# Build script for Travis CI container-based architecture
# Stephen Fegan - sfegan@llr.in2p3.fr - 2015-11-01

sudo: false
language: cpp

matrix:
  include:
    - compiler: gcc-4.8
      env: BUILD_TYPE=Debug GEANT4=TRUE BUILD_CC=gcc-4.8 BUILD_CXX=g++-4.8 CACHE_REBUILD=TRUE
    - compiler: gcc-4.8
      env: BUILD_TYPE=Release GEANT4=TRUE BUILD_CC=gcc-4.8 BUILD_CXX=g++-4.8 CACHE_REBUILD=FALSE
    - compiler: gcc-4.8
      env: BUILD_TYPE=Release GEANT4=FALSE BUILD_CC=gcc-4.8 BUILD_CXX=g++-4.8 CACHE_REBUILD=FALSE
    - compiler: gcc-5
      env: BUILD_TYPE=Debug GEANT4=TRUE BUILD_CC=gcc-5 BUILD_CXX=g++-5 CACHE_REBUILD=TRUE
    - compiler: gcc-5
      env: BUILD_TYPE=Release GEANT4=TRUE BUILD_CC=gcc-5 BUILD_CXX=g++-5 CACHE_REBUILD=FALSE
    - compiler: gcc-5
      env: BUILD_TYPE=Release GEANT4=FALSE BUILD_CC=gcc-5 BUILD_CXX=g++-5 CACHE_REBUILD=FALSE
    - compiler: clang-3.7
      env: BUILD_TYPE=Debug GEANT4=TRUE BUILD_CC=clang-3.7 BUILD_CXX=clang++-3.7 CACHE_REBUILD=TRUE
    - compiler: clang-3.7
      env: BUILD_TYPE=Release GEANT4=TRUE BUILD_CC=clang-3.7 BUILD_CXX=clang++-3.7 CACHE_REBUILD=FALSE
    - compiler: clang-3.7
      env: BUILD_TYPE=Release GEANT4=FALSE BUILD_CC=clang-3.7 BUILD_CXX=clang++-3.7 CACHE_REBUILD=FALSE

addons:
  apt:
    sources:
#    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gsl-bin
    - libgsl0-dev
    - libfftw3-dev
#    - cmake
#    - cmake-data
    - python-numpy
    - g++-4.8
    - g++-5
    - clang-3.7
    - libzmq3-dev
    - python3
    - python3-dev
    - python3-numpy
#    - libczmq-dev <- NOT IN APT WHITE LIST

cache:
  directories:
  - $HOME/local

before_install:
  - if test -n "$BUILD_CC"; then export CC="$BUILD_CC"; fi
  - if test -n "$BUILD_CXX"; then export CXX="$BUILD_CXX"; fi
  - LOCAL=$HOME/local/$CC
  - PATH=$LOCAL/bin:$PATH

# Build SWIG-3, protobuf-3 and Geant4-10 if not available in the cache
# Download and unpack Geant4 data files if necessary
install:
  - |
    echo $HOME
    if [ -d $HOME ]; then ls -l $HOME ; fi
    echo $HOME/local
    if [ -d $HOME/local ]; then ls -l $HOME/local ; fi
    echo $LOCAL
    if [ -d $LOCAL ]; then ls -l $LOCAL ; fi
    echo $LOCAL/bin
    if [ -d $LOCAL/bin ]; then ls -l $LOCAL/bin ; fi
  - |
    if [ ! -f $LOCAL/bin/cmake ];
    then (
      if [ "x$CACHE_REBUILD" != "xTRUE" ]
      then
        exit 1
      fi
      wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3.tar.gz
      tar zxf cmake-3.4.3.tar.gz
      cd cmake-3.4.3
      ./bootstrap  --parallel=3 --prefix=$LOCAL
      make -j3
      make install
    ); fi
  - |
    if [ ! -f $LOCAL/bin/swig ];
    then (
      if [ "x$CACHE_REBUILD" != "xTRUE" ]
      then
        exit 1
      fi
      wget http://sourceforge.net/projects/swig/files/swig/swig-3.0.8/swig-3.0.8.tar.gz &&
      tar zxf swig-3.0.8.tar.gz &&
      cd swig-3.0.8 &&
      ./configure --prefix=$LOCAL --without-alllang --with-python &&
      make -j3 &&
      make install > /dev/null
    ); fi
  - |
    if [ ! -f $LOCAL/bin/protoc ];
    then (
      if [ "x$CACHE_REBUILD" != "xTRUE" ]
      then
        exit 1
      fi
      wget https://github.com/google/protobuf/releases/download/v3.0.0-beta-2/protobuf-cpp-3.0.0-beta-2.tar.gz &&
      tar zxf protobuf-cpp-3.0.0-beta-2.tar.gz &&
      cd protobuf-3.0.0-beta-2 &&
      ./configure --prefix=$LOCAL &&
      make -j3 &&
      make install > /dev/null
    ); fi
  - |
    if [ "x$GEANT4" == "xTRUE" -a ! -f $LOCAL/bin/geant4.sh ];
    then (
      if [ "x$CACHE_REBUILD" != "xTRUE" ]
      then
        exit 1
      fi
      wget http://geant4.cern.ch/support/source/geant4.10.02.p01.tar.gz &&
      tar zxf geant4.10.02.p01.tar.gz &&
      cd geant4.10.02.p01 &&
      mkdir mybuild &&
      cd mybuild &&
      cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$LOCAL .. &&
      make -j3 &&
      make install > /dev/null
    ); fi
  - |
    if [ "x$GEANT4" == "xTRUE" ]
    then
      NO_GEANT4=""
      export G4LEDATA=G4EMLOW.6.48
      export G4LEVELGAMMADATA=G4PhotonEvaporation.3.2
      export G4SAIDXSDATA=G4SAIDDATA.1.1
      export G4NEUTRONXSDATA=G4NEUTRONXS.1.4
      export G4ENSDFSTATEDATA=G4ENSDFSTATE.1.2.1
      GEANT4_DATA=$HOME/geant4_data
      (
        mkdir $GEANT4_DATA
        cd  $GEANT4_DATA
        wget http://geant4.cern.ch/support/source/${G4LEDATA}.tar.gz
        tar zxf ${G4LEDATA}.tar.gz
        wget http://geant4.cern.ch/support/source/${G4LEVELGAMMADATA}.tar.gz
        tar zxf ${G4LEVELGAMMADATA}.tar.gz
        wget http://geant4.cern.ch/support/source/${G4SAIDXSDATA}.tar.gz
        tar zxf ${G4SAIDXSDATA}.tar.gz
        wget http://geant4.cern.ch/support/source/${G4NEUTRONXSDATA}.tar.gz
        tar zxf ${G4NEUTRONXSDATA}.tar.gz
        wget http://geant4.cern.ch/support/source/${G4ENSDFSTATEDATA}.tar.gz
        # Note this data dile actually seems to be a tar file, not a tgz
        tar xf ${G4ENSDFSTATEDATA}.tar.gz
      )
      export G4LEDATA=$GEANT4_DATA/$G4LEDATA
      export G4LEVELGAMMADATA=$GEANT4_DATA/$G4LEVELGAMMADATA
      export G4SAIDXSDATA=$GEANT4_DATA/$G4SAIDXSDATA
      export G4NEUTRONXSDATA=$GEANT4_DATA/$G4NEUTRONXSDATA
      export G4ENSDFSTATEDATA=$GEANT4_DATA/$G4ENSDFSTATEDATA
    else
      NO_GEANT4=-DNO_GEANT4:BOOLEAN=TRUE
    fi

before_script:
  - swig -version
  - cmake -version
  - $CC -v
  - python -V
  - python3 -V

script:
  - |
    mkdir mybuild-travis &&
    cd mybuild-travis &&
    cmake -DCMAKE_PREFIX_PATH=$LOCAL \
          -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DPYTHON_EXECUTABLE=`which python3` \
          $NO_GEANT4 \
          -DCMAKE_INSTALL_PREFIX=build .. &&
    make -j3 &&
    make install &&
    make test
    ./unit_tests/simulation/test_geant4
