before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
#  - sudo add-apt-repository ppa:teward/swig3.0 --yes
  - sudo apt-get update -qq
  - sudo apt-get install -y gsl-bin libgsl0-dev libfftw3-dev cmake cmake-data python-numpy g++-4.8
#  - sudo apt-get install -y swig3.0
  - CC="gcc-4.8"
  - CXX="g++-4.8"
  - $CC -v
  - wget http://sourceforge.net/projects/swig/files/swig/swig-3.0.7/swig-3.0.7.tar.gz
  - tar zxf swig-3.0.7.tar.gz
  - ( cd swig-3.0.7 && ./configure --prefix=/usr --without-alllang --with-python && make -j3 && sudo make install )
  - swig -version
  - wget https://github.com/google/protobuf/releases/download/v3.0.0-beta-1/protobuf-cpp-3.0.0-beta-1.tar.gz
  - tar zxf protobuf-cpp-3.0.0-beta-1.tar.gz
  - ( cd protobuf-3.0.0-beta-1 && ./configure --prefix=/usr && make -j3 && sudo make install )
language: cpp
script:
  - mkdir mybuild-travis && cd mybuild-travis
  - cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build .. && make -j3 && make install && make test
