# Build script for Travis CI container-based architecture
# Stephen Fegan - sfegan@llr.in2p3.fr - 2015-11-01

dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources: &common_sources
    - ubuntu-toolchain-r-test
    packages: &common_packages
    - gsl-bin
    - libgsl0-dev
    - libfftw3-dev
    - python-numpy
    - libzmq3-dev
    - python3
    - python3-dev
    - python3-numpy

matrix:
  include:
    - compiler: gcc-4.9
      env: BUILD_TYPE=Debug GEANT4=TRUE BUILD_CC=gcc-4.9 BUILD_CXX=g++-4.9
      addons: &gcc49_addons
        apt:
          sources:
          - *common_sources
          packages:
          - *common_packages
          - g++-4.9
#    - compiler: gcc-4.9
#      env: BUILD_TYPE=Release GEANT4=TRUE BUILD_CC=gcc-4.9 BUILD_CXX=g++-4.9
#      addons:
#        <<: *gcc49_addons
#    - compiler: gcc-4.9
#      env: BUILD_TYPE=Release GEANT4=FALSE BUILD_CC=gcc-4.9 BUILD_CXX=g++-4.9
#      addons:
#        <<: *gcc49_addons
    - compiler: gcc-5
      env: BUILD_TYPE=Debug GEANT4=TRUE BUILD_CC=gcc-5 BUILD_CXX=g++-5
      addons: &gcc5_addons
        apt:
          sources:
          - *common_sources
          packages:
          - *common_packages
          - g++-5
    - compiler: gcc-5
      env: BUILD_TYPE=Release GEANT4=TRUE BUILD_CC=gcc-5 BUILD_CXX=g++-5
      addons:
        <<: *gcc5_addons
    - compiler: gcc-5
      env: BUILD_TYPE=Release GEANT4=FALSE BUILD_CC=gcc-5 BUILD_CXX=g++-5
      addons:
        <<: *gcc5_addons
    - compiler: gcc-6
      env: BUILD_TYPE=Debug GEANT4=TRUE BUILD_CC=gcc-6 BUILD_CXX=g++-6
      addons: &gcc6_addons
        apt:
          sources:
          - *common_sources
          packages:
          - *common_packages
          - g++-6
    - compiler: clang-3.9
      env: BUILD_TYPE=Debug GEANT4=FALSE BUILD_CC=clang-3.9 BUILD_CXX=clang++-3.9
      addons: &clang39_addons
        apt:
          sources:
          - *common_sources
          - llvm-toolchain-trusty-3.9
          packages:
          - *common_packages
          - clang-3.9
    - compiler: clang-4.0
      env: BUILD_TYPE=Debug GEANT4=FALSE BUILD_CC=clang-4.0 BUILD_CXX=clang++-4.0
      addons: &clang40_addons
        apt:
          sources:
          - *common_sources
          - llvm-toolchain-trusty-4.0
          packages:
          - *common_packages
          - clang-4.0

cache:
  directories:
  - $HOME/local

before_install:
  - if test -n "$BUILD_CC"; then export CC="$BUILD_CC"; fi
  - if test -n "$BUILD_CXX"; then export CXX="$BUILD_CXX"; fi
  - export LOCAL=$HOME/local/$CC
  - export PATH=$LOCAL/bin:$PATH
  - export LD_LIBRARY_PATH=$LOCAL/lib64:$LOCAL/lib:$LD_LIBRARY_PATH
  # Temporarily add this as Eigen produces a vast number of errors - 2016-06-30
  - if [ "x$BUILD_CXX" == "xg++-6" ]; then CXXFLAGS="-Wno-ignored-attributes"; fi

# Build SWIG-3, protobuf-3 and Geant4-10 if not available in the cache
# Download and unpack Geant4 data files if necessary
install:
  - |
    echo $HOME
    if [ -d $HOME ]; then ls -l $HOME ; fi
    echo $HOME/local
    if [ -d $HOME/local ]; then ls -l $HOME/local ; fi
    echo $LOCAL
    if [ -d $LOCAL ]; then ls -l $LOCAL ; fi
    echo $LOCAL/bin
    if [ -d $LOCAL/bin ]; then ls -l $LOCAL/bin ; fi
  - |
    if [ ! -f $LOCAL/bin/cmake ];
    then (
      wget --no-check-certificate https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz &&
      tar zxf cmake-3.7.2.tar.gz &&
      cd cmake-3.7.2 &&
      ./bootstrap  --parallel=3 --prefix=$LOCAL &&
      make -j3 &&
      make install > /dev/null &&
      touch $HOME/suppress_geant_build
    ); fi
  - |
    if [ ! -f $LOCAL/bin/swig ]
    then (
      wget https://sourceforge.net/projects/swig/files/swig/swig-3.0.12/swig-3.0.12.tar.gz &&
      tar zxf swig-3.0.12.tar.gz &&
      cd swig-3.0.12 &&
      ./configure --prefix=$LOCAL --without-alllang --with-python &&
      make -j3 &&
      make install > /dev/null &&
      touch $HOME/suppress_geant_build
    ); fi
  - |
    if [ ! -f $LOCAL/bin/protoc ]
    then (
      wget https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-cpp-3.2.0.tar.gz &&
      tar zxf protobuf-cpp-3.2.0.tar.gz &&
      cd protobuf-3.2.0 &&
      ./configure --prefix=$LOCAL &&
      make -j3 &&
      make install > /dev/null &&
      touch $HOME/suppress_geant_build
    ); fi
  - |
    if [ "x$GEANT4" == "xTRUE" -a ! -f $LOCAL/bin/geant4.sh -a ! -f $HOME/suppress_geant_build ]
    then (
      wget http://geant4.cern.ch/support/source/geant4.10.03.p01.tar.gz &&
      tar zxf geant4.10.03.p01.tar.gz &&
      cd geant4.10.03.p01 &&
      mkdir mybuild &&
      cd mybuild &&
      cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$LOCAL .. &&
      make -j3 &&
      make install > /dev/null
    ); fi
  - |
    if [ "x$GEANT4" == "xTRUE" ]
    then
      NO_GEANT4=""
      export G4LEDATA=6.50
      export G4LEVELGAMMADATA=4.3.2
      export G4SAIDXSDATA=1.1
      export G4NEUTRONXSDATA=1.4
      export G4ENSDFSTATEDATA=2.1
      GEANT4_DATA=$HOME/geant4_data
      (
        mkdir $GEANT4_DATA
        cd  $GEANT4_DATA
        wget http://geant4.cern.ch/support/source/G4EMLOW.${G4LEDATA}.tar.gz
        tar zxf G4EMLOW.${G4LEDATA}.tar.gz
        wget http://geant4.cern.ch/support/source/G4PhotonEvaporation.${G4LEVELGAMMADATA}.tar.gz
        tar zxf G4PhotonEvaporation.${G4LEVELGAMMADATA}.tar.gz
        wget http://geant4.cern.ch/support/source/G4SAIDDATA.${G4SAIDXSDATA}.tar.gz
        tar zxf G4SAIDDATA.${G4SAIDXSDATA}.tar.gz
        wget http://geant4.cern.ch/support/source/G4NEUTRONXS.${G4NEUTRONXSDATA}.tar.gz
        tar zxf G4NEUTRONXS.${G4NEUTRONXSDATA}.tar.gz
        wget http://geant4.cern.ch/support/source/G4ENSDFSTATE.${G4ENSDFSTATEDATA}.tar.gz
        tar zxf G4ENSDFSTATE.${G4ENSDFSTATEDATA}.tar.gz
      )
      export G4LEDATA=$GEANT4_DATA/G4EMLOW${G4LEDATA}
      export G4LEVELGAMMADATA=$GEANT4_DATA/G4PhotonEvaporation${G4LEVELGAMMADATA}
      export G4SAIDXSDATA=$GEANT4_DATA/G4SAIDDATA${G4SAIDXSDATA}
      export G4NEUTRONXSDATA=$GEANT4_DATA/G4NEUTRONXS${G4NEUTRONXSDATA}
      export G4ENSDFSTATEDATA=$GEANT4_DATA/G4ENSDFSTATE${G4ENSDFSTATEDATA}
    else
      NO_GEANT4=-DNO_GEANT4:BOOLEAN=TRUE
    fi

before_script:
  - swig -version
  - cmake -version
  - $CC -v
  - python -V
  - python3 -V

script:
  - |
    mkdir mybuild-travis &&
    cd mybuild-travis &&
    cmake -DCMAKE_PREFIX_PATH=$LOCAL \
          -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX \
          -DCMAKE_CXX_FLAGS=$CXXFLAGS \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DPYTHON_EXECUTABLE=`which python3` \
          $NO_GEANT4 \
          -DCMAKE_INSTALL_PREFIX=build .. &&
    make -j3 &&
    make install | tail &&
    make test
#    ./unit_tests/calib/test_spe_fit

#after_failure:
#  - cat CMakeFiles/CMakeError.log
