env:
  - CC="gcc-4.8" CXX="g++-4.8" BUILD_TYPE="Debug" NO_GEANT4=""
  - CC="gcc-4.8" CXX="g++-4.8" BUILD_TYPE="Release" NO_GEANT4=""
  - CC="gcc-4.8" CXX="g++-4.8" BUILD_TYPE="Release" NO_GEANT4="-DNO_GEANT4:BOOLEAN=TRUE" 
  - CC="gcc-5" CXX="g++-5" BUILD_TYPE="Release" NO_GEANT4=""
  - CC="gcc-5" CXX="g++-5" BUILD_TYPE="Release" NO_GEANT4="-DNO_GEANT4:BOOLEAN=TRUE"

language: cpp
sudo: false

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    packages:
    - gsl-bin
    - libgsl0-dev
    - libfftw3-dev
    - cmake
    - cmake-data
    - python-numpy
    - g++-4.8
    - g++-5

cache:
  directories:
  - $HOME/local

before_install:
  - LOCAL=$HOME/local/${CC}
  - PATH=$LOCAL/bin:$PATH

install:
  - |
    if [ ! -f $LOCAL/bin/swig ];
    then (
      wget http://sourceforge.net/projects/swig/files/swig/swig-3.0.7/swig-3.0.7.tar.gz &&
      tar zxf swig-3.0.7.tar.gz &&
      cd swig-3.0.7 &&
      ./configure --prefix=$LOCAL --without-alllang --with-python &&
      make -j3 &&
      make install > /dev/null
    ); fi 
  - |
    if [ ! -f $LOCAL/bin/protoc ];
    then (
      wget https://github.com/google/protobuf/releases/download/v3.0.0-beta-1/protobuf-cpp-3.0.0-beta-1.tar.gz &&
      tar zxf protobuf-cpp-3.0.0-beta-1.tar.gz &&
      cd protobuf-3.0.0-beta-1 &&
      ./configure --prefix=$LOCAL &&
      make -j3 &&
      make install > /dev/null
    ); fi
  - |
    if [ "x$NO_GEANT4" == "x" -a ! -f $LOCAL/bin/geant4.sh ];
    then (
      wget http://geant4.cern.ch/support/source/geant4.10.01.p02.tar.gz &&
      tar zxf geant4.10.01.p02.tar.gz &&
      cd geant4.10.01.p02 &&
      mkdir mybuild &&
      cd mybuild &&
      cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$LOCAL .. &&
      make -j3 &&
      make install > /dev/null
    ); fi
  - |
    if  [ "x$NO_GEANT4" == "x" ]
    then (
      mkdir $HOME/geant4_data
      cd  $HOME/geant4_data
      wget http://geant4.cern.ch/support/source/G4PhotonEvaporation.3.1.tar.gz
      tar zxf G4PhotonEvaporation.3.1.tar.gz
      export G4LEVELGAMMADATA=`pwd`/PhotonEvaporation3.1
      wget http://geant4.cern.ch/support/source/G4SAIDDATA.1.1.tar.gz
      tar zxf G4SAIDDATA.1.1.tar.gz
      export G4SAIDXSDATA=`pwd`/G4SAIDDATA1.1
      wget http://geant4.cern.ch/support/source/G4NEUTRONXS.1.4.tar.gz
      tar zxf G4NEUTRONXS.1.4.tar.gz
      export G4NEUTRONXSDATA=`pwd`/G4NEUTRONXS1.4
    ); fi
      
before_script:
  - swig -version
  - cmake -version
  - $CC -v

script:
  - |
    mkdir mybuild-travis &&
    cd mybuild-travis &&
    cmake -DCMAKE_PREFIX_PATH=$LOCAL -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE $NO_GEANT4 -DCMAKE_INSTALL_PREFIX=build .. &&
    make -j3 &&
    make install &&
    make test
  - ./unit_tests/simulation/test_geant4
