before_install:
  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
  - sudo apt-get update -qq
  - sudo apt-get install -y gsl-bin libfftw3-3 cmake cmake-data
  - wget https://github.com/google/protobuf/releases/download/v3.0.0-beta-1/protobuf-cpp-3.0.0-beta-1.tar.gz
  - tar zxf protobuf-cpp-3.0.0-beta-1.tar.gz
  - cd protobuf-3.0.0-beta-1
  - ./configure
  - make
  - make check
  - make install
language: cpp
script:
  - mkdir mybuild-travis
  - cd mybuild-travis
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build ..
  - make -j2
  - make install

