# Build script for Travis CI container-based architecture
# Stephen Fegan - sfegan@llr.in2p3.fr - 2015-11-01

sudo: false
language: cpp

matrix:
  include:
    - compiler: gcc-4.8
      env: BUILD_CC=gcc-4.8 BUILD_CXX=g++-4.8 BUILD_TYPE=Debug NO_GEANT4=""
    - compiler: gcc-4.8
      env: BUILD_CC=gcc-4.8 BUILD_CXX=g++-4.8 BUILD_TYPE=Release NO_GEANT4=""
    - compiler: gcc-4.8
      env: BUILD_CC=gcc-4.8 BUILD_CXX=g++-4.8 BUILD_TYPE=Release NO_GEANT4=-DNO_GEANT4:BOOLEAN=TRUE
    - compiler: gcc-5
      env: BUILD_CC=gcc-5 BUILD_CXX=g++-5 BUILD_TYPE=Debug NO_GEANT4=""
    - compiler: gcc-5
      env: BUILD_CC=gcc-5 BUILD_CXX=g++-5 BUILD_TYPE=Release NO_GEANT4=""
    - compiler: gcc-5
      env: BUILD_CC=gcc-5 BUILD_CXX=g++-5 BUILD_TYPE=Release NO_GEANT4=-DNO_GEANT4:BOOLEAN=TRUE
    - compiler: clang-3.7
      env: BUILD_CC=clang-3.7 BUILD_CXX=clang++-3.7 BUILD_TYPE=Debug NO_GEANT4=-DNO_GEANT4:BOOLEAN=TRUE
    - compiler: clang-3.7
      env: BUILD_CC=clang-3.7 BUILD_CXX=clang++-3.7 BUILD_TYPE=Release NO_GEANT4=-DNO_GEANT4:BOOLEAN=TRUE
    - compiler: clang-3.7
      env: BUILD_CC=clang-3.7 BUILD_CXX=clang++-3.7 BUILD_TYPE=Release NO_GEANT4=""

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gsl-bin
    - libgsl0-dev
    - libfftw3-dev
    - cmake
    - cmake-data
    - python-numpy
    - g++-4.8
    - g++-5
    - clang-3.7
    - libzmq3-dev
    - libczmq-dev

cache:
  directories:
  - $HOME/local

before_install:
  - if test -n "$BUILD_CC"; then export CC="$BUILD_CC"; fi
  - if test -n "$BUILD_CXX"; then export CXX="$BUILD_CXX"; fi
  - LOCAL=$HOME/local/$CC
  - PATH=$LOCAL/bin:$PATH

# Build SWIG-3, protobuf-3 and Geant4-10 if not available in the cache
# Download and unpack Geant4 data files if necessary
install:
  - |
    echo $HOME
    if [ -d $HOME ]; then ls -l $HOME ; fi
    echo $HOME/local
    if [ -d $HOME/local ]; then ls -l $HOME/local ; fi
    echo $LOCAL
    if [ -d $LOCAL ]; then ls -l $LOCAL ; fi
    echo $LOCAL/bin
    if [ -d $LOCAL/bin ]; then ls -l $LOCAL/bin ; fi
  - |
    if [ ! -f $LOCAL/bin/swig ];
    then (
      wget http://sourceforge.net/projects/swig/files/swig/swig-3.0.7/swig-3.0.7.tar.gz &&
      tar zxf swig-3.0.7.tar.gz &&
      cd swig-3.0.7 &&
      ./configure --prefix=$LOCAL --without-alllang --with-python &&
      make -j3 &&
      make install > /dev/null
    ); fi
  - |
    if [ ! -f $LOCAL/bin/protoc ];
    then (
      wget https://github.com/google/protobuf/releases/download/v3.0.0-beta-1/protobuf-cpp-3.0.0-beta-1.tar.gz &&
      tar zxf protobuf-cpp-3.0.0-beta-1.tar.gz &&
      cd protobuf-3.0.0-beta-1 &&
      ./configure --prefix=$LOCAL &&
      make -j3 &&
      make install > /dev/null
    ); fi
  - |
    if [ "x$NO_GEANT4" == "x" -a ! -f $LOCAL/bin/geant4.sh ];
    then (
      wget http://geant4.cern.ch/support/source/geant4.10.01.p02.tar.gz &&
      tar zxf geant4.10.01.p02.tar.gz &&
      cd geant4.10.01.p02 &&
      mkdir mybuild &&
      cd mybuild &&
      cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$LOCAL .. &&
      make -j3 &&
      make install > /dev/null
    ); fi
  - |
    if  [ "x$NO_GEANT4" == "x" ]
    then
      GEANT4_DATA=$HOME/geant4_data
      (
        mkdir $GEANT4_DATA
        cd  $GEANT4_DATA
        wget http://geant4.cern.ch/support/source/G4EMLOW.6.41.tar.gz
        tar zxf G4EMLOW.6.41.tar.gz
        wget http://geant4.cern.ch/support/source/G4PhotonEvaporation.3.1.tar.gz
        tar zxf G4PhotonEvaporation.3.1.tar.gz
        wget http://geant4.cern.ch/support/source/G4SAIDDATA.1.1.tar.gz
        tar zxf G4SAIDDATA.1.1.tar.gz
        wget http://geant4.cern.ch/support/source/G4NEUTRONXS.1.4.tar.gz
        tar zxf G4NEUTRONXS.1.4.tar.gz
      )
      export G4LEDATA=$GEANT4_DATA/G4EMLOW6.41
      export G4LEVELGAMMADATA=$GEANT4_DATA/PhotonEvaporation3.1
      export G4SAIDXSDATA=$GEANT4_DATA/G4SAIDDATA1.1
      export G4NEUTRONXSDATA=$GEANT4_DATA/G4NEUTRONXS1.4
    fi

before_script:
  - swig -version
  - cmake -version
  - $CC -v

script:
  - |
    mkdir mybuild-travis &&
    cd mybuild-travis &&
    cmake -DCMAKE_PREFIX_PATH=$LOCAL \
          -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          $NO_GEANT4 \
          -DCMAKE_INSTALL_PREFIX=build .. &&
    make -j3 &&
    make install &&
    make test
