/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_notw.native -n 8 -standalone -fma -generic-arith -compact -name dft_codelet_c2c_8 */

/*
 * This function contains 52 FP additions, 8 FP multiplications,
 * (or, 44 additions, 0 multiplications, 8 fused multiply/add),
 * 28 stack variables, 1 constants, and 32 memory accesses
 */
void dft_codelet_c2c_8(const R * ri, const R * ii, R * ro, R * io, stride is, stride os, INT v, INT ivs, INT ovs)
{
  DK(KP707106781, +0.707106781186547524400844362104849039284835938);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, ri = ri + ivs, ii = ii + ivs, ro = ro + ovs, io = io + ovs, MAKE_VOLATILE_STRIDE(32, is), MAKE_VOLATILE_STRIDE(32, os)) {
      E T3, Tn, Ti, TC, T6, TB, Tl, To, Td, TN, Tz, TH, Ta, TM, Tu;
      E TG;
      {
        E T1, T2, Tj, Tk;
        T1 = ri[0];
        T2 = ri[WS(is, 4)];
        T3 = ADD(T1, T2);
        Tn = SUB(T1, T2);
        {
          E Tg, Th, T4, T5;
          Tg = ii[0];
          Th = ii[WS(is, 4)];
          Ti = ADD(Tg, Th);
          TC = SUB(Tg, Th);
          T4 = ri[WS(is, 2)];
          T5 = ri[WS(is, 6)];
          T6 = ADD(T4, T5);
          TB = SUB(T4, T5);
        }
        Tj = ii[WS(is, 2)];
        Tk = ii[WS(is, 6)];
        Tl = ADD(Tj, Tk);
        To = SUB(Tj, Tk);
        {
          E Tb, Tc, Tv, Tw, Tx, Ty;
          Tb = ri[WS(is, 7)];
          Tc = ri[WS(is, 3)];
          Tv = SUB(Tb, Tc);
          Tw = ii[WS(is, 7)];
          Tx = ii[WS(is, 3)];
          Ty = SUB(Tw, Tx);
          Td = ADD(Tb, Tc);
          TN = ADD(Tw, Tx);
          Tz = SUB(Tv, Ty);
          TH = ADD(Tv, Ty);
        }
        {
          E T8, T9, Tq, Tr, Ts, Tt;
          T8 = ri[WS(is, 1)];
          T9 = ri[WS(is, 5)];
          Tq = SUB(T8, T9);
          Tr = ii[WS(is, 1)];
          Ts = ii[WS(is, 5)];
          Tt = SUB(Tr, Ts);
          Ta = ADD(T8, T9);
          TM = ADD(Tr, Ts);
          Tu = ADD(Tq, Tt);
          TG = SUB(Tt, Tq);
        }
      }
      {
        E T7, Te, TP, TQ;
        T7 = ADD(T3, T6);
        Te = ADD(Ta, Td);
        ro[WS(os, 4)] = SUB(T7, Te);
        ro[0] = ADD(T7, Te);
        TP = ADD(Ti, Tl);
        TQ = ADD(TM, TN);
        io[WS(os, 4)] = SUB(TP, TQ);
        io[0] = ADD(TP, TQ);
      }
      {
        E Tf, Tm, TL, TO;
        Tf = SUB(Td, Ta);
        Tm = SUB(Ti, Tl);
        io[WS(os, 2)] = ADD(Tf, Tm);
        io[WS(os, 6)] = SUB(Tm, Tf);
        TL = SUB(T3, T6);
        TO = SUB(TM, TN);
        ro[WS(os, 6)] = SUB(TL, TO);
        ro[WS(os, 2)] = ADD(TL, TO);
      }
      {
        E Tp, TA, TJ, TK;
        Tp = ADD(Tn, To);
        TA = ADD(Tu, Tz);
        ro[WS(os, 5)] = FNMS(KP707106781, TA, Tp);
        ro[WS(os, 1)] = FMA(KP707106781, TA, Tp);
        TJ = SUB(TC, TB);
        TK = ADD(TG, TH);
        io[WS(os, 5)] = FNMS(KP707106781, TK, TJ);
        io[WS(os, 1)] = FMA(KP707106781, TK, TJ);
      }
      {
        E TD, TE, TF, TI;
        TD = ADD(TB, TC);
        TE = SUB(Tz, Tu);
        io[WS(os, 7)] = FNMS(KP707106781, TE, TD);
        io[WS(os, 3)] = FMA(KP707106781, TE, TD);
        TF = SUB(Tn, To);
        TI = SUB(TG, TH);
        ro[WS(os, 7)] = FNMS(KP707106781, TI, TF);
        ro[WS(os, 3)] = FMA(KP707106781, TI, TF);
      }
    }
  }
}
