/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_notw.native -n 30 -standalone -fma -generic-arith -compact -name dft_codelet_c2c_30 */

/*
 * This function contains 372 FP additions, 168 FP multiplications,
 * (or, 204 additions, 0 multiplications, 168 fused multiply/add),
 * 87 stack variables, 6 constants, and 120 memory accesses
 */
void dft_codelet_c2c_30(const R * ri, const R * ii, R * ro, R * io, stride is, stride os, INT v, INT ivs, INT ovs)
{
  DK(KP951056516, +0.951056516295153572116439333379382143405698634);
  DK(KP866025403, +0.866025403784438646763723170752936183471402627);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, ri = ri + ivs, ii = ii + ivs, ro = ro + ovs, io = io + ovs, MAKE_VOLATILE_STRIDE(120, is), MAKE_VOLATILE_STRIDE(120, os)) {
      E T9, T52, T40, T13, T2r, T1a, T5N, T2s, T3X, T51, Ti, T55, T4b,
       T1e, T2u;
      E T1l, T5O, T2v, T48, T54, T1x, T5G, T2z, T3c, T4M, Ts, T4N, T3f,
       T1q, T2y;
      E TB, T4Q, T3q, T1B, T2B, T1I, T5H, T2C, T3n, T4P, TL, T4U, T3C,
       T1N, T2F;
      E T1U, T5J, T2G, T3z, T4T, T25, T5K, T2J, T3K, T4W, TU, T4X, T3N,
       T1Y, T2I;
      {
        E T1, T4, T7, T8, T3Z, T3Y, T11, T12;
        T1 = ri[0];
        {
          E T2, T3, T5, T6;
          T2 = ri[WS(is, 6)];
          T3 = ri[WS(is, 24)];
          T4 = ADD(T2, T3);
          T5 = ri[WS(is, 12)];
          T6 = ri[WS(is, 18)];
          T7 = ADD(T5, T6);
          T8 = ADD(T4, T7);
          T3Z = SUB(T5, T6);
          T3Y = SUB(T2, T3);
        }
        T9 = ADD(T1, T8);
        T52 = FNMS(KP618033988, T3Y, T3Z);
        T40 = FMA(KP618033988, T3Z, T3Y);
        T11 = FNMS(KP250000000, T8, T1);
        T12 = SUB(T4, T7);
        T13 = FMA(KP559016994, T12, T11);
        T2r = FNMS(KP559016994, T12, T11);
      }
      {
        E T3R, T3S, T3T, T16, T3U, T19, T3V, T3W;
        T3R = ii[0];
        {
          E T14, T15, T17, T18;
          T14 = ii[WS(is, 6)];
          T15 = ii[WS(is, 24)];
          T3S = ADD(T14, T15);
          T17 = ii[WS(is, 12)];
          T18 = ii[WS(is, 18)];
          T3T = ADD(T17, T18);
          T16 = SUB(T14, T15);
          T3U = ADD(T3S, T3T);
          T19 = SUB(T17, T18);
        }
        T1a = FMA(KP618033988, T19, T16);
        T5N = ADD(T3R, T3U);
        T2s = FNMS(KP618033988, T16, T19);
        T3V = FNMS(KP250000000, T3U, T3R);
        T3W = SUB(T3S, T3T);
        T3X = FMA(KP559016994, T3W, T3V);
        T51 = FNMS(KP559016994, T3W, T3V);
      }
      {
        E Ta, Td, Tg, Th, T4a, T49, T1c, T1d;
        Ta = ri[WS(is, 15)];
        {
          E Tb, Tc, Te, Tf;
          Tb = ri[WS(is, 21)];
          Tc = ri[WS(is, 9)];
          Td = ADD(Tb, Tc);
          Te = ri[WS(is, 27)];
          Tf = ri[WS(is, 3)];
          Tg = ADD(Te, Tf);
          Th = ADD(Td, Tg);
          T4a = SUB(Te, Tf);
          T49 = SUB(Tb, Tc);
        }
        Ti = ADD(Ta, Th);
        T55 = FNMS(KP618033988, T49, T4a);
        T4b = FMA(KP618033988, T4a, T49);
        T1c = FNMS(KP250000000, Th, Ta);
        T1d = SUB(Td, Tg);
        T1e = FMA(KP559016994, T1d, T1c);
        T2u = FNMS(KP559016994, T1d, T1c);
      }
      {
        E T42, T43, T44, T1h, T45, T1k, T46, T47;
        T42 = ii[WS(is, 15)];
        {
          E T1f, T1g, T1i, T1j;
          T1f = ii[WS(is, 21)];
          T1g = ii[WS(is, 9)];
          T43 = ADD(T1f, T1g);
          T1i = ii[WS(is, 27)];
          T1j = ii[WS(is, 3)];
          T44 = ADD(T1i, T1j);
          T1h = SUB(T1f, T1g);
          T45 = ADD(T43, T44);
          T1k = SUB(T1i, T1j);
        }
        T1l = FMA(KP618033988, T1k, T1h);
        T5O = ADD(T42, T45);
        T2v = FNMS(KP618033988, T1h, T1k);
        T46 = FNMS(KP250000000, T45, T42);
        T47 = SUB(T43, T44);
        T48 = FMA(KP559016994, T47, T46);
        T54 = FNMS(KP559016994, T47, T46);
      }
      {
        E T36, T37, T38, T1t, T39, T1w, T3a, T3b;
        T36 = ii[WS(is, 10)];
        {
          E T1r, T1s, T1u, T1v;
          T1r = ii[WS(is, 16)];
          T1s = ii[WS(is, 4)];
          T37 = ADD(T1r, T1s);
          T1u = ii[WS(is, 22)];
          T1v = ii[WS(is, 28)];
          T38 = ADD(T1u, T1v);
          T1t = SUB(T1r, T1s);
          T39 = ADD(T37, T38);
          T1w = SUB(T1u, T1v);
        }
        T1x = FMA(KP618033988, T1w, T1t);
        T5G = ADD(T36, T39);
        T2z = FNMS(KP618033988, T1t, T1w);
        T3a = FNMS(KP250000000, T39, T36);
        T3b = SUB(T37, T38);
        T3c = FMA(KP559016994, T3b, T3a);
        T4M = FNMS(KP559016994, T3b, T3a);
      }
      {
        E Tk, Tn, Tq, Tr, T3e, T3d, T1o, T1p;
        Tk = ri[WS(is, 10)];
        {
          E Tl, Tm, To, Tp;
          Tl = ri[WS(is, 16)];
          Tm = ri[WS(is, 4)];
          Tn = ADD(Tl, Tm);
          To = ri[WS(is, 22)];
          Tp = ri[WS(is, 28)];
          Tq = ADD(To, Tp);
          Tr = ADD(Tn, Tq);
          T3e = SUB(To, Tp);
          T3d = SUB(Tl, Tm);
        }
        Ts = ADD(Tk, Tr);
        T4N = FNMS(KP618033988, T3d, T3e);
        T3f = FMA(KP618033988, T3e, T3d);
        T1o = FNMS(KP250000000, Tr, Tk);
        T1p = SUB(Tn, Tq);
        T1q = FMA(KP559016994, T1p, T1o);
        T2y = FNMS(KP559016994, T1p, T1o);
      }
      {
        E Tt, Tw, Tz, TA, T3p, T3o, T1z, T1A;
        Tt = ri[WS(is, 25)];
        {
          E Tu, Tv, Tx, Ty;
          Tu = ri[WS(is, 1)];
          Tv = ri[WS(is, 19)];
          Tw = ADD(Tu, Tv);
          Tx = ri[WS(is, 7)];
          Ty = ri[WS(is, 13)];
          Tz = ADD(Tx, Ty);
          TA = ADD(Tw, Tz);
          T3p = SUB(Tx, Ty);
          T3o = SUB(Tu, Tv);
        }
        TB = ADD(Tt, TA);
        T4Q = FNMS(KP618033988, T3o, T3p);
        T3q = FMA(KP618033988, T3p, T3o);
        T1z = FNMS(KP250000000, TA, Tt);
        T1A = SUB(Tw, Tz);
        T1B = FMA(KP559016994, T1A, T1z);
        T2B = FNMS(KP559016994, T1A, T1z);
      }
      {
        E T3h, T3i, T3j, T1E, T3k, T1H, T3l, T3m;
        T3h = ii[WS(is, 25)];
        {
          E T1C, T1D, T1F, T1G;
          T1C = ii[WS(is, 1)];
          T1D = ii[WS(is, 19)];
          T3i = ADD(T1C, T1D);
          T1F = ii[WS(is, 7)];
          T1G = ii[WS(is, 13)];
          T3j = ADD(T1F, T1G);
          T1E = SUB(T1C, T1D);
          T3k = ADD(T3i, T3j);
          T1H = SUB(T1F, T1G);
        }
        T1I = FMA(KP618033988, T1H, T1E);
        T5H = ADD(T3h, T3k);
        T2C = FNMS(KP618033988, T1E, T1H);
        T3l = FNMS(KP250000000, T3k, T3h);
        T3m = SUB(T3i, T3j);
        T3n = FMA(KP559016994, T3m, T3l);
        T4P = FNMS(KP559016994, T3m, T3l);
      }
      {
        E TD, TG, TJ, TK, T3B, T3A, T1L, T1M;
        TD = ri[WS(is, 20)];
        {
          E TE, TF, TH, TI;
          TE = ri[WS(is, 26)];
          TF = ri[WS(is, 14)];
          TG = ADD(TE, TF);
          TH = ri[WS(is, 2)];
          TI = ri[WS(is, 8)];
          TJ = ADD(TH, TI);
          TK = ADD(TG, TJ);
          T3B = SUB(TH, TI);
          T3A = SUB(TE, TF);
        }
        TL = ADD(TD, TK);
        T4U = FNMS(KP618033988, T3A, T3B);
        T3C = FMA(KP618033988, T3B, T3A);
        T1L = FNMS(KP250000000, TK, TD);
        T1M = SUB(TG, TJ);
        T1N = FMA(KP559016994, T1M, T1L);
        T2F = FNMS(KP559016994, T1M, T1L);
      }
      {
        E T3t, T3u, T3v, T1Q, T3w, T1T, T3x, T3y;
        T3t = ii[WS(is, 20)];
        {
          E T1O, T1P, T1R, T1S;
          T1O = ii[WS(is, 26)];
          T1P = ii[WS(is, 14)];
          T3u = ADD(T1O, T1P);
          T1R = ii[WS(is, 2)];
          T1S = ii[WS(is, 8)];
          T3v = ADD(T1R, T1S);
          T1Q = SUB(T1O, T1P);
          T3w = ADD(T3u, T3v);
          T1T = SUB(T1R, T1S);
        }
        T1U = FMA(KP618033988, T1T, T1Q);
        T5J = ADD(T3t, T3w);
        T2G = FNMS(KP618033988, T1Q, T1T);
        T3x = FNMS(KP250000000, T3w, T3t);
        T3y = SUB(T3u, T3v);
        T3z = FMA(KP559016994, T3y, T3x);
        T4T = FNMS(KP559016994, T3y, T3x);
      }
      {
        E T3E, T3F, T3G, T21, T3H, T24, T3I, T3J;
        T3E = ii[WS(is, 5)];
        {
          E T1Z, T20, T22, T23;
          T1Z = ii[WS(is, 11)];
          T20 = ii[WS(is, 29)];
          T3F = ADD(T1Z, T20);
          T22 = ii[WS(is, 17)];
          T23 = ii[WS(is, 23)];
          T3G = ADD(T22, T23);
          T21 = SUB(T1Z, T20);
          T3H = ADD(T3F, T3G);
          T24 = SUB(T22, T23);
        }
        T25 = FMA(KP618033988, T24, T21);
        T5K = ADD(T3E, T3H);
        T2J = FNMS(KP618033988, T21, T24);
        T3I = FNMS(KP250000000, T3H, T3E);
        T3J = SUB(T3F, T3G);
        T3K = FMA(KP559016994, T3J, T3I);
        T4W = FNMS(KP559016994, T3J, T3I);
      }
      {
        E TM, TP, TS, TT, T3M, T3L, T1W, T1X;
        TM = ri[WS(is, 5)];
        {
          E TN, TO, TQ, TR;
          TN = ri[WS(is, 11)];
          TO = ri[WS(is, 29)];
          TP = ADD(TN, TO);
          TQ = ri[WS(is, 17)];
          TR = ri[WS(is, 23)];
          TS = ADD(TQ, TR);
          TT = ADD(TP, TS);
          T3M = SUB(TQ, TR);
          T3L = SUB(TN, TO);
        }
        TU = ADD(TM, TT);
        T4X = FNMS(KP618033988, T3L, T3M);
        T3N = FMA(KP618033988, T3M, T3L);
        T1W = FNMS(KP250000000, TT, TM);
        T1X = SUB(TP, TS);
        T1Y = FMA(KP559016994, T1X, T1W);
        T2I = FNMS(KP559016994, T1X, T1W);
      }
      {
        E Tj, T5P, TW, T5S, T5M, T5Q, T5F, T5R;
        Tj = SUB(T9, Ti);
        T5P = SUB(T5N, T5O);
        {
          E TC, TV, T5I, T5L;
          TC = SUB(Ts, TB);
          TV = SUB(TL, TU);
          TW = ADD(TC, TV);
          T5S = SUB(TV, TC);
          T5I = SUB(T5G, T5H);
          T5L = SUB(T5J, T5K);
          T5M = SUB(T5I, T5L);
          T5Q = ADD(T5I, T5L);
        }
        ro[WS(os, 15)] = ADD(Tj, TW);
        io[WS(os, 15)] = ADD(T5P, T5Q);
        T5F = FNMS(KP500000000, TW, Tj);
        ro[WS(os, 5)] = FNMS(KP866025403, T5M, T5F);
        ro[WS(os, 25)] = FMA(KP866025403, T5M, T5F);
        T5R = FNMS(KP500000000, T5Q, T5P);
        io[WS(os, 5)] = FNMS(KP866025403, T5S, T5R);
        io[WS(os, 25)] = FMA(KP866025403, T5S, T5R);
      }
      {
        E TX, T5X, T10, T60, T5W, T5Y, T5T, T5Z;
        TX = ADD(T9, Ti);
        T5X = ADD(T5N, T5O);
        {
          E TY, TZ, T5U, T5V;
          TY = ADD(Ts, TB);
          TZ = ADD(TL, TU);
          T10 = ADD(TY, TZ);
          T60 = SUB(TZ, TY);
          T5U = ADD(T5G, T5H);
          T5V = ADD(T5J, T5K);
          T5W = SUB(T5U, T5V);
          T5Y = ADD(T5U, T5V);
        }
        ro[0] = ADD(TX, T10);
        io[0] = ADD(T5X, T5Y);
        T5T = FNMS(KP500000000, T10, TX);
        ro[WS(os, 20)] = FNMS(KP866025403, T5W, T5T);
        ro[WS(os, 10)] = FMA(KP866025403, T5W, T5T);
        T5Z = FNMS(KP500000000, T5Y, T5X);
        io[WS(os, 10)] = FMA(KP866025403, T60, T5Z);
        io[WS(os, 20)] = FNMS(KP866025403, T60, T5Z);
      }
      {
        E T1n, T29, T4z, T4H, T1K, T2a, T27, T2b, T28, T2c, T4s, T4E,
         T4v, T4F, T4A;
        E T4I;
        {
          E T1b, T1m, T4x, T4y;
          T1b = FNMS(KP951056516, T1a, T13);
          T1m = FNMS(KP951056516, T1l, T1e);
          T1n = SUB(T1b, T1m);
          T29 = ADD(T1b, T1m);
          T4x = FMA(KP951056516, T40, T3X);
          T4y = FMA(KP951056516, T4b, T48);
          T4z = SUB(T4x, T4y);
          T4H = ADD(T4x, T4y);
        }
        {
          E T1y, T1J, T1V, T26;
          T1y = FNMS(KP951056516, T1x, T1q);
          T1J = FNMS(KP951056516, T1I, T1B);
          T1K = SUB(T1y, T1J);
          T2a = ADD(T1y, T1J);
          T1V = FNMS(KP951056516, T1U, T1N);
          T26 = FNMS(KP951056516, T25, T1Y);
          T27 = SUB(T1V, T26);
          T2b = ADD(T1V, T26);
        }
        T28 = ADD(T1K, T27);
        T2c = ADD(T2a, T2b);
        {
          E T4q, T4r, T4t, T4u;
          T4q = FMA(KP951056516, T3f, T3c);
          T4r = FMA(KP951056516, T3q, T3n);
          T4s = SUB(T4q, T4r);
          T4E = ADD(T4q, T4r);
          T4t = FMA(KP951056516, T3C, T3z);
          T4u = FMA(KP951056516, T3N, T3K);
          T4v = SUB(T4t, T4u);
          T4F = ADD(T4t, T4u);
        }
        T4A = ADD(T4s, T4v);
        T4I = ADD(T4E, T4F);
        ro[WS(os, 9)] = ADD(T1n, T28);
        io[WS(os, 9)] = ADD(T4z, T4A);
        ro[WS(os, 24)] = ADD(T29, T2c);
        io[WS(os, 24)] = ADD(T4H, T4I);
        {
          E T4p, T4w, T4B, T4C;
          T4p = FNMS(KP500000000, T28, T1n);
          T4w = SUB(T4s, T4v);
          ro[WS(os, 29)] = FNMS(KP866025403, T4w, T4p);
          ro[WS(os, 19)] = FMA(KP866025403, T4w, T4p);
          T4B = FNMS(KP500000000, T4A, T4z);
          T4C = SUB(T27, T1K);
          io[WS(os, 19)] = FMA(KP866025403, T4C, T4B);
          io[WS(os, 29)] = FNMS(KP866025403, T4C, T4B);
        }
        {
          E T4D, T4G, T4J, T4K;
          T4D = FNMS(KP500000000, T2c, T29);
          T4G = SUB(T4E, T4F);
          ro[WS(os, 14)] = FNMS(KP866025403, T4G, T4D);
          ro[WS(os, 4)] = FMA(KP866025403, T4G, T4D);
          T4J = FNMS(KP500000000, T4I, T4H);
          T4K = SUB(T2b, T2a);
          io[WS(os, 4)] = FMA(KP866025403, T4K, T4J);
          io[WS(os, 14)] = FNMS(KP866025403, T4K, T4J);
        }
      }
      {
        E T2T, T31, T5t, T5B, T2W, T32, T2Z, T33, T30, T34, T5m, T5y,
         T5p, T5z, T5u;
        E T5C;
        {
          E T2R, T2S, T5r, T5s;
          T2R = FMA(KP951056516, T2s, T2r);
          T2S = FMA(KP951056516, T2v, T2u);
          T2T = SUB(T2R, T2S);
          T31 = ADD(T2R, T2S);
          T5r = FNMS(KP951056516, T52, T51);
          T5s = FNMS(KP951056516, T55, T54);
          T5t = SUB(T5r, T5s);
          T5B = ADD(T5r, T5s);
        }
        {
          E T2U, T2V, T2X, T2Y;
          T2U = FMA(KP951056516, T2z, T2y);
          T2V = FMA(KP951056516, T2C, T2B);
          T2W = SUB(T2U, T2V);
          T32 = ADD(T2U, T2V);
          T2X = FMA(KP951056516, T2G, T2F);
          T2Y = FMA(KP951056516, T2J, T2I);
          T2Z = SUB(T2X, T2Y);
          T33 = ADD(T2X, T2Y);
        }
        T30 = ADD(T2W, T2Z);
        T34 = ADD(T32, T33);
        {
          E T5k, T5l, T5n, T5o;
          T5k = FNMS(KP951056516, T4N, T4M);
          T5l = FNMS(KP951056516, T4Q, T4P);
          T5m = SUB(T5k, T5l);
          T5y = ADD(T5k, T5l);
          T5n = FNMS(KP951056516, T4U, T4T);
          T5o = FNMS(KP951056516, T4X, T4W);
          T5p = SUB(T5n, T5o);
          T5z = ADD(T5n, T5o);
        }
        T5u = ADD(T5m, T5p);
        T5C = ADD(T5y, T5z);
        ro[WS(os, 3)] = ADD(T2T, T30);
        io[WS(os, 3)] = ADD(T5t, T5u);
        ro[WS(os, 18)] = ADD(T31, T34);
        io[WS(os, 18)] = ADD(T5B, T5C);
        {
          E T5j, T5q, T5v, T5w;
          T5j = FNMS(KP500000000, T30, T2T);
          T5q = SUB(T5m, T5p);
          ro[WS(os, 23)] = FNMS(KP866025403, T5q, T5j);
          ro[WS(os, 13)] = FMA(KP866025403, T5q, T5j);
          T5v = FNMS(KP500000000, T5u, T5t);
          T5w = SUB(T2Z, T2W);
          io[WS(os, 13)] = FMA(KP866025403, T5w, T5v);
          io[WS(os, 23)] = FNMS(KP866025403, T5w, T5v);
        }
        {
          E T5x, T5A, T5D, T5E;
          T5x = FNMS(KP500000000, T34, T31);
          T5A = SUB(T5y, T5z);
          ro[WS(os, 8)] = FNMS(KP866025403, T5A, T5x);
          ro[WS(os, 28)] = FMA(KP866025403, T5A, T5x);
          T5D = FNMS(KP500000000, T5C, T5B);
          T5E = SUB(T33, T32);
          io[WS(os, 8)] = FNMS(KP866025403, T5E, T5D);
          io[WS(os, 28)] = FMA(KP866025403, T5E, T5D);
        }
      }
      {
        E T2x, T2N, T57, T5f, T2E, T2O, T2L, T2P, T2M, T2Q, T4S, T5c,
         T4Z, T5d, T58;
        E T5g;
        {
          E T2t, T2w, T53, T56;
          T2t = FNMS(KP951056516, T2s, T2r);
          T2w = FNMS(KP951056516, T2v, T2u);
          T2x = SUB(T2t, T2w);
          T2N = ADD(T2t, T2w);
          T53 = FMA(KP951056516, T52, T51);
          T56 = FMA(KP951056516, T55, T54);
          T57 = SUB(T53, T56);
          T5f = ADD(T53, T56);
        }
        {
          E T2A, T2D, T2H, T2K;
          T2A = FNMS(KP951056516, T2z, T2y);
          T2D = FNMS(KP951056516, T2C, T2B);
          T2E = SUB(T2A, T2D);
          T2O = ADD(T2A, T2D);
          T2H = FNMS(KP951056516, T2G, T2F);
          T2K = FNMS(KP951056516, T2J, T2I);
          T2L = SUB(T2H, T2K);
          T2P = ADD(T2H, T2K);
        }
        T2M = ADD(T2E, T2L);
        T2Q = ADD(T2O, T2P);
        {
          E T4O, T4R, T4V, T4Y;
          T4O = FMA(KP951056516, T4N, T4M);
          T4R = FMA(KP951056516, T4Q, T4P);
          T4S = SUB(T4O, T4R);
          T5c = ADD(T4O, T4R);
          T4V = FMA(KP951056516, T4U, T4T);
          T4Y = FMA(KP951056516, T4X, T4W);
          T4Z = SUB(T4V, T4Y);
          T5d = ADD(T4V, T4Y);
        }
        T58 = ADD(T4S, T4Z);
        T5g = ADD(T5c, T5d);
        ro[WS(os, 27)] = ADD(T2x, T2M);
        io[WS(os, 27)] = ADD(T57, T58);
        ro[WS(os, 12)] = ADD(T2N, T2Q);
        io[WS(os, 12)] = ADD(T5f, T5g);
        {
          E T4L, T50, T59, T5a;
          T4L = FNMS(KP500000000, T2M, T2x);
          T50 = SUB(T4S, T4Z);
          ro[WS(os, 17)] = FNMS(KP866025403, T50, T4L);
          ro[WS(os, 7)] = FMA(KP866025403, T50, T4L);
          T59 = FNMS(KP500000000, T58, T57);
          T5a = SUB(T2L, T2E);
          io[WS(os, 7)] = FMA(KP866025403, T5a, T59);
          io[WS(os, 17)] = FNMS(KP866025403, T5a, T59);
        }
        {
          E T5b, T5e, T5h, T5i;
          T5b = FNMS(KP500000000, T2Q, T2N);
          T5e = SUB(T5c, T5d);
          ro[WS(os, 2)] = FNMS(KP866025403, T5e, T5b);
          ro[WS(os, 22)] = FMA(KP866025403, T5e, T5b);
          T5h = FNMS(KP500000000, T5g, T5f);
          T5i = SUB(T2P, T2O);
          io[WS(os, 2)] = FNMS(KP866025403, T5i, T5h);
          io[WS(os, 22)] = FMA(KP866025403, T5i, T5h);
        }
      }
      {
        E T2f, T2n, T4d, T4l, T2i, T2o, T2l, T2p, T2m, T2q, T3s, T4i,
         T3P, T4j, T4e;
        E T4m;
        {
          E T2d, T2e, T41, T4c;
          T2d = FMA(KP951056516, T1a, T13);
          T2e = FMA(KP951056516, T1l, T1e);
          T2f = SUB(T2d, T2e);
          T2n = ADD(T2d, T2e);
          T41 = FNMS(KP951056516, T40, T3X);
          T4c = FNMS(KP951056516, T4b, T48);
          T4d = SUB(T41, T4c);
          T4l = ADD(T41, T4c);
        }
        {
          E T2g, T2h, T2j, T2k;
          T2g = FMA(KP951056516, T1x, T1q);
          T2h = FMA(KP951056516, T1I, T1B);
          T2i = SUB(T2g, T2h);
          T2o = ADD(T2g, T2h);
          T2j = FMA(KP951056516, T1U, T1N);
          T2k = FMA(KP951056516, T25, T1Y);
          T2l = SUB(T2j, T2k);
          T2p = ADD(T2j, T2k);
        }
        T2m = ADD(T2i, T2l);
        T2q = ADD(T2o, T2p);
        {
          E T3g, T3r, T3D, T3O;
          T3g = FNMS(KP951056516, T3f, T3c);
          T3r = FNMS(KP951056516, T3q, T3n);
          T3s = SUB(T3g, T3r);
          T4i = ADD(T3g, T3r);
          T3D = FNMS(KP951056516, T3C, T3z);
          T3O = FNMS(KP951056516, T3N, T3K);
          T3P = SUB(T3D, T3O);
          T4j = ADD(T3D, T3O);
        }
        T4e = ADD(T3s, T3P);
        T4m = ADD(T4i, T4j);
        ro[WS(os, 21)] = ADD(T2f, T2m);
        io[WS(os, 21)] = ADD(T4d, T4e);
        ro[WS(os, 6)] = ADD(T2n, T2q);
        io[WS(os, 6)] = ADD(T4l, T4m);
        {
          E T35, T3Q, T4f, T4g;
          T35 = FNMS(KP500000000, T2m, T2f);
          T3Q = SUB(T3s, T3P);
          ro[WS(os, 11)] = FNMS(KP866025403, T3Q, T35);
          ro[WS(os, 1)] = FMA(KP866025403, T3Q, T35);
          T4f = FNMS(KP500000000, T4e, T4d);
          T4g = SUB(T2l, T2i);
          io[WS(os, 1)] = FMA(KP866025403, T4g, T4f);
          io[WS(os, 11)] = FNMS(KP866025403, T4g, T4f);
        }
        {
          E T4h, T4k, T4n, T4o;
          T4h = FNMS(KP500000000, T2q, T2n);
          T4k = SUB(T4i, T4j);
          ro[WS(os, 26)] = FNMS(KP866025403, T4k, T4h);
          ro[WS(os, 16)] = FMA(KP866025403, T4k, T4h);
          T4n = FNMS(KP500000000, T4m, T4l);
          T4o = SUB(T2p, T2o);
          io[WS(os, 16)] = FMA(KP866025403, T4o, T4n);
          io[WS(os, 26)] = FNMS(KP866025403, T4o, T4n);
        }
      }
    }
  }
}
