/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_notw.native -n 16 -standalone -fma -generic-arith -compact -name dft_codelet_c2c_16 */

/*
 * This function contains 144 FP additions, 40 FP multiplications,
 * (or, 104 additions, 0 multiplications, 40 fused multiply/add),
 * 50 stack variables, 3 constants, and 64 memory accesses
 */
void dft_codelet_c2c_16(const R * ri, const R * ii, R * ro, R * io, stride is, stride os, INT v, INT ivs, INT ovs)
{
  DK(KP923879532, +0.923879532511286756128183189396788286822416626);
  DK(KP414213562, +0.414213562373095048801688724209698078569671875);
  DK(KP707106781, +0.707106781186547524400844362104849039284835938);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, ri = ri + ivs, ii = ii + ivs, ro = ro + ovs, io = io + ovs, MAKE_VOLATILE_STRIDE(64, is), MAKE_VOLATILE_STRIDE(64, os)) {
      E T7, T1R, T25, TC, TN, T1x, T1H, T1l, Tt, T22, T2h, T1b, T1g,
       T1E, T1Z;
      E T1D, Te, T1S, T26, TJ, TQ, T1m, T1n, TT, Tm, T1X, T2g, T10,
       T15, T1B;
      E T1U, T1A;
      {
        E T3, TL, Ty, T1k, T6, T1j, TB, TM;
        {
          E T1, T2, Tw, Tx;
          T1 = ri[0];
          T2 = ri[WS(is, 8)];
          T3 = ADD(T1, T2);
          TL = SUB(T1, T2);
          Tw = ii[0];
          Tx = ii[WS(is, 8)];
          Ty = ADD(Tw, Tx);
          T1k = SUB(Tw, Tx);
        }
        {
          E T4, T5, Tz, TA;
          T4 = ri[WS(is, 4)];
          T5 = ri[WS(is, 12)];
          T6 = ADD(T4, T5);
          T1j = SUB(T4, T5);
          Tz = ii[WS(is, 4)];
          TA = ii[WS(is, 12)];
          TB = ADD(Tz, TA);
          TM = SUB(Tz, TA);
        }
        T7 = ADD(T3, T6);
        T1R = SUB(T3, T6);
        T25 = SUB(Ty, TB);
        TC = ADD(Ty, TB);
        TN = SUB(TL, TM);
        T1x = ADD(TL, TM);
        T1H = SUB(T1k, T1j);
        T1l = ADD(T1j, T1k);
      }
      {
        E Tp, T1c, T1a, T20, Ts, T17, T1f, T21;
        {
          E Tn, To, T18, T19;
          Tn = ri[WS(is, 15)];
          To = ri[WS(is, 7)];
          Tp = ADD(Tn, To);
          T1c = SUB(Tn, To);
          T18 = ii[WS(is, 15)];
          T19 = ii[WS(is, 7)];
          T1a = SUB(T18, T19);
          T20 = ADD(T18, T19);
        }
        {
          E Tq, Tr, T1d, T1e;
          Tq = ri[WS(is, 3)];
          Tr = ri[WS(is, 11)];
          Ts = ADD(Tq, Tr);
          T17 = SUB(Tq, Tr);
          T1d = ii[WS(is, 3)];
          T1e = ii[WS(is, 11)];
          T1f = SUB(T1d, T1e);
          T21 = ADD(T1d, T1e);
        }
        Tt = ADD(Tp, Ts);
        T22 = SUB(T20, T21);
        T2h = ADD(T20, T21);
        T1b = ADD(T17, T1a);
        T1g = SUB(T1c, T1f);
        T1E = SUB(T1a, T17);
        T1Z = SUB(Tp, Ts);
        T1D = ADD(T1c, T1f);
      }
      {
        E Ta, TP, TF, TO, Td, TR, TI, TS;
        {
          E T8, T9, TD, TE;
          T8 = ri[WS(is, 2)];
          T9 = ri[WS(is, 10)];
          Ta = ADD(T8, T9);
          TP = SUB(T8, T9);
          TD = ii[WS(is, 2)];
          TE = ii[WS(is, 10)];
          TF = ADD(TD, TE);
          TO = SUB(TD, TE);
        }
        {
          E Tb, Tc, TG, TH;
          Tb = ri[WS(is, 14)];
          Tc = ri[WS(is, 6)];
          Td = ADD(Tb, Tc);
          TR = SUB(Tb, Tc);
          TG = ii[WS(is, 14)];
          TH = ii[WS(is, 6)];
          TI = ADD(TG, TH);
          TS = SUB(TG, TH);
        }
        Te = ADD(Ta, Td);
        T1S = SUB(TF, TI);
        T26 = SUB(Td, Ta);
        TJ = ADD(TF, TI);
        TQ = SUB(TO, TP);
        T1m = SUB(TR, TS);
        T1n = ADD(TP, TO);
        TT = ADD(TR, TS);
      }
      {
        E Ti, T11, TZ, T1V, Tl, TW, T14, T1W;
        {
          E Tg, Th, TX, TY;
          Tg = ri[WS(is, 1)];
          Th = ri[WS(is, 9)];
          Ti = ADD(Tg, Th);
          T11 = SUB(Tg, Th);
          TX = ii[WS(is, 1)];
          TY = ii[WS(is, 9)];
          TZ = SUB(TX, TY);
          T1V = ADD(TX, TY);
        }
        {
          E Tj, Tk, T12, T13;
          Tj = ri[WS(is, 5)];
          Tk = ri[WS(is, 13)];
          Tl = ADD(Tj, Tk);
          TW = SUB(Tj, Tk);
          T12 = ii[WS(is, 5)];
          T13 = ii[WS(is, 13)];
          T14 = SUB(T12, T13);
          T1W = ADD(T12, T13);
        }
        Tm = ADD(Ti, Tl);
        T1X = SUB(T1V, T1W);
        T2g = ADD(T1V, T1W);
        T10 = ADD(TW, TZ);
        T15 = SUB(T11, T14);
        T1B = SUB(TZ, TW);
        T1U = SUB(Ti, Tl);
        T1A = ADD(T11, T14);
      }
      {
        E Tf, Tu, T2j, T2k;
        Tf = ADD(T7, Te);
        Tu = ADD(Tm, Tt);
        ro[WS(os, 8)] = SUB(Tf, Tu);
        ro[0] = ADD(Tf, Tu);
        T2j = ADD(TC, TJ);
        T2k = ADD(T2g, T2h);
        io[WS(os, 8)] = SUB(T2j, T2k);
        io[0] = ADD(T2j, T2k);
      }
      {
        E Tv, TK, T2f, T2i;
        Tv = SUB(Tt, Tm);
        TK = SUB(TC, TJ);
        io[WS(os, 4)] = ADD(Tv, TK);
        io[WS(os, 12)] = SUB(TK, Tv);
        T2f = SUB(T7, Te);
        T2i = SUB(T2g, T2h);
        ro[WS(os, 12)] = SUB(T2f, T2i);
        ro[WS(os, 4)] = ADD(T2f, T2i);
      }
      {
        E T1T, T27, T24, T28, T1Y, T23;
        T1T = ADD(T1R, T1S);
        T27 = SUB(T25, T26);
        T1Y = ADD(T1U, T1X);
        T23 = SUB(T1Z, T22);
        T24 = ADD(T1Y, T23);
        T28 = SUB(T23, T1Y);
        ro[WS(os, 10)] = FNMS(KP707106781, T24, T1T);
        io[WS(os, 6)] = FMA(KP707106781, T28, T27);
        ro[WS(os, 2)] = FMA(KP707106781, T24, T1T);
        io[WS(os, 14)] = FNMS(KP707106781, T28, T27);
      }
      {
        E T29, T2d, T2c, T2e, T2a, T2b;
        T29 = SUB(T1R, T1S);
        T2d = ADD(T26, T25);
        T2a = SUB(T1X, T1U);
        T2b = ADD(T1Z, T22);
        T2c = SUB(T2a, T2b);
        T2e = ADD(T2a, T2b);
        ro[WS(os, 14)] = FNMS(KP707106781, T2c, T29);
        io[WS(os, 2)] = FMA(KP707106781, T2e, T2d);
        ro[WS(os, 6)] = FMA(KP707106781, T2c, T29);
        io[WS(os, 10)] = FNMS(KP707106781, T2e, T2d);
      }
      {
        E TV, T1v, T1p, T1r, T1i, T1q, T1u, T1w, TU, T1o;
        TU = SUB(TQ, TT);
        TV = FMA(KP707106781, TU, TN);
        T1v = FNMS(KP707106781, TU, TN);
        T1o = SUB(T1m, T1n);
        T1p = FNMS(KP707106781, T1o, T1l);
        T1r = FMA(KP707106781, T1o, T1l);
        {
          E T16, T1h, T1s, T1t;
          T16 = FMA(KP414213562, T15, T10);
          T1h = FNMS(KP414213562, T1g, T1b);
          T1i = SUB(T16, T1h);
          T1q = ADD(T16, T1h);
          T1s = FMA(KP414213562, T1b, T1g);
          T1t = FNMS(KP414213562, T10, T15);
          T1u = SUB(T1s, T1t);
          T1w = ADD(T1t, T1s);
        }
        ro[WS(os, 11)] = FNMS(KP923879532, T1i, TV);
        io[WS(os, 11)] = FNMS(KP923879532, T1u, T1r);
        ro[WS(os, 3)] = FMA(KP923879532, T1i, TV);
        io[WS(os, 3)] = FMA(KP923879532, T1u, T1r);
        io[WS(os, 7)] = FNMS(KP923879532, T1q, T1p);
        ro[WS(os, 7)] = FNMS(KP923879532, T1w, T1v);
        io[WS(os, 15)] = FMA(KP923879532, T1q, T1p);
        ro[WS(os, 15)] = FMA(KP923879532, T1w, T1v);
      }
      {
        E T1z, T1L, T1J, T1P, T1G, T1K, T1O, T1Q, T1y, T1I;
        T1y = ADD(T1n, T1m);
        T1z = FMA(KP707106781, T1y, T1x);
        T1L = FNMS(KP707106781, T1y, T1x);
        T1I = ADD(TQ, TT);
        T1J = FNMS(KP707106781, T1I, T1H);
        T1P = FMA(KP707106781, T1I, T1H);
        {
          E T1C, T1F, T1M, T1N;
          T1C = FMA(KP414213562, T1B, T1A);
          T1F = FNMS(KP414213562, T1E, T1D);
          T1G = ADD(T1C, T1F);
          T1K = SUB(T1F, T1C);
          T1M = FNMS(KP414213562, T1A, T1B);
          T1N = FMA(KP414213562, T1D, T1E);
          T1O = SUB(T1M, T1N);
          T1Q = ADD(T1M, T1N);
        }
        ro[WS(os, 9)] = FNMS(KP923879532, T1G, T1z);
        io[WS(os, 9)] = FNMS(KP923879532, T1Q, T1P);
        ro[WS(os, 1)] = FMA(KP923879532, T1G, T1z);
        io[WS(os, 1)] = FMA(KP923879532, T1Q, T1P);
        io[WS(os, 13)] = FNMS(KP923879532, T1K, T1J);
        ro[WS(os, 13)] = FNMS(KP923879532, T1O, T1L);
        io[WS(os, 5)] = FMA(KP923879532, T1K, T1J);
        ro[WS(os, 5)] = FMA(KP923879532, T1O, T1L);
      }
    }
  }
}
