/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cf.native -n 8 -standalone -fma -generic-arith -compact -name dft_codelet_r2cf_8 */

/*
 * This function contains 20 FP additions, 4 FP multiplications,
 * (or, 16 additions, 0 multiplications, 4 fused multiply/add),
 * 14 stack variables, 1 constants, and 16 memory accesses
 */
void dft_codelet_r2cf_8(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs)
{
  DK(KP707106781, +0.707106781186547524400844362104849039284835938);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, R0 = R0 + ivs, R1 = R1 + ivs, Cr = Cr + ovs, Ci = Ci + ovs, MAKE_VOLATILE_STRIDE(32, rs), MAKE_VOLATILE_STRIDE(32, csr), MAKE_VOLATILE_STRIDE(32, csi)) {
      E T3, T7, Td, Tj, T6, Tf, Ta, Ti;
      {
        E T1, T2, Tb, Tc;
        T1 = R0[0];
        T2 = R0[WS(rs, 2)];
        T3 = ADD(T1, T2);
        T7 = SUB(T1, T2);
        Tb = R1[WS(rs, 3)];
        Tc = R1[WS(rs, 1)];
        Td = SUB(Tb, Tc);
        Tj = ADD(Tb, Tc);
      }
      {
        E T4, T5, T8, T9;
        T4 = R0[WS(rs, 1)];
        T5 = R0[WS(rs, 3)];
        T6 = ADD(T4, T5);
        Tf = SUB(T4, T5);
        T8 = R1[0];
        T9 = R1[WS(rs, 2)];
        Ta = SUB(T8, T9);
        Ti = ADD(T8, T9);
      }
      Cr[WS(csr, 2)] = SUB(T3, T6);
      Ci[WS(csi, 2)] = SUB(Tj, Ti);
      {
        E Te, Tg, Th, Tk;
        Te = ADD(Ta, Td);
        Cr[WS(csr, 3)] = FNMS(KP707106781, Te, T7);
        Cr[WS(csr, 1)] = FMA(KP707106781, Te, T7);
        Tg = SUB(Td, Ta);
        Ci[WS(csi, 1)] = NEG(FNMS(KP707106781, Tg, Tf));
        Ci[WS(csi, 3)] = FMA(KP707106781, Tg, Tf);
        Th = ADD(T3, T6);
        Tk = ADD(Ti, Tj);
        Cr[WS(csr, 4)] = SUB(Th, Tk);
        Cr[0] = ADD(Th, Tk);
      }
    }
  }
}
