/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 48 -standalone -fma -generic-arith -compact -name dft_codelet_r2cb_48 */

/*
 * This function contains 266 FP additions, 120 FP multiplications,
 * (or, 146 additions, 0 multiplications, 120 fused multiply/add),
 * 78 stack variables, 7 constants, and 96 memory accesses
 */
void dft_codelet_r2cb_48(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs)
{
  DK(KP923879532, +0.923879532511286756128183189396788286822416626);
  DK(KP707106781, +0.707106781186547524400844362104849039284835938);
  DK(KP1_847759065, +1.847759065022573512256366378793576573644833252);
  DK(KP414213562, +0.414213562373095048801688724209698078569671875);
  DK(KP1_414213562, +1.414213562373095048801688724209698078569671875);
  DK(KP1_732050807, +1.732050807568877293527446341505872366942805254);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, R0 = R0 + ovs, R1 = R1 + ovs, Cr = Cr + ivs, Ci = Ci + ivs, MAKE_VOLATILE_STRIDE(192, rs), MAKE_VOLATILE_STRIDE(192, csr), MAKE_VOLATILE_STRIDE(192, csi)) {
      E Tc, T3E, TY, T1C, T1U, T2Y, T7, T3D, TT, T2X, T1B, T1P, T14,
       T1E, T19;
      E T1F, T26, T32, T21, T31, T3G, T3H, T3I, Ti, Tn, T3J, T1g, T1I,
       T1l, T1J;
      E T2w, T37, T2r, T36, T3U, T4a, TA, T3M, T1r, T1L, T1w, T1M, T2k,
       T3d, T2f;
      E T3c, T3P, T4b, TL, T3R;
      {
        E T8, T1R, Tb, T1T, TX, T1Q, TU, T1S;
        T8 = Cr[WS(csr, 12)];
        T1R = Ci[WS(csi, 12)];
        {
          E T9, Ta, TV, TW;
          T9 = Cr[WS(csr, 20)];
          Ta = Cr[WS(csr, 4)];
          Tb = ADD(T9, Ta);
          T1T = SUB(Ta, T9);
          TV = Ci[WS(csi, 4)];
          TW = Ci[WS(csi, 20)];
          TX = SUB(TV, TW);
          T1Q = ADD(TW, TV);
        }
        Tc = ADD(T8, Tb);
        T3E = SUB(T1R, T1Q);
        TU = FNMS(KP2_000000000, T8, Tb);
        TY = FMA(KP1_732050807, TX, TU);
        T1C = FNMS(KP1_732050807, TX, TU);
        T1S = FMA(KP2_000000000, T1R, T1Q);
        T1U = FMA(KP1_732050807, T1T, T1S);
        T2Y = FNMS(KP1_732050807, T1T, T1S);
      }
      {
        E TO, T3, TN, TR, T6, TQ;
        {
          E T1, T2, T4, T5;
          TO = Ci[WS(csi, 16)];
          T1 = Cr[0];
          T2 = Cr[WS(csr, 16)];
          T3 = FMA(KP2_000000000, T2, T1);
          TN = SUB(T1, T2);
          TR = Ci[WS(csi, 8)];
          T4 = Cr[WS(csr, 24)];
          T5 = Cr[WS(csr, 8)];
          T6 = FMA(KP2_000000000, T5, T4);
          TQ = SUB(T4, T5);
        }
        T7 = ADD(T3, T6);
        T3D = SUB(T3, T6);
        {
          E TP, TS, T1z, T1A;
          TP = FNMS(KP1_732050807, TO, TN);
          TS = FMA(KP1_732050807, TR, TQ);
          TT = ADD(TP, TS);
          T2X = SUB(TP, TS);
          T1z = FMA(KP1_732050807, TO, TN);
          T1A = FNMS(KP1_732050807, TR, TQ);
          T1B = ADD(T1z, T1A);
          T1P = SUB(T1z, T1A);
        }
      }
      {
        E Te, T1Y, Tj, T23, Th, T20, T13, T1X, Tm, T25, T18, T22;
        Te = Cr[WS(csr, 6)];
        T1Y = Ci[WS(csi, 6)];
        Tj = Cr[WS(csr, 18)];
        T23 = Ci[WS(csi, 18)];
        {
          E Tf, Tg, T11, T12;
          Tf = Cr[WS(csr, 22)];
          Tg = Cr[WS(csr, 10)];
          Th = ADD(Tf, Tg);
          T20 = SUB(Tg, Tf);
          T11 = Ci[WS(csi, 22)];
          T12 = Ci[WS(csi, 10)];
          T13 = ADD(T11, T12);
          T1X = SUB(T12, T11);
        }
        {
          E Tk, Tl, T16, T17;
          Tk = Cr[WS(csr, 2)];
          Tl = Cr[WS(csr, 14)];
          Tm = ADD(Tk, Tl);
          T25 = SUB(Tl, Tk);
          T16 = Ci[WS(csi, 2)];
          T17 = Ci[WS(csi, 14)];
          T18 = ADD(T16, T17);
          T22 = SUB(T16, T17);
        }
        {
          E T10, T15, T24, T1Z;
          T10 = FNMS(KP2_000000000, Te, Th);
          T14 = FMA(KP1_732050807, T13, T10);
          T1E = FNMS(KP1_732050807, T13, T10);
          T15 = FNMS(KP2_000000000, Tj, Tm);
          T19 = FNMS(KP1_732050807, T18, T15);
          T1F = FMA(KP1_732050807, T18, T15);
          T24 = FNMS(KP2_000000000, T23, T22);
          T26 = FMA(KP1_732050807, T25, T24);
          T32 = FNMS(KP1_732050807, T25, T24);
          T1Z = FMA(KP2_000000000, T1Y, T1X);
          T21 = FMA(KP1_732050807, T20, T1Z);
          T31 = FNMS(KP1_732050807, T20, T1Z);
          T3G = SUB(T1Y, T1X);
          T3H = ADD(T22, T23);
          T3I = ADD(T3G, T3H);
          Ti = ADD(Te, Th);
          Tn = ADD(Tj, Tm);
          T3J = SUB(Ti, Tn);
        }
      }
      {
        E Tq, T2o, Tv, T2t, Tt, T2q, T1f, T2n, Ty, T2v, T1k, T2s;
        Tq = Cr[WS(csr, 3)];
        T2o = Ci[WS(csi, 3)];
        Tv = Cr[WS(csr, 21)];
        T2t = Ci[WS(csi, 21)];
        {
          E Tr, Ts, T1d, T1e;
          Tr = Cr[WS(csr, 19)];
          Ts = Cr[WS(csr, 13)];
          Tt = ADD(Tr, Ts);
          T2q = SUB(Ts, Tr);
          T1d = Ci[WS(csi, 19)];
          T1e = Ci[WS(csi, 13)];
          T1f = ADD(T1d, T1e);
          T2n = SUB(T1e, T1d);
        }
        {
          E Tw, Tx, T1i, T1j;
          Tw = Cr[WS(csr, 5)];
          Tx = Cr[WS(csr, 11)];
          Ty = ADD(Tw, Tx);
          T2v = SUB(Tx, Tw);
          T1i = Ci[WS(csi, 5)];
          T1j = Ci[WS(csi, 11)];
          T1k = ADD(T1i, T1j);
          T2s = SUB(T1i, T1j);
        }
        {
          E T1c, T1h, T2u, T2p;
          T1c = FNMS(KP2_000000000, Tq, Tt);
          T1g = FMA(KP1_732050807, T1f, T1c);
          T1I = FNMS(KP1_732050807, T1f, T1c);
          T1h = FNMS(KP2_000000000, Tv, Ty);
          T1l = FNMS(KP1_732050807, T1k, T1h);
          T1J = FMA(KP1_732050807, T1k, T1h);
          T2u = FNMS(KP2_000000000, T2t, T2s);
          T2w = FMA(KP1_732050807, T2v, T2u);
          T37 = FNMS(KP1_732050807, T2v, T2u);
          T2p = FMA(KP2_000000000, T2o, T2n);
          T2r = FMA(KP1_732050807, T2q, T2p);
          T36 = FNMS(KP1_732050807, T2q, T2p);
          {
            E T3S, T3T, Tu, Tz;
            T3S = SUB(T2o, T2n);
            T3T = ADD(T2s, T2t);
            T3U = ADD(T3S, T3T);
            T4a = SUB(T3S, T3T);
            Tu = ADD(Tq, Tt);
            Tz = ADD(Tv, Ty);
            TA = ADD(Tu, Tz);
            T3M = SUB(Tu, Tz);
          }
        }
      }
      {
        E TB, T2c, TG, T2h, TE, T2e, T1q, T2b, TJ, T2j, T1v, T2g;
        TB = Cr[WS(csr, 15)];
        T2c = Ci[WS(csi, 15)];
        TG = Cr[WS(csr, 9)];
        T2h = Ci[WS(csi, 9)];
        {
          E TC, TD, T1o, T1p;
          TC = Cr[WS(csr, 17)];
          TD = Cr[WS(csr, 1)];
          TE = ADD(TC, TD);
          T2e = SUB(TD, TC);
          T1o = Ci[WS(csi, 1)];
          T1p = Ci[WS(csi, 17)];
          T1q = SUB(T1o, T1p);
          T2b = ADD(T1p, T1o);
        }
        {
          E TH, TI, T1t, T1u;
          TH = Cr[WS(csr, 7)];
          TI = Cr[WS(csr, 23)];
          TJ = ADD(TH, TI);
          T2j = SUB(TI, TH);
          T1t = Ci[WS(csi, 7)];
          T1u = Ci[WS(csi, 23)];
          T1v = SUB(T1t, T1u);
          T2g = ADD(T1t, T1u);
        }
        {
          E T1n, T1s, T2i, T2d;
          T1n = FNMS(KP2_000000000, TB, TE);
          T1r = FMA(KP1_732050807, T1q, T1n);
          T1L = FNMS(KP1_732050807, T1q, T1n);
          T1s = FNMS(KP2_000000000, TG, TJ);
          T1w = FMA(KP1_732050807, T1v, T1s);
          T1M = FNMS(KP1_732050807, T1v, T1s);
          T2i = FMA(KP2_000000000, T2h, T2g);
          T2k = FNMS(KP1_732050807, T2j, T2i);
          T3d = FMA(KP1_732050807, T2j, T2i);
          T2d = FMA(KP2_000000000, T2c, T2b);
          T2f = FMA(KP1_732050807, T2e, T2d);
          T3c = FNMS(KP1_732050807, T2e, T2d);
          {
            E T3N, T3O, TF, TK;
            T3N = SUB(T2c, T2b);
            T3O = SUB(T2g, T2h);
            T3P = SUB(T3N, T3O);
            T4b = ADD(T3N, T3O);
            TF = ADD(TB, TE);
            TK = ADD(TG, TJ);
            TL = ADD(TF, TK);
            T3R = SUB(TF, TK);
          }
        }
      }
      {
        E TM, T4i, Tp, T4h, Td, To;
        TM = ADD(TA, TL);
        T4i = ADD(T4b, T4a);
        Td = FMA(KP2_000000000, Tc, T7);
        To = ADD(Ti, Tn);
        Tp = FMA(KP2_000000000, To, Td);
        T4h = FNMS(KP2_000000000, To, Td);
        R0[WS(rs, 12)] = FNMS(KP2_000000000, TM, Tp);
        R0[WS(rs, 18)] = FMA(KP2_000000000, T4i, T4h);
        R0[0] = FMA(KP2_000000000, TM, Tp);
        R0[WS(rs, 6)] = FNMS(KP2_000000000, T4i, T4h);
      }
      {
        E T41, T45, T44, T46;
        {
          E T3Z, T40, T42, T43;
          T3Z = FMA(KP2_000000000, T3E, T3D);
          T40 = ADD(T3J, T3I);
          T41 = FMA(KP1_414213562, T40, T3Z);
          T45 = FNMS(KP1_414213562, T40, T3Z);
          T42 = ADD(T3M, T3P);
          T43 = SUB(T3U, T3R);
          T44 = FMA(KP414213562, T43, T42);
          T46 = FNMS(KP414213562, T42, T43);
        }
        R1[WS(rs, 4)] = FNMS(KP1_847759065, T44, T41);
        R1[WS(rs, 10)] = FMA(KP1_847759065, T46, T45);
        R1[WS(rs, 16)] = FMA(KP1_847759065, T44, T41);
        R1[WS(rs, 22)] = FNMS(KP1_847759065, T46, T45);
      }
      {
        E T49, T4f, T4e, T4g;
        {
          E T47, T48, T4c, T4d;
          T47 = FNMS(KP2_000000000, Tc, T7);
          T48 = SUB(T3G, T3H);
          T49 = FNMS(KP2_000000000, T48, T47);
          T4f = FMA(KP2_000000000, T48, T47);
          T4c = SUB(T4a, T4b);
          T4d = SUB(TA, TL);
          T4e = SUB(T4c, T4d);
          T4g = ADD(T4d, T4c);
        }
        R0[WS(rs, 15)] = FNMS(KP1_414213562, T4e, T49);
        R0[WS(rs, 9)] = FMA(KP1_414213562, T4g, T4f);
        R0[WS(rs, 3)] = FMA(KP1_414213562, T4e, T49);
        R0[WS(rs, 21)] = FNMS(KP1_414213562, T4g, T4f);
      }
      {
        E T3L, T3X, T3W, T3Y;
        {
          E T3F, T3K, T3Q, T3V;
          T3F = FNMS(KP2_000000000, T3E, T3D);
          T3K = SUB(T3I, T3J);
          T3L = FNMS(KP1_414213562, T3K, T3F);
          T3X = FMA(KP1_414213562, T3K, T3F);
          T3Q = SUB(T3M, T3P);
          T3V = ADD(T3R, T3U);
          T3W = FNMS(KP414213562, T3V, T3Q);
          T3Y = FMA(KP414213562, T3Q, T3V);
        }
        R1[WS(rs, 19)] = FNMS(KP1_847759065, T3W, T3L);
        R1[WS(rs, 1)] = FMA(KP1_847759065, T3Y, T3X);
        R1[WS(rs, 7)] = FMA(KP1_847759065, T3W, T3L);
        R1[WS(rs, 13)] = FNMS(KP1_847759065, T3Y, T3X);
      }
      {
        E T1b, T3B, T3x, T3C, T1y, T3u, T3t, T3z, T3A, T3y;
        {
          E TZ, T1a, T3v, T3w;
          TZ = SUB(TT, TY);
          T1a = ADD(T14, T19);
          T1b = SUB(TZ, T1a);
          T3B = ADD(TZ, T1a);
          T3v = ADD(T36, T37);
          T3w = SUB(T3c, T3d);
          T3x = SUB(T3v, T3w);
          T3C = ADD(T3w, T3v);
        }
        {
          E T1m, T1x, T3r, T3s;
          T1m = ADD(T1g, T1l);
          T1x = ADD(T1r, T1w);
          T1y = ADD(T1m, T1x);
          T3u = SUB(T1x, T1m);
          T3r = ADD(TT, TY);
          T3s = ADD(T31, T32);
          T3t = SUB(T3r, T3s);
          T3z = ADD(T3r, T3s);
        }
        R0[WS(rs, 4)] = ADD(T1b, T1y);
        R0[WS(rs, 16)] = SUB(T1b, T1y);
        R0[WS(rs, 10)] = ADD(T3B, T3C);
        R0[WS(rs, 22)] = SUB(T3B, T3C);
        T3A = ADD(T3u, T3x);
        R0[WS(rs, 13)] = FNMS(KP707106781, T3A, T3z);
        R0[WS(rs, 1)] = FMA(KP707106781, T3A, T3z);
        T3y = SUB(T3u, T3x);
        R0[WS(rs, 19)] = FNMS(KP707106781, T3y, T3t);
        R0[WS(rs, 7)] = FMA(KP707106781, T3y, T3t);
      }
      {
        E T1H, T2L, T2R, T2V, T1O, T2S, T2O, T2T, T2W, T2U;
        {
          E T1D, T1G, T2P, T2Q;
          T1D = SUB(T1B, T1C);
          T1G = ADD(T1E, T1F);
          T1H = SUB(T1D, T1G);
          T2L = ADD(T1D, T1G);
          T2P = ADD(T1B, T1C);
          T2Q = ADD(T21, T26);
          T2R = ADD(T2P, T2Q);
          T2V = SUB(T2P, T2Q);
        }
        {
          E T1K, T1N, T2M, T2N;
          T1K = ADD(T1I, T1J);
          T1N = ADD(T1L, T1M);
          T1O = ADD(T1K, T1N);
          T2S = SUB(T1N, T1K);
          T2M = SUB(T2f, T2k);
          T2N = ADD(T2r, T2w);
          T2O = ADD(T2M, T2N);
          T2T = SUB(T2N, T2M);
        }
        R0[WS(rs, 20)] = ADD(T1H, T1O);
        R0[WS(rs, 8)] = SUB(T1H, T1O);
        R0[WS(rs, 2)] = ADD(T2L, T2O);
        R0[WS(rs, 14)] = SUB(T2L, T2O);
        T2W = SUB(T2T, T2S);
        R0[WS(rs, 23)] = FNMS(KP707106781, T2W, T2V);
        R0[WS(rs, 11)] = FMA(KP707106781, T2W, T2V);
        T2U = ADD(T2S, T2T);
        R0[WS(rs, 5)] = FNMS(KP707106781, T2U, T2R);
        R0[WS(rs, 17)] = FMA(KP707106781, T2U, T2R);
      }
      {
        E T1V, T2D, T28, T2E, T2m, T2G, T2z, T2H, T1W, T27;
        T1V = ADD(T1P, T1U);
        T2D = SUB(T1P, T1U);
        T1W = SUB(T1F, T1E);
        T27 = SUB(T21, T26);
        T28 = ADD(T1W, T27);
        T2E = SUB(T1W, T27);
        {
          E T2a, T2l, T2x, T2y;
          T2a = SUB(T1J, T1I);
          T2l = ADD(T2f, T2k);
          T2m = ADD(T2a, T2l);
          T2G = SUB(T2a, T2l);
          T2x = SUB(T2r, T2w);
          T2y = SUB(T1M, T1L);
          T2z = SUB(T2x, T2y);
          T2H = ADD(T2y, T2x);
        }
        {
          E T29, T2A, T2J, T2K;
          T29 = FMA(KP707106781, T28, T1V);
          T2A = FMA(KP414213562, T2z, T2m);
          R1[WS(rs, 12)] = FNMS(KP923879532, T2A, T29);
          R1[0] = FMA(KP923879532, T2A, T29);
          T2J = FNMS(KP707106781, T2E, T2D);
          T2K = FMA(KP414213562, T2G, T2H);
          R1[WS(rs, 21)] = FNMS(KP923879532, T2K, T2J);
          R1[WS(rs, 9)] = FMA(KP923879532, T2K, T2J);
        }
        {
          E T2B, T2C, T2F, T2I;
          T2B = FNMS(KP707106781, T28, T1V);
          T2C = FNMS(KP414213562, T2m, T2z);
          R1[WS(rs, 6)] = FNMS(KP923879532, T2C, T2B);
          R1[WS(rs, 18)] = FMA(KP923879532, T2C, T2B);
          T2F = FMA(KP707106781, T2E, T2D);
          T2I = FNMS(KP414213562, T2H, T2G);
          R1[WS(rs, 3)] = FNMS(KP923879532, T2I, T2F);
          R1[WS(rs, 15)] = FMA(KP923879532, T2I, T2F);
        }
      }
      {
        E T2Z, T3j, T34, T3k, T3a, T3n, T3f, T3m, T30, T33;
        T2Z = ADD(T2X, T2Y);
        T3j = SUB(T2X, T2Y);
        T30 = SUB(T19, T14);
        T33 = SUB(T31, T32);
        T34 = ADD(T30, T33);
        T3k = SUB(T33, T30);
        {
          E T38, T39, T3b, T3e;
          T38 = SUB(T36, T37);
          T39 = SUB(T1w, T1r);
          T3a = SUB(T38, T39);
          T3n = ADD(T39, T38);
          T3b = SUB(T1l, T1g);
          T3e = ADD(T3c, T3d);
          T3f = ADD(T3b, T3e);
          T3m = SUB(T3b, T3e);
        }
        {
          E T35, T3g, T3p, T3q;
          T35 = FNMS(KP707106781, T34, T2Z);
          T3g = FNMS(KP414213562, T3f, T3a);
          R1[WS(rs, 14)] = FNMS(KP923879532, T3g, T35);
          R1[WS(rs, 2)] = FMA(KP923879532, T3g, T35);
          T3p = FMA(KP707106781, T3k, T3j);
          T3q = FMA(KP414213562, T3m, T3n);
          R1[WS(rs, 5)] = FNMS(KP923879532, T3q, T3p);
          R1[WS(rs, 17)] = FMA(KP923879532, T3q, T3p);
        }
        {
          E T3h, T3i, T3l, T3o;
          T3h = FMA(KP707106781, T34, T2Z);
          T3i = FMA(KP414213562, T3a, T3f);
          R1[WS(rs, 20)] = FNMS(KP923879532, T3i, T3h);
          R1[WS(rs, 8)] = FMA(KP923879532, T3i, T3h);
          T3l = FNMS(KP707106781, T3k, T3j);
          T3o = FNMS(KP414213562, T3n, T3m);
          R1[WS(rs, 11)] = FNMS(KP923879532, T3o, T3l);
          R1[WS(rs, 23)] = FMA(KP923879532, T3o, T3l);
        }
      }
    }
  }
}
