/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_notw.native -n 15 -standalone -fma -generic-arith -compact -name dft_codelet_c2c_15 */

/*
 * This function contains 156 FP additions, 84 FP multiplications,
 * (or, 72 additions, 0 multiplications, 84 fused multiply/add),
 * 69 stack variables, 6 constants, and 60 memory accesses
 */
void dft_codelet_c2c_15(const R * ri, const R * ii, R * ro, R * io, stride is, stride os, INT v, INT ivs, INT ovs)
{
  DK(KP951056516, +0.951056516295153572116439333379382143405698634);
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  DK(KP866025403, +0.866025403784438646763723170752936183471402627);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, ri = ri + ivs, ii = ii + ivs, ro = ro + ovs, io = io + ovs, MAKE_VOLATILE_STRIDE(60, is), MAKE_VOLATILE_STRIDE(60, os)) {
      E T5, T2l, Tx, TV, T1z, T1X, Tl, Tq, Tr, TN, TS, TT, T2c, T2d,
       T2n;
      E T1O, T1P, T1Z, T1l, T1q, T1B, TZ, T10, T11, Ta, Tf, Tg, TC,
       TH, TI;
      E T2f, T2g, T2m, T1R, T1S, T1Y, T1a, T1f, T1A, TW, TX, TY;
      {
        E T1, T1v, T4, T1y, Tw, T1w, Tt, T1x;
        T1 = ri[0];
        T1v = ii[0];
        {
          E T2, T3, Tu, Tv;
          T2 = ri[WS(is, 5)];
          T3 = ri[WS(is, 10)];
          T4 = ADD(T2, T3);
          T1y = SUB(T3, T2);
          Tu = ii[WS(is, 5)];
          Tv = ii[WS(is, 10)];
          Tw = SUB(Tu, Tv);
          T1w = ADD(Tu, Tv);
        }
        T5 = ADD(T1, T4);
        T2l = ADD(T1v, T1w);
        Tt = FNMS(KP500000000, T4, T1);
        Tx = FNMS(KP866025403, Tw, Tt);
        TV = FMA(KP866025403, Tw, Tt);
        T1x = FNMS(KP500000000, T1w, T1v);
        T1z = FMA(KP866025403, T1y, T1x);
        T1X = FNMS(KP866025403, T1y, T1x);
      }
      {
        E Th, Tk, TJ, T1k, T1h, T1i, TM, T1j, Tm, Tp, TO, T1p, T1m,
         T1n, TR;
        E T1o;
        {
          E Ti, Tj, TK, TL;
          Th = ri[WS(is, 6)];
          Ti = ri[WS(is, 11)];
          Tj = ri[WS(is, 1)];
          Tk = ADD(Ti, Tj);
          TJ = FNMS(KP500000000, Tk, Th);
          T1k = SUB(Tj, Ti);
          T1h = ii[WS(is, 6)];
          TK = ii[WS(is, 11)];
          TL = ii[WS(is, 1)];
          T1i = ADD(TK, TL);
          TM = SUB(TK, TL);
          T1j = FNMS(KP500000000, T1i, T1h);
        }
        {
          E Tn, To, TP, TQ;
          Tm = ri[WS(is, 9)];
          Tn = ri[WS(is, 14)];
          To = ri[WS(is, 4)];
          Tp = ADD(Tn, To);
          TO = FNMS(KP500000000, Tp, Tm);
          T1p = SUB(To, Tn);
          T1m = ii[WS(is, 9)];
          TP = ii[WS(is, 14)];
          TQ = ii[WS(is, 4)];
          T1n = ADD(TP, TQ);
          TR = SUB(TP, TQ);
          T1o = FNMS(KP500000000, T1n, T1m);
        }
        Tl = ADD(Th, Tk);
        Tq = ADD(Tm, Tp);
        Tr = ADD(Tl, Tq);
        TN = FNMS(KP866025403, TM, TJ);
        TS = FNMS(KP866025403, TR, TO);
        TT = ADD(TN, TS);
        T2c = ADD(T1h, T1i);
        T2d = ADD(T1m, T1n);
        T2n = ADD(T2c, T2d);
        T1O = FNMS(KP866025403, T1k, T1j);
        T1P = FNMS(KP866025403, T1p, T1o);
        T1Z = ADD(T1O, T1P);
        T1l = FMA(KP866025403, T1k, T1j);
        T1q = FMA(KP866025403, T1p, T1o);
        T1B = ADD(T1l, T1q);
        TZ = FMA(KP866025403, TM, TJ);
        T10 = FMA(KP866025403, TR, TO);
        T11 = ADD(TZ, T10);
      }
      {
        E T6, T9, Ty, T19, T16, T17, TB, T18, Tb, Te, TD, T1e, T1b,
         T1c, TG;
        E T1d;
        {
          E T7, T8, Tz, TA;
          T6 = ri[WS(is, 3)];
          T7 = ri[WS(is, 8)];
          T8 = ri[WS(is, 13)];
          T9 = ADD(T7, T8);
          Ty = FNMS(KP500000000, T9, T6);
          T19 = SUB(T8, T7);
          T16 = ii[WS(is, 3)];
          Tz = ii[WS(is, 8)];
          TA = ii[WS(is, 13)];
          T17 = ADD(Tz, TA);
          TB = SUB(Tz, TA);
          T18 = FNMS(KP500000000, T17, T16);
        }
        {
          E Tc, Td, TE, TF;
          Tb = ri[WS(is, 12)];
          Tc = ri[WS(is, 2)];
          Td = ri[WS(is, 7)];
          Te = ADD(Tc, Td);
          TD = FNMS(KP500000000, Te, Tb);
          T1e = SUB(Td, Tc);
          T1b = ii[WS(is, 12)];
          TE = ii[WS(is, 2)];
          TF = ii[WS(is, 7)];
          T1c = ADD(TE, TF);
          TG = SUB(TE, TF);
          T1d = FNMS(KP500000000, T1c, T1b);
        }
        Ta = ADD(T6, T9);
        Tf = ADD(Tb, Te);
        Tg = ADD(Ta, Tf);
        TC = FNMS(KP866025403, TB, Ty);
        TH = FNMS(KP866025403, TG, TD);
        TI = ADD(TC, TH);
        T2f = ADD(T16, T17);
        T2g = ADD(T1b, T1c);
        T2m = ADD(T2f, T2g);
        T1R = FNMS(KP866025403, T19, T18);
        T1S = FNMS(KP866025403, T1e, T1d);
        T1Y = ADD(T1R, T1S);
        T1a = FMA(KP866025403, T19, T18);
        T1f = FMA(KP866025403, T1e, T1d);
        T1A = ADD(T1a, T1f);
        TW = FMA(KP866025403, TB, Ty);
        TX = FMA(KP866025403, TG, TD);
        TY = ADD(TW, TX);
      }
      {
        E T2a, Ts, T29, T2i, T2k, T2e, T2h, T2j, T2b;
        T2a = SUB(Tg, Tr);
        Ts = ADD(Tg, Tr);
        T29 = FNMS(KP250000000, Ts, T5);
        T2e = SUB(T2c, T2d);
        T2h = SUB(T2f, T2g);
        T2i = FNMS(KP618033988, T2h, T2e);
        T2k = FMA(KP618033988, T2e, T2h);
        ro[0] = ADD(T5, Ts);
        T2j = FMA(KP559016994, T2a, T29);
        ro[WS(os, 9)] = FNMS(KP951056516, T2k, T2j);
        ro[WS(os, 6)] = FMA(KP951056516, T2k, T2j);
        T2b = FNMS(KP559016994, T2a, T29);
        ro[WS(os, 12)] = FNMS(KP951056516, T2i, T2b);
        ro[WS(os, 3)] = FMA(KP951056516, T2i, T2b);
      }
      {
        E T2q, T2o, T2p, T2u, T2w, T2s, T2t, T2v, T2r;
        T2q = SUB(T2m, T2n);
        T2o = ADD(T2m, T2n);
        T2p = FNMS(KP250000000, T2o, T2l);
        T2s = SUB(Tl, Tq);
        T2t = SUB(Ta, Tf);
        T2u = FNMS(KP618033988, T2t, T2s);
        T2w = FMA(KP618033988, T2s, T2t);
        io[0] = ADD(T2l, T2o);
        T2v = FMA(KP559016994, T2q, T2p);
        io[WS(os, 6)] = FNMS(KP951056516, T2w, T2v);
        io[WS(os, 9)] = FMA(KP951056516, T2w, T2v);
        T2r = FNMS(KP559016994, T2q, T2p);
        io[WS(os, 3)] = FNMS(KP951056516, T2u, T2r);
        io[WS(os, 12)] = FMA(KP951056516, T2u, T2r);
      }
      {
        E T1M, TU, T1L, T1U, T1W, T1Q, T1T, T1V, T1N;
        T1M = SUB(TI, TT);
        TU = ADD(TI, TT);
        T1L = FNMS(KP250000000, TU, Tx);
        T1Q = SUB(T1O, T1P);
        T1T = SUB(T1R, T1S);
        T1U = FNMS(KP618033988, T1T, T1Q);
        T1W = FMA(KP618033988, T1Q, T1T);
        ro[WS(os, 5)] = ADD(Tx, TU);
        T1V = FMA(KP559016994, T1M, T1L);
        ro[WS(os, 14)] = FNMS(KP951056516, T1W, T1V);
        ro[WS(os, 11)] = FMA(KP951056516, T1W, T1V);
        T1N = FNMS(KP559016994, T1M, T1L);
        ro[WS(os, 2)] = FNMS(KP951056516, T1U, T1N);
        ro[WS(os, 8)] = FMA(KP951056516, T1U, T1N);
      }
      {
        E T22, T20, T21, T26, T28, T24, T25, T27, T23;
        T22 = SUB(T1Y, T1Z);
        T20 = ADD(T1Y, T1Z);
        T21 = FNMS(KP250000000, T20, T1X);
        T24 = SUB(TN, TS);
        T25 = SUB(TC, TH);
        T26 = FNMS(KP618033988, T25, T24);
        T28 = FMA(KP618033988, T24, T25);
        io[WS(os, 5)] = ADD(T1X, T20);
        T27 = FMA(KP559016994, T22, T21);
        io[WS(os, 11)] = FNMS(KP951056516, T28, T27);
        io[WS(os, 14)] = FMA(KP951056516, T28, T27);
        T23 = FNMS(KP559016994, T22, T21);
        io[WS(os, 2)] = FMA(KP951056516, T26, T23);
        io[WS(os, 8)] = FNMS(KP951056516, T26, T23);
      }
      {
        E T1E, T1C, T1D, T1I, T1K, T1G, T1H, T1J, T1F;
        T1E = SUB(T1A, T1B);
        T1C = ADD(T1A, T1B);
        T1D = FNMS(KP250000000, T1C, T1z);
        T1G = SUB(TW, TX);
        T1H = SUB(TZ, T10);
        T1I = FMA(KP618033988, T1H, T1G);
        T1K = FNMS(KP618033988, T1G, T1H);
        io[WS(os, 10)] = ADD(T1z, T1C);
        T1J = FNMS(KP559016994, T1E, T1D);
        io[WS(os, 7)] = FMA(KP951056516, T1K, T1J);
        io[WS(os, 13)] = FNMS(KP951056516, T1K, T1J);
        T1F = FMA(KP559016994, T1E, T1D);
        io[WS(os, 1)] = FNMS(KP951056516, T1I, T1F);
        io[WS(os, 4)] = FMA(KP951056516, T1I, T1F);
      }
      {
        E T14, T12, T13, T1s, T1u, T1g, T1r, T1t, T15;
        T14 = SUB(TY, T11);
        T12 = ADD(TY, T11);
        T13 = FNMS(KP250000000, T12, TV);
        T1g = SUB(T1a, T1f);
        T1r = SUB(T1l, T1q);
        T1s = FMA(KP618033988, T1r, T1g);
        T1u = FNMS(KP618033988, T1g, T1r);
        ro[WS(os, 10)] = ADD(TV, T12);
        T1t = FNMS(KP559016994, T14, T13);
        ro[WS(os, 7)] = FNMS(KP951056516, T1u, T1t);
        ro[WS(os, 13)] = FMA(KP951056516, T1u, T1t);
        T15 = FMA(KP559016994, T14, T13);
        ro[WS(os, 4)] = FNMS(KP951056516, T1s, T15);
        ro[WS(os, 1)] = FMA(KP951056516, T1s, T15);
      }
    }
  }
}
