/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cf.native -n 28 -standalone -fma -generic-arith -compact -name dft_codelet_r2cf_28 */

/*
 * This function contains 150 FP additions, 78 FP multiplications,
 * (or, 78 additions, 6 multiplications, 72 fused multiply/add),
 * 83 stack variables, 6 constants, and 56 memory accesses
 */
void dft_codelet_r2cf_28(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs)
{
  DK(KP974927912, +0.974927912181823607018131682993931217232785801);
  DK(KP801937735, +0.801937735804838252472204639014890102331838324);
  DK(KP554958132, +0.554958132087371191422194871006410481067288862);
  DK(KP900968867, +0.900968867902419126236102319507445051165919162);
  DK(KP692021471, +0.692021471630095869627814897002069140197260599);
  DK(KP356895867, +0.356895867892209443894399510021300583399127187);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, R0 = R0 + ivs, R1 = R1 + ivs, Cr = Cr + ovs, Ci = Ci + ovs, MAKE_VOLATILE_STRIDE(112, rs), MAKE_VOLATILE_STRIDE(112, csr), MAKE_VOLATILE_STRIDE(112, csi)) {
      E T3, T1n, T11, T1o, Ty, T1a, T18, TM, T19, TF, T1s, T1v, T1w,
       T23, T24;
      E T2c, T1z, T1C, T1D, T1X, T1Y, T2b, T1G, T1J, T1K, T20, T21,
       T2a, T12, T14;
      E T13, T15, T1i, T1d, Ta, To, Th, Tp, TU, TP;
      {
        E T1, T2, TZ, T10;
        T1 = R0[0];
        T2 = R0[WS(rs, 7)];
        T3 = SUB(T1, T2);
        T1n = ADD(T1, T2);
        TZ = R1[WS(rs, 3)];
        T10 = R1[WS(rs, 10)];
        T11 = SUB(TZ, T10);
        T1o = ADD(TZ, T10);
        {
          E T6, T1q, TL, T1F, TE, T1r, Td, T1x, TI, T1I, T9, T1t, Tg,
           T1A, TB;
          E T1u, Tu, T1B, Tn, T1H, Tx, T1y, Tk, T1E;
          {
            E T4, T5, Tb, Tc;
            T4 = R0[WS(rs, 2)];
            T5 = R0[WS(rs, 9)];
            T6 = SUB(T4, T5);
            T1q = ADD(T4, T5);
            {
              E TJ, TK, TC, TD;
              TJ = R1[WS(rs, 9)];
              TK = R1[WS(rs, 2)];
              TL = SUB(TJ, TK);
              T1F = ADD(TJ, TK);
              TC = R1[WS(rs, 5)];
              TD = R1[WS(rs, 12)];
              TE = SUB(TC, TD);
              T1r = ADD(TC, TD);
            }
            Tb = R0[WS(rs, 4)];
            Tc = R0[WS(rs, 11)];
            Td = SUB(Tb, Tc);
            T1x = ADD(Tb, Tc);
            {
              E TG, TH, T7, T8;
              TG = R1[WS(rs, 11)];
              TH = R1[WS(rs, 4)];
              TI = SUB(TG, TH);
              T1I = ADD(TG, TH);
              T7 = R0[WS(rs, 12)];
              T8 = R0[WS(rs, 5)];
              T9 = SUB(T7, T8);
              T1t = ADD(T7, T8);
            }
          }
          {
            E Te, Tf, Tl, Tm;
            Te = R0[WS(rs, 10)];
            Tf = R0[WS(rs, 3)];
            Tg = SUB(Te, Tf);
            T1A = ADD(Te, Tf);
            {
              E Tz, TA, Ts, Tt;
              Tz = R1[WS(rs, 1)];
              TA = R1[WS(rs, 8)];
              TB = SUB(Tz, TA);
              T1u = ADD(Tz, TA);
              Ts = R1[WS(rs, 13)];
              Tt = R1[WS(rs, 6)];
              Tu = SUB(Ts, Tt);
              T1B = ADD(Ts, Tt);
            }
            Tl = R0[WS(rs, 8)];
            Tm = R0[WS(rs, 1)];
            Tn = SUB(Tl, Tm);
            T1H = ADD(Tl, Tm);
            {
              E Tv, Tw, Ti, Tj;
              Tv = R1[WS(rs, 7)];
              Tw = R1[0];
              Tx = SUB(Tv, Tw);
              T1y = ADD(Tv, Tw);
              Ti = R0[WS(rs, 6)];
              Tj = R0[WS(rs, 13)];
              Tk = SUB(Ti, Tj);
              T1E = ADD(Ti, Tj);
            }
          }
          Ty = SUB(Tu, Tx);
          T1a = SUB(T9, T6);
          T18 = SUB(Tn, Tk);
          TM = SUB(TI, TL);
          T19 = SUB(Tg, Td);
          TF = SUB(TB, TE);
          T1s = SUB(T1q, T1r);
          T1v = SUB(T1t, T1u);
          T1w = ADD(T1s, T1v);
          T23 = ADD(T1E, T1F);
          T24 = ADD(T1H, T1I);
          T2c = ADD(T23, T24);
          T1z = SUB(T1x, T1y);
          T1C = SUB(T1A, T1B);
          T1D = ADD(T1z, T1C);
          T1X = ADD(T1A, T1B);
          T1Y = ADD(T1x, T1y);
          T2b = ADD(T1Y, T1X);
          T1G = SUB(T1E, T1F);
          T1J = SUB(T1H, T1I);
          T1K = ADD(T1G, T1J);
          T20 = ADD(T1q, T1r);
          T21 = ADD(T1t, T1u);
          T2a = ADD(T20, T21);
          T12 = ADD(TE, TB);
          T14 = ADD(TL, TI);
          T13 = ADD(Tx, Tu);
          T15 = FNMS(KP356895867, T14, T13);
          T1i = FNMS(KP356895867, T13, T12);
          T1d = FNMS(KP356895867, T12, T14);
          Ta = ADD(T6, T9);
          To = ADD(Tk, Tn);
          Th = ADD(Td, Tg);
          Tp = FNMS(KP356895867, Th, Ta);
          TU = FNMS(KP356895867, To, Th);
          TP = FNMS(KP356895867, Ta, To);
        }
      }
      Cr[WS(csr, 7)] = ADD(T3, ADD(Ta, ADD(Th, To)));
      Ci[WS(csi, 7)] = ADD(T11, ADD(T12, ADD(T13, T14)));
      {
        E Tr, TO, Tq, TN;
        Tq = FNMS(KP692021471, Tp, To);
        Tr = FNMS(KP900968867, Tq, T3);
        TN = FMA(KP554958132, TM, TF);
        TO = FMA(KP801937735, TN, Ty);
        Cr[WS(csr, 13)] = FNMS(KP974927912, TO, Tr);
        Cr[WS(csr, 1)] = FMA(KP974927912, TO, Tr);
      }
      {
        E T1k, T1m, T1j, T1l;
        T1j = FNMS(KP692021471, T1i, T14);
        T1k = FNMS(KP900968867, T1j, T11);
        T1l = FMA(KP554958132, T18, T1a);
        T1m = FMA(KP801937735, T1l, T19);
        Ci[WS(csi, 1)] = NEG(FNMS(KP974927912, T1m, T1k));
        Ci[WS(csi, 13)] = NEG(FMA(KP974927912, T1m, T1k));
      }
      {
        E T1f, T1h, T1e, T1g;
        T1e = FNMS(KP692021471, T1d, T13);
        T1f = FNMS(KP900968867, T1e, T11);
        T1g = FMA(KP554958132, T19, T18);
        T1h = FNMS(KP801937735, T1g, T1a);
        Ci[WS(csi, 5)] = NEG(FMA(KP974927912, T1h, T1f));
        Ci[WS(csi, 9)] = NEG(FNMS(KP974927912, T1h, T1f));
      }
      {
        E TR, TT, TQ, TS;
        TQ = FNMS(KP692021471, TP, Th);
        TR = FNMS(KP900968867, TQ, T3);
        TS = FMA(KP554958132, Ty, TM);
        TT = FNMS(KP801937735, TS, TF);
        Cr[WS(csr, 5)] = FNMS(KP974927912, TT, TR);
        Cr[WS(csr, 9)] = FMA(KP974927912, TT, TR);
      }
      {
        E TW, TY, TV, TX;
        TV = FNMS(KP692021471, TU, Ta);
        TW = FNMS(KP900968867, TV, T3);
        TX = FNMS(KP554958132, TF, Ty);
        TY = FNMS(KP801937735, TX, TM);
        Cr[WS(csr, 3)] = FNMS(KP974927912, TY, TW);
        Cr[WS(csr, 11)] = FMA(KP974927912, TY, TW);
      }
      {
        E T17, T1c, T16, T1b;
        T16 = FNMS(KP692021471, T15, T12);
        T17 = FNMS(KP900968867, T16, T11);
        T1b = FNMS(KP554958132, T1a, T19);
        T1c = FNMS(KP801937735, T1b, T18);
        Ci[WS(csi, 3)] = FMA(KP974927912, T1c, T17);
        Ci[WS(csi, 11)] = FNMS(KP974927912, T1c, T17);
      }
      {
        E T1R, T1T, T1S, T1U, T1W, T1V;
        T1R = SUB(T1v, T1s);
        T1T = SUB(T1z, T1C);
        T1S = SUB(T1J, T1G);
        T1U = FNMS(KP554958132, T1T, T1S);
        T1W = FMA(KP554958132, T1R, T1T);
        T1V = FMA(KP554958132, T1S, T1R);
        Ci[WS(csi, 2)] = MUL(KP974927912, FNMS(KP801937735, T1U, T1R));
        Ci[WS(csi, 10)] = MUL(KP974927912, FMA(KP801937735, T1W, T1S));
        Ci[WS(csi, 6)] = MUL(KP974927912, FNMS(KP801937735, T1V, T1T));
      }
      {
        E T1Z, T25, T22, T26, T28, T27;
        T1Z = SUB(T1X, T1Y);
        T25 = SUB(T23, T24);
        T22 = SUB(T20, T21);
        T26 = FMA(KP554958132, T25, T22);
        T28 = FMA(KP554958132, T22, T1Z);
        T27 = FNMS(KP554958132, T1Z, T25);
        Ci[WS(csi, 8)] = MUL(KP974927912, FNMS(KP801937735, T26, T1Z));
        Ci[WS(csi, 4)] = MUL(KP974927912, FMA(KP801937735, T28, T25));
        Ci[WS(csi, 12)] = MUL(KP974927912, FNMS(KP801937735, T27, T22));
      }
      {
        E T29, T2i, T2e, T2g, T2h, T2d, T2f;
        T29 = ADD(T1n, T1o);
        T2h = FNMS(KP356895867, T2b, T2a);
        T2i = FNMS(KP692021471, T2h, T2c);
        T2d = FNMS(KP356895867, T2c, T2b);
        T2e = FNMS(KP692021471, T2d, T2a);
        T2f = FNMS(KP356895867, T2a, T2c);
        T2g = FNMS(KP692021471, T2f, T2b);
        Cr[WS(csr, 4)] = FNMS(KP900968867, T2e, T29);
        Cr[WS(csr, 8)] = FNMS(KP900968867, T2i, T29);
        Cr[WS(csr, 12)] = FNMS(KP900968867, T2g, T29);
        Cr[0] = ADD(T29, ADD(T2a, ADD(T2b, T2c)));
      }
      {
        E T1p, T1Q, T1M, T1O, T1P, T1L, T1N;
        T1p = SUB(T1n, T1o);
        T1P = FNMS(KP356895867, T1D, T1w);
        T1Q = FNMS(KP692021471, T1P, T1K);
        T1L = FNMS(KP356895867, T1K, T1D);
        T1M = FNMS(KP692021471, T1L, T1w);
        T1N = FNMS(KP356895867, T1w, T1K);
        T1O = FNMS(KP692021471, T1N, T1D);
        Cr[WS(csr, 10)] = FNMS(KP900968867, T1M, T1p);
        Cr[WS(csr, 6)] = FNMS(KP900968867, T1Q, T1p);
        Cr[WS(csr, 2)] = FNMS(KP900968867, T1O, T1p);
        Cr[WS(csr, 14)] = ADD(T1p, ADD(T1w, ADD(T1D, T1K)));
      }
    }
  }
}
