/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 60 -standalone -fma -generic-arith -compact -name dft_codelet_r2cb_60 */

/*
 * This function contains 374 FP additions, 190 FP multiplications,
 * (or, 184 additions, 0 multiplications, 190 fused multiply/add),
 * 92 stack variables, 9 constants, and 120 memory accesses
 */
void dft_codelet_r2cb_60(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs)
{
  DK(KP951056516, +0.951056516295153572116439333379382143405698634);
  DK(KP1_732050807, +1.732050807568877293527446341505872366942805254);
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  DK(KP1_902113032, +1.902113032590307144232878666758764286811397268);
  DK(KP1_118033988, +1.118033988749894848204586834365638117720309180);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, R0 = R0 + ovs, R1 = R1 + ovs, Cr = Cr + ivs, Ci = Ci + ivs, MAKE_VOLATILE_STRIDE(240, rs), MAKE_VOLATILE_STRIDE(240, csr), MAKE_VOLATILE_STRIDE(240, csi)) {
      E T5, T2p, T2N, T15, T2b, T27, T5G, T2J, T3s, T4P, T1L, T5E, T2D,
       T36, T52;
      E TW, T4Q, T3v, T20, T2I, TN, T4T, T3k, T1P, T2F, T1W, T5F, T2G,
       T3h, T4S;
      E TE, T53, T39, T1E, T2C, T1y, T5N, T2y, T3T, T4J, Tk, T2w, T2Q,
       T1o, T2e;
      E Tt, T4K, T3W, T1r, T2x, Te, T4F, T3J, T18, T2q, T1f, T5K, T2r,
       T3G, T4E;
      {
        E T14, T2o, T1, T4, TZ, T10, T2n, T11;
        {
          E T12, T13, T2, T3;
          T12 = Ci[WS(csi, 12)];
          T13 = Ci[WS(csi, 24)];
          T14 = FMA(KP618033988, T13, T12);
          T2o = FNMS(KP618033988, T12, T13);
          T1 = Cr[0];
          T2 = Cr[WS(csr, 12)];
          T3 = Cr[WS(csr, 24)];
          T4 = ADD(T2, T3);
          TZ = FNMS(KP500000000, T4, T1);
          T10 = SUB(T2, T3);
        }
        T5 = FMA(KP2_000000000, T4, T1);
        T2n = FNMS(KP1_118033988, T10, TZ);
        T2p = FMA(KP1_902113032, T2o, T2n);
        T2N = FNMS(KP1_902113032, T2o, T2n);
        T11 = FMA(KP1_118033988, T10, TZ);
        T15 = FMA(KP1_902113032, T14, T11);
        T2b = FNMS(KP1_902113032, T14, T11);
      }
      {
        E T3m, T3n, T3o, T23, T3p, T26, T3q, T3r;
        T3m = Ci[WS(csi, 5)];
        {
          E T21, T22, T24, T25;
          T21 = Ci[WS(csi, 7)];
          T22 = Ci[WS(csi, 17)];
          T3n = SUB(T22, T21);
          T24 = Ci[WS(csi, 19)];
          T25 = Ci[WS(csi, 29)];
          T3o = SUB(T25, T24);
          T23 = ADD(T21, T22);
          T3p = ADD(T3n, T3o);
          T26 = ADD(T24, T25);
        }
        T27 = FMA(KP618033988, T26, T23);
        T5G = ADD(T3p, T3m);
        T2J = FNMS(KP618033988, T23, T26);
        T3q = FNMS(KP250000000, T3p, T3m);
        T3r = SUB(T3o, T3n);
        T3s = FNMS(KP559016994, T3r, T3q);
        T4P = FMA(KP559016994, T3r, T3q);
      }
      {
        E T30, T31, T32, T1H, T33, T1K, T34, T35;
        T30 = Ci[WS(csi, 15)];
        {
          E T1F, T1G, T1I, T1J;
          T1F = Ci[WS(csi, 27)];
          T1G = Ci[WS(csi, 3)];
          T31 = ADD(T1F, T1G);
          T1I = Ci[WS(csi, 9)];
          T1J = Ci[WS(csi, 21)];
          T32 = ADD(T1J, T1I);
          T1H = SUB(T1F, T1G);
          T33 = SUB(T31, T32);
          T1K = SUB(T1I, T1J);
        }
        T1L = FMA(KP618033988, T1K, T1H);
        T5E = ADD(T30, T33);
        T2D = FNMS(KP618033988, T1H, T1K);
        T34 = FNMS(KP250000000, T33, T30);
        T35 = ADD(T31, T32);
        T36 = FMA(KP559016994, T35, T34);
        T52 = FNMS(KP559016994, T35, T34);
      }
      {
        E TO, TR, TU, TV, T3u, T3t, T1Y, T1Z;
        TO = Cr[WS(csr, 5)];
        {
          E TP, TQ, TS, TT;
          TP = Cr[WS(csr, 7)];
          TQ = Cr[WS(csr, 17)];
          TR = ADD(TP, TQ);
          TS = Cr[WS(csr, 19)];
          TT = Cr[WS(csr, 29)];
          TU = ADD(TS, TT);
          TV = ADD(TR, TU);
          T3u = SUB(TS, TT);
          T3t = SUB(TP, TQ);
        }
        TW = ADD(TO, TV);
        T4Q = FNMS(KP618033988, T3t, T3u);
        T3v = FMA(KP618033988, T3u, T3t);
        T1Y = FNMS(KP250000000, TV, TO);
        T1Z = SUB(TR, TU);
        T20 = FMA(KP559016994, T1Z, T1Y);
        T2I = FNMS(KP559016994, T1Z, T1Y);
      }
      {
        E TF, TI, TL, TM, T3j, T3i, T1N, T1O;
        TF = Cr[WS(csr, 25)];
        {
          E TG, TH, TJ, TK;
          TG = Cr[WS(csr, 13)];
          TH = Cr[WS(csr, 23)];
          TI = ADD(TG, TH);
          TJ = Cr[WS(csr, 1)];
          TK = Cr[WS(csr, 11)];
          TL = ADD(TJ, TK);
          TM = ADD(TI, TL);
          T3j = SUB(TJ, TK);
          T3i = SUB(TG, TH);
        }
        TN = ADD(TF, TM);
        T4T = FNMS(KP618033988, T3i, T3j);
        T3k = FMA(KP618033988, T3j, T3i);
        T1N = FNMS(KP250000000, TM, TF);
        T1O = SUB(TI, TL);
        T1P = FMA(KP559016994, T1O, T1N);
        T2F = FNMS(KP559016994, T1O, T1N);
      }
      {
        E T3b, T3c, T3d, T1S, T3e, T1V, T3f, T3g;
        T3b = Ci[WS(csi, 25)];
        {
          E T1Q, T1R, T1T, T1U;
          T1Q = Ci[WS(csi, 23)];
          T1R = Ci[WS(csi, 13)];
          T3c = SUB(T1R, T1Q);
          T1T = Ci[WS(csi, 11)];
          T1U = Ci[WS(csi, 1)];
          T3d = SUB(T1U, T1T);
          T1S = ADD(T1Q, T1R);
          T3e = ADD(T3c, T3d);
          T1V = ADD(T1T, T1U);
        }
        T1W = FMA(KP618033988, T1V, T1S);
        T5F = ADD(T3e, T3b);
        T2G = FNMS(KP618033988, T1S, T1V);
        T3f = FNMS(KP250000000, T3e, T3b);
        T3g = SUB(T3d, T3c);
        T3h = FNMS(KP559016994, T3g, T3f);
        T4S = FMA(KP559016994, T3g, T3f);
      }
      {
        E Tw, Tz, TC, TD, T38, T37, T1C, T1D;
        Tw = Cr[WS(csr, 15)];
        {
          E Tx, Ty, TA, TB;
          Tx = Cr[WS(csr, 27)];
          Ty = Cr[WS(csr, 3)];
          Tz = ADD(Tx, Ty);
          TA = Cr[WS(csr, 21)];
          TB = Cr[WS(csr, 9)];
          TC = ADD(TA, TB);
          TD = ADD(Tz, TC);
          T38 = SUB(TA, TB);
          T37 = SUB(Tx, Ty);
        }
        TE = ADD(Tw, TD);
        T53 = FNMS(KP618033988, T37, T38);
        T39 = FMA(KP618033988, T38, T37);
        T1C = FNMS(KP250000000, TD, Tw);
        T1D = SUB(Tz, TC);
        T1E = FMA(KP559016994, T1D, T1C);
        T2C = FNMS(KP559016994, T1D, T1C);
      }
      {
        E T3N, T3O, T3P, T1u, T3Q, T1x, T3R, T3S;
        T3N = Ci[WS(csi, 10)];
        {
          E T1s, T1t, T1v, T1w;
          T1s = Ci[WS(csi, 2)];
          T1t = Ci[WS(csi, 22)];
          T3O = SUB(T1s, T1t);
          T1v = Ci[WS(csi, 14)];
          T1w = Ci[WS(csi, 26)];
          T3P = ADD(T1v, T1w);
          T1u = ADD(T1s, T1t);
          T3Q = ADD(T3O, T3P);
          T1x = SUB(T1v, T1w);
        }
        T1y = FMA(KP618033988, T1x, T1u);
        T5N = SUB(T3Q, T3N);
        T2y = FNMS(KP618033988, T1u, T1x);
        T3R = FMA(KP250000000, T3Q, T3N);
        T3S = SUB(T3O, T3P);
        T3T = FNMS(KP559016994, T3S, T3R);
        T4J = FMA(KP559016994, T3S, T3R);
      }
      {
        E T1n, T2v, Tg, Tj, T1i, T1j, T2u, T1k;
        {
          E T1l, T1m, Th, Ti;
          T1l = Ci[WS(csi, 18)];
          T1m = Ci[WS(csi, 6)];
          T1n = FMA(KP618033988, T1m, T1l);
          T2v = FMS(KP618033988, T1l, T1m);
          Tg = Cr[WS(csr, 30)];
          Th = Cr[WS(csr, 18)];
          Ti = Cr[WS(csr, 6)];
          Tj = ADD(Th, Ti);
          T1i = FNMS(KP500000000, Tj, Tg);
          T1j = SUB(Th, Ti);
        }
        Tk = FMA(KP2_000000000, Tj, Tg);
        T2u = FNMS(KP1_118033988, T1j, T1i);
        T2w = FMA(KP1_902113032, T2v, T2u);
        T2Q = FNMS(KP1_902113032, T2v, T2u);
        T1k = FMA(KP1_118033988, T1j, T1i);
        T1o = FNMS(KP1_902113032, T1n, T1k);
        T2e = FMA(KP1_902113032, T1n, T1k);
      }
      {
        E Tl, To, Tr, Ts, T3V, T3U, T1p, T1q;
        Tl = Cr[WS(csr, 10)];
        {
          E Tm, Tn, Tp, Tq;
          Tm = Cr[WS(csr, 2)];
          Tn = Cr[WS(csr, 22)];
          To = ADD(Tm, Tn);
          Tp = Cr[WS(csr, 14)];
          Tq = Cr[WS(csr, 26)];
          Tr = ADD(Tp, Tq);
          Ts = ADD(To, Tr);
          T3V = SUB(Tp, Tq);
          T3U = SUB(Tm, Tn);
        }
        Tt = ADD(Tl, Ts);
        T4K = FNMS(KP618033988, T3U, T3V);
        T3W = FMA(KP618033988, T3V, T3U);
        T1p = FNMS(KP250000000, Ts, Tl);
        T1q = SUB(To, Tr);
        T1r = FMA(KP559016994, T1q, T1p);
        T2x = FNMS(KP559016994, T1q, T1p);
      }
      {
        E T6, T9, Tc, Td, T3I, T3H, T16, T17;
        T6 = Cr[WS(csr, 20)];
        {
          E T7, T8, Ta, Tb;
          T7 = Cr[WS(csr, 28)];
          T8 = Cr[WS(csr, 8)];
          T9 = ADD(T7, T8);
          Ta = Cr[WS(csr, 16)];
          Tb = Cr[WS(csr, 4)];
          Tc = ADD(Ta, Tb);
          Td = ADD(T9, Tc);
          T3I = SUB(Ta, Tb);
          T3H = SUB(T7, T8);
        }
        Te = ADD(T6, Td);
        T4F = FNMS(KP618033988, T3H, T3I);
        T3J = FMA(KP618033988, T3I, T3H);
        T16 = FNMS(KP250000000, Td, T6);
        T17 = SUB(T9, Tc);
        T18 = FMA(KP559016994, T17, T16);
        T2q = FNMS(KP559016994, T17, T16);
      }
      {
        E T3A, T3B, T3C, T1b, T3D, T1e, T3E, T3F;
        T3A = Ci[WS(csi, 20)];
        {
          E T19, T1a, T1c, T1d;
          T19 = Ci[WS(csi, 28)];
          T1a = Ci[WS(csi, 8)];
          T3B = SUB(T1a, T19);
          T1c = Ci[WS(csi, 4)];
          T1d = Ci[WS(csi, 16)];
          T3C = ADD(T1c, T1d);
          T1b = ADD(T19, T1a);
          T3D = SUB(T3B, T3C);
          T1e = SUB(T1c, T1d);
        }
        T1f = FNMS(KP618033988, T1e, T1b);
        T5K = ADD(T3D, T3A);
        T2r = FMA(KP618033988, T1b, T1e);
        T3E = FNMS(KP250000000, T3D, T3A);
        T3F = ADD(T3B, T3C);
        T3G = FMA(KP559016994, T3F, T3E);
        T4E = FNMS(KP559016994, T3F, T3E);
      }
      {
        E T5R, T5Z, TY, T5Y, T5O, T5U, T5L, T5T, T5I, T5Q, Tv, T5D,
         TX;
        T5R = SUB(TW, TN);
        T5Z = SUB(T5G, T5F);
        TX = ADD(TN, TW);
        TY = ADD(TE, TX);
        T5Y = FNMS(KP2_000000000, TE, TX);
        {
          E T5M, T5J, T5H, Tf, Tu;
          T5M = SUB(Tk, Tt);
          T5O = FNMS(KP1_732050807, T5N, T5M);
          T5U = FMA(KP1_732050807, T5N, T5M);
          T5J = SUB(T5, Te);
          T5L = FNMS(KP1_732050807, T5K, T5J);
          T5T = FMA(KP1_732050807, T5K, T5J);
          T5H = ADD(T5F, T5G);
          T5I = SUB(T5E, T5H);
          T5Q = FMA(KP2_000000000, T5E, T5H);
          Tf = FMA(KP2_000000000, Te, T5);
          Tu = FMA(KP2_000000000, Tt, Tk);
          Tv = ADD(Tf, Tu);
          T5D = SUB(Tf, Tu);
        }
        R0[WS(rs, 15)] = FNMS(KP2_000000000, TY, Tv);
        R1[WS(rs, 7)] = FNMS(KP2_000000000, T5I, T5D);
        R1[WS(rs, 22)] = FMA(KP2_000000000, T5I, T5D);
        R0[0] = FMA(KP2_000000000, TY, Tv);
        {
          E T5P, T5S, T5X, T60;
          T5P = SUB(T5L, T5O);
          T5S = FNMS(KP1_732050807, T5R, T5Q);
          R1[WS(rs, 17)] = SUB(T5P, T5S);
          R1[WS(rs, 2)] = ADD(T5P, T5S);
          T5X = ADD(T5L, T5O);
          T60 = FMA(KP1_732050807, T5Z, T5Y);
          R0[WS(rs, 25)] = ADD(T5X, T60);
          R0[WS(rs, 10)] = SUB(T5X, T60);
        }
        {
          E T61, T62, T5V, T5W;
          T61 = ADD(T5T, T5U);
          T62 = FNMS(KP1_732050807, T5Z, T5Y);
          R0[WS(rs, 5)] = ADD(T61, T62);
          R0[WS(rs, 20)] = SUB(T61, T62);
          T5V = SUB(T5T, T5U);
          T5W = FMA(KP1_732050807, T5R, T5Q);
          R1[WS(rs, 27)] = SUB(T5V, T5W);
          R1[WS(rs, 12)] = ADD(T5V, T5W);
        }
      }
      {
        E T2P, T4X, T4H, T2S, T4Y, T4M, T2U, T2X, T4O, T59, T54, T55,
         T4V, T58;
        {
          E T4G, T2O, T4D, T4L, T2R, T4I;
          T4G = FMA(KP951056516, T4F, T4E);
          T2O = FNMS(KP951056516, T2r, T2q);
          T4D = SUB(T2N, T2O);
          T2P = FMA(KP2_000000000, T2O, T2N);
          T4X = FMA(KP1_732050807, T4G, T4D);
          T4H = FNMS(KP1_732050807, T4G, T4D);
          T4L = FNMS(KP951056516, T4K, T4J);
          T2R = FNMS(KP951056516, T2y, T2x);
          T4I = SUB(T2Q, T2R);
          T2S = FMA(KP2_000000000, T2R, T2Q);
          T4Y = FNMS(KP1_732050807, T4L, T4I);
          T4M = FMA(KP1_732050807, T4L, T4I);
        }
        {
          E T2V, T2W, T4R, T4U;
          T2U = FNMS(KP951056516, T2D, T2C);
          T2V = FMA(KP951056516, T2G, T2F);
          T2W = FNMS(KP951056516, T2J, T2I);
          T2X = ADD(T2V, T2W);
          T4O = FNMS(KP2_000000000, T2U, T2X);
          T59 = SUB(T2W, T2V);
          T54 = FMA(KP951056516, T53, T52);
          T4R = FNMS(KP951056516, T4Q, T4P);
          T4U = FNMS(KP951056516, T4T, T4S);
          T55 = ADD(T4U, T4R);
          T4V = SUB(T4R, T4U);
          T58 = FMA(KP2_000000000, T54, T55);
        }
        {
          E T2T, T2Y, T57, T5a;
          T2T = ADD(T2P, T2S);
          T2Y = ADD(T2U, T2X);
          R0[WS(rs, 21)] = FNMS(KP2_000000000, T2Y, T2T);
          R0[WS(rs, 6)] = FMA(KP2_000000000, T2Y, T2T);
          {
            E T4N, T4W, T5b, T5c;
            T4N = ADD(T4H, T4M);
            T4W = FMA(KP1_732050807, T4V, T4O);
            R0[WS(rs, 1)] = ADD(T4N, T4W);
            R0[WS(rs, 16)] = SUB(T4N, T4W);
            T5b = SUB(T4H, T4M);
            T5c = FNMS(KP1_732050807, T59, T58);
            R1[WS(rs, 23)] = SUB(T5b, T5c);
            R1[WS(rs, 8)] = ADD(T5b, T5c);
          }
          T57 = SUB(T4X, T4Y);
          T5a = FMA(KP1_732050807, T59, T58);
          R1[WS(rs, 3)] = SUB(T57, T5a);
          R1[WS(rs, 18)] = ADD(T57, T5a);
          {
            E T51, T56, T4Z, T50;
            T51 = SUB(T2P, T2S);
            T56 = SUB(T54, T55);
            R1[WS(rs, 13)] = FNMS(KP2_000000000, T56, T51);
            R1[WS(rs, 28)] = FMA(KP2_000000000, T56, T51);
            T4Z = ADD(T4X, T4Y);
            T50 = FNMS(KP1_732050807, T4V, T4O);
            R0[WS(rs, 11)] = ADD(T4Z, T50);
            R0[WS(rs, 26)] = SUB(T4Z, T50);
          }
        }
      }
      {
        E T1h, T43, T3L, T1A, T44, T3Y, T1M, T29, T41, T48, T3a, T3x,
         T40, T49;
        {
          E T3K, T1g, T3z, T3X, T1z, T3M;
          T3K = FNMS(KP951056516, T3J, T3G);
          T1g = FNMS(KP951056516, T1f, T18);
          T3z = SUB(T15, T1g);
          T1h = FMA(KP2_000000000, T1g, T15);
          T43 = FNMS(KP1_732050807, T3K, T3z);
          T3L = FMA(KP1_732050807, T3K, T3z);
          T3X = FMA(KP951056516, T3W, T3T);
          T1z = FMA(KP951056516, T1y, T1r);
          T3M = SUB(T1o, T1z);
          T1A = FMA(KP2_000000000, T1z, T1o);
          T44 = FMA(KP1_732050807, T3X, T3M);
          T3Y = FNMS(KP1_732050807, T3X, T3M);
        }
        {
          E T1X, T28, T3l, T3w;
          T1M = FMA(KP951056516, T1L, T1E);
          T1X = FNMS(KP951056516, T1W, T1P);
          T28 = FMA(KP951056516, T27, T20);
          T29 = ADD(T1X, T28);
          T41 = SUB(T28, T1X);
          T48 = FNMS(KP2_000000000, T1M, T29);
          T3a = FNMS(KP951056516, T39, T36);
          T3l = FMA(KP951056516, T3k, T3h);
          T3w = FMA(KP951056516, T3v, T3s);
          T3x = ADD(T3l, T3w);
          T40 = FMA(KP2_000000000, T3a, T3x);
          T49 = SUB(T3w, T3l);
        }
        {
          E T1B, T2a, T47, T4a;
          T1B = ADD(T1h, T1A);
          T2a = ADD(T1M, T29);
          R0[WS(rs, 3)] = FNMS(KP2_000000000, T2a, T1B);
          R0[WS(rs, 18)] = FMA(KP2_000000000, T2a, T1B);
          {
            E T2Z, T3y, T4b, T4c;
            T2Z = SUB(T1h, T1A);
            T3y = SUB(T3a, T3x);
            R1[WS(rs, 25)] = FNMS(KP2_000000000, T3y, T2Z);
            R1[WS(rs, 10)] = FMA(KP2_000000000, T3y, T2Z);
            T4b = ADD(T3L, T3Y);
            T4c = FNMS(KP1_732050807, T49, T48);
            R0[WS(rs, 23)] = ADD(T4b, T4c);
            R0[WS(rs, 8)] = SUB(T4b, T4c);
          }
          T47 = ADD(T43, T44);
          T4a = FMA(KP1_732050807, T49, T48);
          R0[WS(rs, 13)] = ADD(T47, T4a);
          R0[WS(rs, 28)] = SUB(T47, T4a);
          {
            E T45, T46, T3Z, T42;
            T45 = SUB(T43, T44);
            T46 = FNMS(KP1_732050807, T41, T40);
            R1[WS(rs, 5)] = SUB(T45, T46);
            R1[WS(rs, 20)] = ADD(T45, T46);
            T3Z = SUB(T3L, T3Y);
            T42 = FMA(KP1_732050807, T41, T40);
            R1[WS(rs, 15)] = SUB(T3Z, T42);
            R1[0] = ADD(T3Z, T42);
          }
        }
      }
      {
        E T2d, T4p, T4f, T2g, T4q, T4i, T2i, T2l, T4k, T4z, T4u, T4v,
         T4n, T4y;
        {
          E T4e, T2c, T4d, T4h, T2f, T4g;
          T4e = FMA(KP951056516, T3J, T3G);
          T2c = FMA(KP951056516, T1f, T18);
          T4d = SUB(T2b, T2c);
          T2d = FMA(KP2_000000000, T2c, T2b);
          T4p = FMA(KP1_732050807, T4e, T4d);
          T4f = FNMS(KP1_732050807, T4e, T4d);
          T4h = FNMS(KP951056516, T3W, T3T);
          T2f = FNMS(KP951056516, T1y, T1r);
          T4g = SUB(T2e, T2f);
          T2g = FMA(KP2_000000000, T2f, T2e);
          T4q = FNMS(KP1_732050807, T4h, T4g);
          T4i = FMA(KP1_732050807, T4h, T4g);
        }
        {
          E T2j, T2k, T4l, T4m;
          T2i = FNMS(KP951056516, T1L, T1E);
          T2j = FMA(KP951056516, T1W, T1P);
          T2k = FNMS(KP951056516, T27, T20);
          T2l = ADD(T2j, T2k);
          T4k = FNMS(KP2_000000000, T2i, T2l);
          T4z = SUB(T2k, T2j);
          T4u = FMA(KP951056516, T39, T36);
          T4l = FNMS(KP951056516, T3v, T3s);
          T4m = FNMS(KP951056516, T3k, T3h);
          T4v = ADD(T4m, T4l);
          T4n = SUB(T4l, T4m);
          T4y = FMA(KP2_000000000, T4u, T4v);
        }
        {
          E T2h, T2m, T4x, T4A;
          T2h = ADD(T2d, T2g);
          T2m = ADD(T2i, T2l);
          R0[WS(rs, 27)] = FNMS(KP2_000000000, T2m, T2h);
          R0[WS(rs, 12)] = FMA(KP2_000000000, T2m, T2h);
          {
            E T4j, T4o, T4B, T4C;
            T4j = ADD(T4f, T4i);
            T4o = FMA(KP1_732050807, T4n, T4k);
            R0[WS(rs, 7)] = ADD(T4j, T4o);
            R0[WS(rs, 22)] = SUB(T4j, T4o);
            T4B = SUB(T4f, T4i);
            T4C = FNMS(KP1_732050807, T4z, T4y);
            R1[WS(rs, 29)] = SUB(T4B, T4C);
            R1[WS(rs, 14)] = ADD(T4B, T4C);
          }
          T4x = SUB(T4p, T4q);
          T4A = FMA(KP1_732050807, T4z, T4y);
          R1[WS(rs, 9)] = SUB(T4x, T4A);
          R1[WS(rs, 24)] = ADD(T4x, T4A);
          {
            E T4t, T4w, T4r, T4s;
            T4t = SUB(T2d, T2g);
            T4w = SUB(T4u, T4v);
            R1[WS(rs, 19)] = FNMS(KP2_000000000, T4w, T4t);
            R1[WS(rs, 4)] = FMA(KP2_000000000, T4w, T4t);
            T4r = ADD(T4p, T4q);
            T4s = FNMS(KP1_732050807, T4n, T4k);
            R0[WS(rs, 17)] = ADD(T4r, T4s);
            R0[WS(rs, 2)] = SUB(T4r, T4s);
          }
        }
      }
      {
        E T2t, T5t, T5l, T2A, T5u, T5o, T2E, T2L, T5r, T5y, T5e, T5h,
         T5q, T5z;
        {
          E T5k, T2s, T5j, T5n, T2z, T5m;
          T5k = FNMS(KP951056516, T4F, T4E);
          T2s = FMA(KP951056516, T2r, T2q);
          T5j = SUB(T2p, T2s);
          T2t = FMA(KP2_000000000, T2s, T2p);
          T5t = FNMS(KP1_732050807, T5k, T5j);
          T5l = FMA(KP1_732050807, T5k, T5j);
          T5n = FMA(KP951056516, T4K, T4J);
          T2z = FMA(KP951056516, T2y, T2x);
          T5m = SUB(T2w, T2z);
          T2A = FMA(KP2_000000000, T2z, T2w);
          T5u = FMA(KP1_732050807, T5n, T5m);
          T5o = FNMS(KP1_732050807, T5n, T5m);
        }
        {
          E T2H, T2K, T5f, T5g;
          T2E = FMA(KP951056516, T2D, T2C);
          T2H = FNMS(KP951056516, T2G, T2F);
          T2K = FMA(KP951056516, T2J, T2I);
          T2L = ADD(T2H, T2K);
          T5r = SUB(T2K, T2H);
          T5y = FNMS(KP2_000000000, T2E, T2L);
          T5e = FNMS(KP951056516, T53, T52);
          T5f = FMA(KP951056516, T4T, T4S);
          T5g = FMA(KP951056516, T4Q, T4P);
          T5h = ADD(T5f, T5g);
          T5q = FMA(KP2_000000000, T5e, T5h);
          T5z = SUB(T5g, T5f);
        }
        {
          E T2B, T2M, T5x, T5A;
          T2B = ADD(T2t, T2A);
          T2M = ADD(T2E, T2L);
          R0[WS(rs, 9)] = FNMS(KP2_000000000, T2M, T2B);
          R0[WS(rs, 24)] = FMA(KP2_000000000, T2M, T2B);
          {
            E T5d, T5i, T5B, T5C;
            T5d = SUB(T2t, T2A);
            T5i = SUB(T5e, T5h);
            R1[WS(rs, 1)] = FNMS(KP2_000000000, T5i, T5d);
            R1[WS(rs, 16)] = FMA(KP2_000000000, T5i, T5d);
            T5B = ADD(T5l, T5o);
            T5C = FNMS(KP1_732050807, T5z, T5y);
            R0[WS(rs, 29)] = ADD(T5B, T5C);
            R0[WS(rs, 14)] = SUB(T5B, T5C);
          }
          T5x = ADD(T5t, T5u);
          T5A = FMA(KP1_732050807, T5z, T5y);
          R0[WS(rs, 19)] = ADD(T5x, T5A);
          R0[WS(rs, 4)] = SUB(T5x, T5A);
          {
            E T5v, T5w, T5p, T5s;
            T5v = SUB(T5t, T5u);
            T5w = FNMS(KP1_732050807, T5r, T5q);
            R1[WS(rs, 11)] = SUB(T5v, T5w);
            R1[WS(rs, 26)] = ADD(T5v, T5w);
            T5p = SUB(T5l, T5o);
            T5s = FMA(KP1_732050807, T5r, T5q);
            R1[WS(rs, 21)] = SUB(T5p, T5s);
            R1[WS(rs, 6)] = ADD(T5p, T5s);
          }
        }
      }
    }
  }
}
