/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_notw.native -n 48 -standalone -fma -generic-arith -compact -name dft_codelet_c2c_48 */

/*
 * This function contains 624 FP additions, 216 FP multiplications,
 * (or, 408 additions, 0 multiplications, 216 fused multiply/add),
 * 134 stack variables, 5 constants, and 192 memory accesses
 */
void dft_codelet_c2c_48(const R * ri, const R * ii, R * ro, R * io, stride is, stride os, INT v, INT ivs, INT ovs)
{
  DK(KP923879532, +0.923879532511286756128183189396788286822416626);
  DK(KP414213562, +0.414213562373095048801688724209698078569671875);
  DK(KP707106781, +0.707106781186547524400844362104849039284835938);
  DK(KP866025403, +0.866025403784438646763723170752936183471402627);
  DK(KP500000000, +0.500000000000000000000000000000000000000000000);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, ri = ri + ivs, ii = ii + ivs, ro = ro + ovs, io = io + ovs, MAKE_VOLATILE_STRIDE(192, is), MAKE_VOLATILE_STRIDE(192, os)) {
      E T2l, T4z, T2o, T4A, T3E, T46, T3B, T45, T1I, T94, Tb, T8v, T2s,
       T4C, T2v;
      E T4D, T3L, T49, T3I, T48, T1T, T8w, Tm, T93, T2A, T2D, T6Y, T3Q,
       T3T, T6Z;
      E T4G, T4H, T4W, T4c, T4d, T4V, T25, T8y, Ty, T8z, T2H, T2K, T71,
       T3X, T40;
      E T72, T4J, T4K, T4S, T4f, T4g, T4T, T2g, T8C, TJ, T8B, TW, T8L,
       T2Y, T7m;
      E T8J, T9K, T7j, T85, T5a, T6A, T4t, T5d, T1j, T8W, T3l, T7b,
       T8U, T9F, T78;
      E T8a, T5B, T6u, T4m, T5E, T1u, T8R, T3w, T79, T8Z, T9G, T7e,
       T8b, T5P, T6v;
      E T4p, T5C, T17, T8G, T39, T7k, T8O, T9L, T7p, T86, T5o, T6B,
       T4w, T5b;
      {
        E T1, T1y, T6, T1D, T4, T3A, T1B, T2k, T9, T3D, T1G, T2n;
        T1 = ri[0];
        T1y = ii[0];
        T6 = ri[WS(is, 24)];
        T1D = ii[WS(is, 24)];
        {
          E T2, T3, T1z, T1A;
          T2 = ri[WS(is, 16)];
          T3 = ri[WS(is, 32)];
          T4 = ADD(T2, T3);
          T3A = SUB(T3, T2);
          T1z = ii[WS(is, 16)];
          T1A = ii[WS(is, 32)];
          T1B = ADD(T1z, T1A);
          T2k = SUB(T1z, T1A);
        }
        {
          E T7, T8, T1E, T1F;
          T7 = ri[WS(is, 40)];
          T8 = ri[WS(is, 8)];
          T9 = ADD(T7, T8);
          T3D = SUB(T8, T7);
          T1E = ii[WS(is, 40)];
          T1F = ii[WS(is, 8)];
          T1G = ADD(T1E, T1F);
          T2n = SUB(T1E, T1F);
        }
        {
          E T2j, T2m, T3C, T3z;
          T2j = FNMS(KP500000000, T4, T1);
          T2l = FNMS(KP866025403, T2k, T2j);
          T4z = FMA(KP866025403, T2k, T2j);
          T2m = FNMS(KP500000000, T9, T6);
          T2o = FNMS(KP866025403, T2n, T2m);
          T4A = FMA(KP866025403, T2n, T2m);
          T3C = FNMS(KP500000000, T1G, T1D);
          T3E = FNMS(KP866025403, T3D, T3C);
          T46 = FMA(KP866025403, T3D, T3C);
          T3z = FNMS(KP500000000, T1B, T1y);
          T3B = FNMS(KP866025403, T3A, T3z);
          T45 = FMA(KP866025403, T3A, T3z);
          {
            E T1C, T1H, T5, Ta;
            T1C = ADD(T1y, T1B);
            T1H = ADD(T1D, T1G);
            T1I = ADD(T1C, T1H);
            T94 = SUB(T1C, T1H);
            T5 = ADD(T1, T4);
            Ta = ADD(T6, T9);
            Tb = ADD(T5, Ta);
            T8v = SUB(T5, Ta);
          }
        }
      }
      {
        E Tc, T1J, Th, T1O, Tf, T3H, T1M, T2r, Tk, T3K, T1R, T2u;
        Tc = ri[WS(is, 12)];
        T1J = ii[WS(is, 12)];
        Th = ri[WS(is, 36)];
        T1O = ii[WS(is, 36)];
        {
          E Td, Te, T1K, T1L;
          Td = ri[WS(is, 28)];
          Te = ri[WS(is, 44)];
          Tf = ADD(Td, Te);
          T3H = SUB(Te, Td);
          T1K = ii[WS(is, 28)];
          T1L = ii[WS(is, 44)];
          T1M = ADD(T1K, T1L);
          T2r = SUB(T1K, T1L);
        }
        {
          E Ti, Tj, T1P, T1Q;
          Ti = ri[WS(is, 4)];
          Tj = ri[WS(is, 20)];
          Tk = ADD(Ti, Tj);
          T3K = SUB(Tj, Ti);
          T1P = ii[WS(is, 4)];
          T1Q = ii[WS(is, 20)];
          T1R = ADD(T1P, T1Q);
          T2u = SUB(T1P, T1Q);
        }
        {
          E T2q, T2t, T3J, T3G;
          T2q = FNMS(KP500000000, Tf, Tc);
          T2s = FNMS(KP866025403, T2r, T2q);
          T4C = FMA(KP866025403, T2r, T2q);
          T2t = FNMS(KP500000000, Tk, Th);
          T2v = FNMS(KP866025403, T2u, T2t);
          T4D = FMA(KP866025403, T2u, T2t);
          T3J = FNMS(KP500000000, T1R, T1O);
          T3L = FNMS(KP866025403, T3K, T3J);
          T49 = FMA(KP866025403, T3K, T3J);
          T3G = FNMS(KP500000000, T1M, T1J);
          T3I = FNMS(KP866025403, T3H, T3G);
          T48 = FMA(KP866025403, T3H, T3G);
          {
            E T1N, T1S, Tg, Tl;
            T1N = ADD(T1J, T1M);
            T1S = ADD(T1O, T1R);
            T1T = ADD(T1N, T1S);
            T8w = SUB(T1N, T1S);
            Tg = ADD(Tc, Tf);
            Tl = ADD(Th, Tk);
            Tm = ADD(Tg, Tl);
            T93 = SUB(Tg, Tl);
          }
        }
      }
      {
        E To, Tr, T2y, T3P, T1V, T1Y, T2z, T3O, Tt, Tw, T2B, T3S, T20,
         T23, T2C;
        E T3R;
        {
          E Tp, Tq, T1W, T1X;
          To = ri[WS(is, 6)];
          Tp = ri[WS(is, 22)];
          Tq = ri[WS(is, 38)];
          Tr = ADD(Tp, Tq);
          T2y = FNMS(KP500000000, Tr, To);
          T3P = SUB(Tq, Tp);
          T1V = ii[WS(is, 6)];
          T1W = ii[WS(is, 22)];
          T1X = ii[WS(is, 38)];
          T1Y = ADD(T1W, T1X);
          T2z = SUB(T1W, T1X);
          T3O = FNMS(KP500000000, T1Y, T1V);
        }
        {
          E Tu, Tv, T21, T22;
          Tt = ri[WS(is, 30)];
          Tu = ri[WS(is, 46)];
          Tv = ri[WS(is, 14)];
          Tw = ADD(Tu, Tv);
          T2B = FNMS(KP500000000, Tw, Tt);
          T3S = SUB(Tv, Tu);
          T20 = ii[WS(is, 30)];
          T21 = ii[WS(is, 46)];
          T22 = ii[WS(is, 14)];
          T23 = ADD(T21, T22);
          T2C = SUB(T21, T22);
          T3R = FNMS(KP500000000, T23, T20);
        }
        T2A = FNMS(KP866025403, T2z, T2y);
        T2D = FNMS(KP866025403, T2C, T2B);
        T6Y = SUB(T2A, T2D);
        T3Q = FNMS(KP866025403, T3P, T3O);
        T3T = FNMS(KP866025403, T3S, T3R);
        T6Z = SUB(T3Q, T3T);
        T4G = FMA(KP866025403, T2z, T2y);
        T4H = FMA(KP866025403, T2C, T2B);
        T4W = SUB(T4G, T4H);
        T4c = FMA(KP866025403, T3P, T3O);
        T4d = FMA(KP866025403, T3S, T3R);
        T4V = SUB(T4c, T4d);
        {
          E T1Z, T24, Ts, Tx;
          T1Z = ADD(T1V, T1Y);
          T24 = ADD(T20, T23);
          T25 = ADD(T1Z, T24);
          T8y = SUB(T1Z, T24);
          Ts = ADD(To, Tr);
          Tx = ADD(Tt, Tw);
          Ty = ADD(Ts, Tx);
          T8z = SUB(Ts, Tx);
        }
      }
      {
        E Tz, TC, T2F, T3W, T26, T29, T2G, T3V, TE, TH, T2I, T3Z, T2b,
         T2e, T2J;
        E T3Y;
        {
          E TA, TB, T27, T28;
          Tz = ri[WS(is, 42)];
          TA = ri[WS(is, 10)];
          TB = ri[WS(is, 26)];
          TC = ADD(TA, TB);
          T2F = FNMS(KP500000000, TC, Tz);
          T3W = SUB(TB, TA);
          T26 = ii[WS(is, 42)];
          T27 = ii[WS(is, 10)];
          T28 = ii[WS(is, 26)];
          T29 = ADD(T27, T28);
          T2G = SUB(T27, T28);
          T3V = FNMS(KP500000000, T29, T26);
        }
        {
          E TF, TG, T2c, T2d;
          TE = ri[WS(is, 18)];
          TF = ri[WS(is, 34)];
          TG = ri[WS(is, 2)];
          TH = ADD(TF, TG);
          T2I = FNMS(KP500000000, TH, TE);
          T3Z = SUB(TG, TF);
          T2b = ii[WS(is, 18)];
          T2c = ii[WS(is, 34)];
          T2d = ii[WS(is, 2)];
          T2e = ADD(T2c, T2d);
          T2J = SUB(T2c, T2d);
          T3Y = FNMS(KP500000000, T2e, T2b);
        }
        T2H = FNMS(KP866025403, T2G, T2F);
        T2K = FNMS(KP866025403, T2J, T2I);
        T71 = SUB(T2H, T2K);
        T3X = FNMS(KP866025403, T3W, T3V);
        T40 = FNMS(KP866025403, T3Z, T3Y);
        T72 = SUB(T3X, T40);
        T4J = FMA(KP866025403, T2G, T2F);
        T4K = FMA(KP866025403, T2J, T2I);
        T4S = SUB(T4J, T4K);
        T4f = FMA(KP866025403, T3W, T3V);
        T4g = FMA(KP866025403, T3Z, T3Y);
        T4T = SUB(T4f, T4g);
        {
          E T2a, T2f, TD, TI;
          T2a = ADD(T26, T29);
          T2f = ADD(T2b, T2e);
          T2g = ADD(T2a, T2f);
          T8C = SUB(T2a, T2f);
          TD = ADD(Tz, TC);
          TI = ADD(TE, TH);
          TJ = ADD(TD, TI);
          T8B = SUB(TD, TI);
        }
      }
      {
        E TM, TP, T2O, T53, T50, T51, T2R, T52, TR, TU, T2T, T58, T55,
         T56, T2W;
        E T57;
        {
          E TN, TO, T2P, T2Q;
          TM = ri[WS(is, 3)];
          TN = ri[WS(is, 19)];
          TO = ri[WS(is, 35)];
          TP = ADD(TN, TO);
          T2O = FNMS(KP500000000, TP, TM);
          T53 = SUB(TO, TN);
          T50 = ii[WS(is, 3)];
          T2P = ii[WS(is, 19)];
          T2Q = ii[WS(is, 35)];
          T51 = ADD(T2P, T2Q);
          T2R = SUB(T2P, T2Q);
          T52 = FNMS(KP500000000, T51, T50);
        }
        {
          E TS, TT, T2U, T2V;
          TR = ri[WS(is, 27)];
          TS = ri[WS(is, 43)];
          TT = ri[WS(is, 11)];
          TU = ADD(TS, TT);
          T2T = FNMS(KP500000000, TU, TR);
          T58 = SUB(TT, TS);
          T55 = ii[WS(is, 27)];
          T2U = ii[WS(is, 43)];
          T2V = ii[WS(is, 11)];
          T56 = ADD(T2U, T2V);
          T2W = SUB(T2U, T2V);
          T57 = FNMS(KP500000000, T56, T55);
        }
        {
          E TQ, TV, T7h, T7i;
          TQ = ADD(TM, TP);
          TV = ADD(TR, TU);
          TW = ADD(TQ, TV);
          T8L = SUB(TQ, TV);
          {
            E T2S, T2X, T8H, T8I;
            T2S = FNMS(KP866025403, T2R, T2O);
            T2X = FNMS(KP866025403, T2W, T2T);
            T2Y = ADD(T2S, T2X);
            T7m = SUB(T2S, T2X);
            T8H = ADD(T50, T51);
            T8I = ADD(T55, T56);
            T8J = SUB(T8H, T8I);
            T9K = ADD(T8H, T8I);
          }
          T7h = FNMS(KP866025403, T53, T52);
          T7i = FNMS(KP866025403, T58, T57);
          T7j = SUB(T7h, T7i);
          T85 = ADD(T7h, T7i);
          {
            E T54, T59, T4r, T4s;
            T54 = FMA(KP866025403, T53, T52);
            T59 = FMA(KP866025403, T58, T57);
            T5a = SUB(T54, T59);
            T6A = ADD(T54, T59);
            T4r = FMA(KP866025403, T2R, T2O);
            T4s = FMA(KP866025403, T2W, T2T);
            T4t = ADD(T4r, T4s);
            T5d = SUB(T4r, T4s);
          }
        }
      }
      {
        E T19, T1c, T3b, T5u, T5r, T5s, T3e, T5t, T1e, T1h, T3g, T5z,
         T5w, T5x, T3j;
        E T5y;
        {
          E T1a, T1b, T3c, T3d;
          T19 = ri[WS(is, 45)];
          T1a = ri[WS(is, 13)];
          T1b = ri[WS(is, 29)];
          T1c = ADD(T1a, T1b);
          T3b = FNMS(KP500000000, T1c, T19);
          T5u = SUB(T1b, T1a);
          T5r = ii[WS(is, 45)];
          T3c = ii[WS(is, 13)];
          T3d = ii[WS(is, 29)];
          T5s = ADD(T3c, T3d);
          T3e = SUB(T3c, T3d);
          T5t = FNMS(KP500000000, T5s, T5r);
        }
        {
          E T1f, T1g, T3h, T3i;
          T1e = ri[WS(is, 21)];
          T1f = ri[WS(is, 37)];
          T1g = ri[WS(is, 5)];
          T1h = ADD(T1f, T1g);
          T3g = FNMS(KP500000000, T1h, T1e);
          T5z = SUB(T1g, T1f);
          T5w = ii[WS(is, 21)];
          T3h = ii[WS(is, 37)];
          T3i = ii[WS(is, 5)];
          T5x = ADD(T3h, T3i);
          T3j = SUB(T3h, T3i);
          T5y = FNMS(KP500000000, T5x, T5w);
        }
        {
          E T1d, T1i, T76, T77;
          T1d = ADD(T19, T1c);
          T1i = ADD(T1e, T1h);
          T1j = ADD(T1d, T1i);
          T8W = SUB(T1d, T1i);
          {
            E T3f, T3k, T8S, T8T;
            T3f = FNMS(KP866025403, T3e, T3b);
            T3k = FNMS(KP866025403, T3j, T3g);
            T3l = ADD(T3f, T3k);
            T7b = SUB(T3f, T3k);
            T8S = ADD(T5r, T5s);
            T8T = ADD(T5w, T5x);
            T8U = SUB(T8S, T8T);
            T9F = ADD(T8S, T8T);
          }
          T76 = FNMS(KP866025403, T5u, T5t);
          T77 = FNMS(KP866025403, T5z, T5y);
          T78 = SUB(T76, T77);
          T8a = ADD(T76, T77);
          {
            E T5v, T5A, T4k, T4l;
            T5v = FMA(KP866025403, T5u, T5t);
            T5A = FMA(KP866025403, T5z, T5y);
            T5B = SUB(T5v, T5A);
            T6u = ADD(T5v, T5A);
            T4k = FMA(KP866025403, T3e, T3b);
            T4l = FMA(KP866025403, T3j, T3g);
            T4m = ADD(T4k, T4l);
            T5E = SUB(T4k, T4l);
          }
        }
      }
      {
        E T1k, T1n, T3m, T5I, T5F, T5G, T3p, T5H, T1p, T1s, T3r, T5N,
         T5K, T5L, T3u;
        E T5M;
        {
          E T1l, T1m, T3n, T3o;
          T1k = ri[WS(is, 9)];
          T1l = ri[WS(is, 25)];
          T1m = ri[WS(is, 41)];
          T1n = ADD(T1l, T1m);
          T3m = FNMS(KP500000000, T1n, T1k);
          T5I = SUB(T1m, T1l);
          T5F = ii[WS(is, 9)];
          T3n = ii[WS(is, 25)];
          T3o = ii[WS(is, 41)];
          T5G = ADD(T3n, T3o);
          T3p = SUB(T3n, T3o);
          T5H = FNMS(KP500000000, T5G, T5F);
        }
        {
          E T1q, T1r, T3s, T3t;
          T1p = ri[WS(is, 33)];
          T1q = ri[WS(is, 1)];
          T1r = ri[WS(is, 17)];
          T1s = ADD(T1q, T1r);
          T3r = FNMS(KP500000000, T1s, T1p);
          T5N = SUB(T1r, T1q);
          T5K = ii[WS(is, 33)];
          T3s = ii[WS(is, 1)];
          T3t = ii[WS(is, 17)];
          T5L = ADD(T3s, T3t);
          T3u = SUB(T3s, T3t);
          T5M = FNMS(KP500000000, T5L, T5K);
        }
        {
          E T1o, T1t, T7c, T7d;
          T1o = ADD(T1k, T1n);
          T1t = ADD(T1p, T1s);
          T1u = ADD(T1o, T1t);
          T8R = SUB(T1o, T1t);
          {
            E T3q, T3v, T8X, T8Y;
            T3q = FNMS(KP866025403, T3p, T3m);
            T3v = FNMS(KP866025403, T3u, T3r);
            T3w = ADD(T3q, T3v);
            T79 = SUB(T3q, T3v);
            T8X = ADD(T5F, T5G);
            T8Y = ADD(T5K, T5L);
            T8Z = SUB(T8X, T8Y);
            T9G = ADD(T8X, T8Y);
          }
          T7c = FNMS(KP866025403, T5I, T5H);
          T7d = FNMS(KP866025403, T5N, T5M);
          T7e = SUB(T7c, T7d);
          T8b = ADD(T7c, T7d);
          {
            E T5J, T5O, T4n, T4o;
            T5J = FMA(KP866025403, T5I, T5H);
            T5O = FMA(KP866025403, T5N, T5M);
            T5P = SUB(T5J, T5O);
            T6v = ADD(T5J, T5O);
            T4n = FMA(KP866025403, T3p, T3m);
            T4o = FMA(KP866025403, T3u, T3r);
            T4p = ADD(T4n, T4o);
            T5C = SUB(T4n, T4o);
          }
        }
      }
      {
        E TX, T10, T2Z, T5h, T5e, T5f, T32, T5g, T12, T15, T34, T5m,
         T5j, T5k, T37;
        E T5l;
        {
          E TY, TZ, T30, T31;
          TX = ri[WS(is, 15)];
          TY = ri[WS(is, 31)];
          TZ = ri[WS(is, 47)];
          T10 = ADD(TY, TZ);
          T2Z = FNMS(KP500000000, T10, TX);
          T5h = SUB(TZ, TY);
          T5e = ii[WS(is, 15)];
          T30 = ii[WS(is, 31)];
          T31 = ii[WS(is, 47)];
          T5f = ADD(T30, T31);
          T32 = SUB(T30, T31);
          T5g = FNMS(KP500000000, T5f, T5e);
        }
        {
          E T13, T14, T35, T36;
          T12 = ri[WS(is, 39)];
          T13 = ri[WS(is, 7)];
          T14 = ri[WS(is, 23)];
          T15 = ADD(T13, T14);
          T34 = FNMS(KP500000000, T15, T12);
          T5m = SUB(T14, T13);
          T5j = ii[WS(is, 39)];
          T35 = ii[WS(is, 7)];
          T36 = ii[WS(is, 23)];
          T5k = ADD(T35, T36);
          T37 = SUB(T35, T36);
          T5l = FNMS(KP500000000, T5k, T5j);
        }
        {
          E T11, T16, T7n, T7o;
          T11 = ADD(TX, T10);
          T16 = ADD(T12, T15);
          T17 = ADD(T11, T16);
          T8G = SUB(T11, T16);
          {
            E T33, T38, T8M, T8N;
            T33 = FNMS(KP866025403, T32, T2Z);
            T38 = FNMS(KP866025403, T37, T34);
            T39 = ADD(T33, T38);
            T7k = SUB(T33, T38);
            T8M = ADD(T5e, T5f);
            T8N = ADD(T5j, T5k);
            T8O = SUB(T8M, T8N);
            T9L = ADD(T8M, T8N);
          }
          T7n = FNMS(KP866025403, T5h, T5g);
          T7o = FNMS(KP866025403, T5m, T5l);
          T7p = SUB(T7n, T7o);
          T86 = ADD(T7n, T7o);
          {
            E T5i, T5n, T4u, T4v;
            T5i = FMA(KP866025403, T5h, T5g);
            T5n = FMA(KP866025403, T5m, T5l);
            T5o = SUB(T5i, T5n);
            T6B = ADD(T5i, T5n);
            T4u = FMA(KP866025403, T32, T2Z);
            T4v = FMA(KP866025403, T37, T34);
            T4w = ADD(T4u, T4v);
            T5b = SUB(T4u, T4v);
          }
        }
      }
      {
        E TL, Ta3, Ta2, Ta4, T1w, T1x, T2i, T9Z;
        {
          E Tn, TK, Ta0, Ta1;
          Tn = ADD(Tb, Tm);
          TK = ADD(Ty, TJ);
          TL = ADD(Tn, TK);
          Ta3 = SUB(Tn, TK);
          Ta0 = ADD(T9K, T9L);
          Ta1 = ADD(T9F, T9G);
          Ta2 = ADD(Ta0, Ta1);
          Ta4 = SUB(Ta1, Ta0);
        }
        {
          E T18, T1v, T1U, T2h;
          T18 = ADD(TW, T17);
          T1v = ADD(T1j, T1u);
          T1w = ADD(T18, T1v);
          T1x = SUB(T18, T1v);
          T1U = ADD(T1I, T1T);
          T2h = ADD(T25, T2g);
          T2i = SUB(T1U, T2h);
          T9Z = ADD(T1U, T2h);
        }
        ro[WS(os, 24)] = SUB(TL, T1w);
        io[WS(os, 24)] = SUB(T9Z, Ta2);
        ro[0] = ADD(TL, T1w);
        io[0] = ADD(T9Z, Ta2);
        io[WS(os, 12)] = ADD(T1x, T2i);
        ro[WS(os, 12)] = ADD(Ta3, Ta4);
        io[WS(os, 36)] = SUB(T2i, T1x);
        ro[WS(os, 36)] = SUB(Ta3, Ta4);
      }
      {
        E T9D, T9X, T9R, T9T, T9I, T9V, T9N, T9U;
        {
          E T9B, T9C, T9P, T9Q;
          T9B = SUB(Ty, TJ);
          T9C = SUB(T1I, T1T);
          T9D = ADD(T9B, T9C);
          T9X = SUB(T9C, T9B);
          T9P = SUB(Tb, Tm);
          T9Q = SUB(T2g, T25);
          T9R = SUB(T9P, T9Q);
          T9T = ADD(T9P, T9Q);
        }
        {
          E T9E, T9H, T9J, T9M;
          T9E = SUB(T1j, T1u);
          T9H = SUB(T9F, T9G);
          T9I = SUB(T9E, T9H);
          T9V = ADD(T9E, T9H);
          T9J = SUB(TW, T17);
          T9M = SUB(T9K, T9L);
          T9N = ADD(T9J, T9M);
          T9U = SUB(T9M, T9J);
        }
        {
          E T9O, T9W, T9S, T9Y;
          T9O = SUB(T9I, T9N);
          io[WS(os, 30)] = FNMS(KP707106781, T9O, T9D);
          io[WS(os, 6)] = FMA(KP707106781, T9O, T9D);
          T9W = SUB(T9U, T9V);
          ro[WS(os, 30)] = FNMS(KP707106781, T9W, T9T);
          ro[WS(os, 6)] = FMA(KP707106781, T9W, T9T);
          T9S = ADD(T9N, T9I);
          ro[WS(os, 42)] = FNMS(KP707106781, T9S, T9R);
          ro[WS(os, 18)] = FMA(KP707106781, T9S, T9R);
          T9Y = ADD(T9U, T9V);
          io[WS(os, 42)] = FNMS(KP707106781, T9Y, T9X);
          io[WS(os, 18)] = FMA(KP707106781, T9Y, T9X);
        }
      }
      {
        E T8x, T9h, T9r, T95, T8E, T9s, T9p, T9x, T98, T9i, T8Q, T9d,
         T9m, T9w, T91;
        E T9c;
        {
          E T8A, T8D, T8K, T8P;
          T8x = SUB(T8v, T8w);
          T9h = ADD(T8v, T8w);
          T9r = SUB(T94, T93);
          T95 = ADD(T93, T94);
          T8A = SUB(T8y, T8z);
          T8D = ADD(T8B, T8C);
          T8E = SUB(T8A, T8D);
          T9s = ADD(T8A, T8D);
          {
            E T9n, T9o, T96, T97;
            T9n = ADD(T8W, T8Z);
            T9o = SUB(T8U, T8R);
            T9p = FNMS(KP414213562, T9o, T9n);
            T9x = FMA(KP414213562, T9n, T9o);
            T96 = SUB(T8B, T8C);
            T97 = ADD(T8z, T8y);
            T98 = SUB(T96, T97);
            T9i = ADD(T97, T96);
          }
          T8K = ADD(T8G, T8J);
          T8P = SUB(T8L, T8O);
          T8Q = FMA(KP414213562, T8P, T8K);
          T9d = FNMS(KP414213562, T8K, T8P);
          {
            E T9k, T9l, T8V, T90;
            T9k = ADD(T8L, T8O);
            T9l = SUB(T8J, T8G);
            T9m = FMA(KP414213562, T9l, T9k);
            T9w = FNMS(KP414213562, T9k, T9l);
            T8V = ADD(T8R, T8U);
            T90 = SUB(T8W, T8Z);
            T91 = FNMS(KP414213562, T90, T8V);
            T9c = FMA(KP414213562, T8V, T90);
          }
        }
        {
          E T8F, T92, T9b, T9e;
          T8F = FMA(KP707106781, T8E, T8x);
          T92 = SUB(T8Q, T91);
          ro[WS(os, 27)] = FNMS(KP923879532, T92, T8F);
          ro[WS(os, 3)] = FMA(KP923879532, T92, T8F);
          T9b = FMA(KP707106781, T98, T95);
          T9e = SUB(T9c, T9d);
          io[WS(os, 27)] = FNMS(KP923879532, T9e, T9b);
          io[WS(os, 3)] = FMA(KP923879532, T9e, T9b);
        }
        {
          E T99, T9a, T9f, T9g;
          T99 = FNMS(KP707106781, T98, T95);
          T9a = ADD(T8Q, T91);
          io[WS(os, 39)] = FNMS(KP923879532, T9a, T99);
          io[WS(os, 15)] = FMA(KP923879532, T9a, T99);
          T9f = FNMS(KP707106781, T8E, T8x);
          T9g = ADD(T9d, T9c);
          ro[WS(os, 39)] = FNMS(KP923879532, T9g, T9f);
          ro[WS(os, 15)] = FMA(KP923879532, T9g, T9f);
        }
        {
          E T9j, T9q, T9z, T9A;
          T9j = FMA(KP707106781, T9i, T9h);
          T9q = ADD(T9m, T9p);
          ro[WS(os, 9)] = FNMS(KP923879532, T9q, T9j);
          ro[WS(os, 33)] = FMA(KP923879532, T9q, T9j);
          T9z = FMA(KP707106781, T9s, T9r);
          T9A = ADD(T9w, T9x);
          io[WS(os, 9)] = FNMS(KP923879532, T9A, T9z);
          io[WS(os, 33)] = FMA(KP923879532, T9A, T9z);
        }
        {
          E T9t, T9u, T9v, T9y;
          T9t = FNMS(KP707106781, T9s, T9r);
          T9u = SUB(T9p, T9m);
          io[WS(os, 45)] = FNMS(KP923879532, T9u, T9t);
          io[WS(os, 21)] = FMA(KP923879532, T9u, T9t);
          T9v = FNMS(KP707106781, T9i, T9h);
          T9y = SUB(T9w, T9x);
          ro[WS(os, 45)] = FNMS(KP923879532, T9y, T9v);
          ro[WS(os, 21)] = FMA(KP923879532, T9y, T9v);
        }
      }
      {
        E T6X, T7H, T7M, T7X, T7P, T7W, T74, T7S, T7g, T7D, T7v, T7R,
         T7y, T7I, T7r;
        E T7C;
        {
          E T6V, T6W, T7K, T7L;
          T6V = SUB(T2l, T2o);
          T6W = SUB(T3I, T3L);
          T6X = SUB(T6V, T6W);
          T7H = ADD(T6V, T6W);
          T7K = SUB(T7j, T7k);
          T7L = ADD(T7m, T7p);
          T7M = FNMS(KP414213562, T7L, T7K);
          T7X = FMA(KP414213562, T7K, T7L);
        }
        {
          E T7N, T7O, T70, T73;
          T7N = SUB(T78, T79);
          T7O = ADD(T7b, T7e);
          T7P = FMA(KP414213562, T7O, T7N);
          T7W = FNMS(KP414213562, T7N, T7O);
          T70 = SUB(T6Y, T6Z);
          T73 = ADD(T71, T72);
          T74 = ADD(T70, T73);
          T7S = SUB(T70, T73);
        }
        {
          E T7a, T7f, T7t, T7u;
          T7a = ADD(T78, T79);
          T7f = SUB(T7b, T7e);
          T7g = FNMS(KP414213562, T7f, T7a);
          T7D = FMA(KP414213562, T7a, T7f);
          T7t = SUB(T3B, T3E);
          T7u = SUB(T2s, T2v);
          T7v = ADD(T7t, T7u);
          T7R = SUB(T7t, T7u);
        }
        {
          E T7w, T7x, T7l, T7q;
          T7w = ADD(T6Y, T6Z);
          T7x = SUB(T72, T71);
          T7y = ADD(T7w, T7x);
          T7I = SUB(T7x, T7w);
          T7l = ADD(T7j, T7k);
          T7q = SUB(T7m, T7p);
          T7r = FMA(KP414213562, T7q, T7l);
          T7C = FNMS(KP414213562, T7l, T7q);
        }
        {
          E T75, T7s, T7B, T7E;
          T75 = FNMS(KP707106781, T74, T6X);
          T7s = SUB(T7g, T7r);
          ro[WS(os, 35)] = FNMS(KP923879532, T7s, T75);
          ro[WS(os, 11)] = FMA(KP923879532, T7s, T75);
          T7B = FNMS(KP707106781, T7y, T7v);
          T7E = SUB(T7C, T7D);
          io[WS(os, 35)] = FNMS(KP923879532, T7E, T7B);
          io[WS(os, 11)] = FMA(KP923879532, T7E, T7B);
        }
        {
          E T7z, T7A, T7F, T7G;
          T7z = FMA(KP707106781, T7y, T7v);
          T7A = ADD(T7r, T7g);
          io[WS(os, 23)] = FNMS(KP923879532, T7A, T7z);
          io[WS(os, 47)] = FMA(KP923879532, T7A, T7z);
          T7F = FMA(KP707106781, T74, T6X);
          T7G = ADD(T7C, T7D);
          ro[WS(os, 23)] = FNMS(KP923879532, T7G, T7F);
          ro[WS(os, 47)] = FMA(KP923879532, T7G, T7F);
        }
        {
          E T7J, T7Q, T7V, T7Y;
          T7J = FMA(KP707106781, T7I, T7H);
          T7Q = SUB(T7M, T7P);
          ro[WS(os, 29)] = FNMS(KP923879532, T7Q, T7J);
          ro[WS(os, 5)] = FMA(KP923879532, T7Q, T7J);
          T7V = FMA(KP707106781, T7S, T7R);
          T7Y = SUB(T7W, T7X);
          io[WS(os, 29)] = FNMS(KP923879532, T7Y, T7V);
          io[WS(os, 5)] = FMA(KP923879532, T7Y, T7V);
        }
        {
          E T7T, T7U, T7Z, T80;
          T7T = FNMS(KP707106781, T7S, T7R);
          T7U = ADD(T7M, T7P);
          io[WS(os, 41)] = FNMS(KP923879532, T7U, T7T);
          io[WS(os, 17)] = FMA(KP923879532, T7U, T7T);
          T7Z = FNMS(KP707106781, T7I, T7H);
          T80 = ADD(T7X, T7W);
          ro[WS(os, 41)] = FNMS(KP923879532, T80, T7Z);
          ro[WS(os, 17)] = FMA(KP923879532, T80, T7Z);
        }
      }
      {
        E T4b, T6F, T6D, T6K, T6S, T6U, T4i, T6s, T4y, T4O, T4M, T6G,
         T6y, T6L, T4F;
        E T6r;
        {
          E T47, T4a, T6z, T6C;
          T47 = ADD(T45, T46);
          T4a = ADD(T48, T49);
          T4b = ADD(T47, T4a);
          T6F = SUB(T47, T4a);
          T6z = SUB(T4t, T4w);
          T6C = SUB(T6A, T6B);
          T6D = ADD(T6z, T6C);
          T6K = SUB(T6z, T6C);
        }
        {
          E T6Q, T6R, T4e, T4h;
          T6Q = ADD(T6A, T6B);
          T6R = ADD(T6u, T6v);
          T6S = SUB(T6Q, T6R);
          T6U = ADD(T6Q, T6R);
          T4e = ADD(T4c, T4d);
          T4h = ADD(T4f, T4g);
          T4i = ADD(T4e, T4h);
          T6s = SUB(T4e, T4h);
        }
        {
          E T4q, T4x, T4I, T4L;
          T4q = ADD(T4m, T4p);
          T4x = ADD(T4t, T4w);
          T4y = SUB(T4q, T4x);
          T4O = ADD(T4x, T4q);
          T4I = ADD(T4G, T4H);
          T4L = ADD(T4J, T4K);
          T4M = ADD(T4I, T4L);
          T6G = SUB(T4L, T4I);
        }
        {
          E T6w, T6x, T4B, T4E;
          T6w = SUB(T6u, T6v);
          T6x = SUB(T4m, T4p);
          T6y = SUB(T6w, T6x);
          T6L = ADD(T6x, T6w);
          T4B = ADD(T4z, T4A);
          T4E = ADD(T4C, T4D);
          T4F = ADD(T4B, T4E);
          T6r = SUB(T4B, T4E);
        }
        {
          E T4j, T6P, T4N, T6T;
          T4j = SUB(T4b, T4i);
          io[WS(os, 28)] = SUB(T4j, T4y);
          io[WS(os, 4)] = ADD(T4j, T4y);
          T6P = SUB(T4F, T4M);
          ro[WS(os, 28)] = SUB(T6P, T6S);
          ro[WS(os, 4)] = ADD(T6P, T6S);
          T4N = ADD(T4F, T4M);
          ro[WS(os, 40)] = SUB(T4N, T4O);
          ro[WS(os, 16)] = ADD(T4N, T4O);
          T6T = ADD(T4b, T4i);
          io[WS(os, 40)] = SUB(T6T, T6U);
          io[WS(os, 16)] = ADD(T6T, T6U);
        }
        {
          E T6t, T6E, T6J, T6M;
          T6t = ADD(T6r, T6s);
          T6E = SUB(T6y, T6D);
          ro[WS(os, 34)] = FNMS(KP707106781, T6E, T6t);
          ro[WS(os, 10)] = FMA(KP707106781, T6E, T6t);
          T6J = ADD(T6F, T6G);
          T6M = SUB(T6K, T6L);
          io[WS(os, 34)] = FNMS(KP707106781, T6M, T6J);
          io[WS(os, 10)] = FMA(KP707106781, T6M, T6J);
        }
        {
          E T6H, T6I, T6N, T6O;
          T6H = SUB(T6F, T6G);
          T6I = ADD(T6D, T6y);
          io[WS(os, 22)] = FNMS(KP707106781, T6I, T6H);
          io[WS(os, 46)] = FMA(KP707106781, T6I, T6H);
          T6N = SUB(T6r, T6s);
          T6O = ADD(T6K, T6L);
          ro[WS(os, 22)] = FNMS(KP707106781, T6O, T6N);
          ro[WS(os, 46)] = FMA(KP707106781, T6O, T6N);
        }
      }
      {
        E T2x, T8f, T8d, T8l, T8s, T8u, T2M, T82, T3y, T44, T42, T8g,
         T88, T8k, T3N;
        E T81;
        {
          E T2p, T2w, T89, T8c;
          T2p = ADD(T2l, T2o);
          T2w = ADD(T2s, T2v);
          T2x = ADD(T2p, T2w);
          T8f = SUB(T2p, T2w);
          T89 = SUB(T3l, T3w);
          T8c = SUB(T8a, T8b);
          T8d = SUB(T89, T8c);
          T8l = ADD(T89, T8c);
        }
        {
          E T8q, T8r, T2E, T2L;
          T8q = ADD(T85, T86);
          T8r = ADD(T8a, T8b);
          T8s = SUB(T8q, T8r);
          T8u = ADD(T8q, T8r);
          T2E = ADD(T2A, T2D);
          T2L = ADD(T2H, T2K);
          T2M = ADD(T2E, T2L);
          T82 = SUB(T2L, T2E);
        }
        {
          E T3a, T3x, T3U, T41;
          T3a = ADD(T2Y, T39);
          T3x = ADD(T3l, T3w);
          T3y = ADD(T3a, T3x);
          T44 = SUB(T3x, T3a);
          T3U = ADD(T3Q, T3T);
          T41 = ADD(T3X, T40);
          T42 = ADD(T3U, T41);
          T8g = SUB(T3U, T41);
        }
        {
          E T84, T87, T3F, T3M;
          T84 = SUB(T2Y, T39);
          T87 = SUB(T85, T86);
          T88 = ADD(T84, T87);
          T8k = SUB(T87, T84);
          T3F = ADD(T3B, T3E);
          T3M = ADD(T3I, T3L);
          T3N = ADD(T3F, T3M);
          T81 = SUB(T3F, T3M);
        }
        {
          E T2N, T8t, T43, T8p;
          T2N = ADD(T2x, T2M);
          ro[WS(os, 8)] = SUB(T2N, T3y);
          ro[WS(os, 32)] = ADD(T2N, T3y);
          T8t = ADD(T3N, T42);
          io[WS(os, 8)] = SUB(T8t, T8u);
          io[WS(os, 32)] = ADD(T8t, T8u);
          T43 = SUB(T3N, T42);
          io[WS(os, 44)] = SUB(T43, T44);
          io[WS(os, 20)] = ADD(T43, T44);
          T8p = SUB(T2x, T2M);
          ro[WS(os, 44)] = SUB(T8p, T8s);
          ro[WS(os, 20)] = ADD(T8p, T8s);
        }
        {
          E T83, T8e, T8n, T8o;
          T83 = SUB(T81, T82);
          T8e = SUB(T88, T8d);
          io[WS(os, 38)] = FNMS(KP707106781, T8e, T83);
          io[WS(os, 14)] = FMA(KP707106781, T8e, T83);
          T8n = SUB(T8f, T8g);
          T8o = SUB(T8l, T8k);
          ro[WS(os, 38)] = FNMS(KP707106781, T8o, T8n);
          ro[WS(os, 14)] = FMA(KP707106781, T8o, T8n);
        }
        {
          E T8h, T8i, T8j, T8m;
          T8h = ADD(T8f, T8g);
          T8i = ADD(T88, T8d);
          ro[WS(os, 26)] = FNMS(KP707106781, T8i, T8h);
          ro[WS(os, 2)] = FMA(KP707106781, T8i, T8h);
          T8j = ADD(T81, T82);
          T8m = ADD(T8k, T8l);
          io[WS(os, 26)] = FNMS(KP707106781, T8m, T8j);
          io[WS(os, 2)] = FMA(KP707106781, T8m, T8j);
        }
      }
      {
        E T4R, T6h, T6c, T6m, T6f, T6n, T4Y, T68, T5q, T62, T5V, T67,
         T5Y, T6i, T5R;
        E T63;
        {
          E T4P, T4Q, T6a, T6b;
          T4P = SUB(T4z, T4A);
          T4Q = SUB(T48, T49);
          T4R = SUB(T4P, T4Q);
          T6h = ADD(T4P, T4Q);
          T6a = ADD(T5d, T5o);
          T6b = SUB(T5a, T5b);
          T6c = FMA(KP414213562, T6b, T6a);
          T6m = FNMS(KP414213562, T6a, T6b);
        }
        {
          E T6d, T6e, T4U, T4X;
          T6d = ADD(T5E, T5P);
          T6e = SUB(T5B, T5C);
          T6f = FNMS(KP414213562, T6e, T6d);
          T6n = FMA(KP414213562, T6d, T6e);
          T4U = ADD(T4S, T4T);
          T4X = SUB(T4V, T4W);
          T4Y = SUB(T4U, T4X);
          T68 = ADD(T4X, T4U);
        }
        {
          E T5c, T5p, T5T, T5U;
          T5c = ADD(T5a, T5b);
          T5p = SUB(T5d, T5o);
          T5q = FMA(KP414213562, T5p, T5c);
          T62 = FNMS(KP414213562, T5c, T5p);
          T5T = SUB(T45, T46);
          T5U = SUB(T4C, T4D);
          T5V = ADD(T5T, T5U);
          T67 = SUB(T5T, T5U);
        }
        {
          E T5W, T5X, T5D, T5Q;
          T5W = ADD(T4W, T4V);
          T5X = SUB(T4S, T4T);
          T5Y = SUB(T5W, T5X);
          T6i = ADD(T5W, T5X);
          T5D = ADD(T5B, T5C);
          T5Q = SUB(T5E, T5P);
          T5R = FNMS(KP414213562, T5Q, T5D);
          T63 = FMA(KP414213562, T5D, T5Q);
        }
        {
          E T4Z, T5S, T65, T66;
          T4Z = FNMS(KP707106781, T4Y, T4R);
          T5S = SUB(T5q, T5R);
          ro[WS(os, 43)] = FNMS(KP923879532, T5S, T4Z);
          ro[WS(os, 19)] = FMA(KP923879532, T5S, T4Z);
          T65 = FNMS(KP707106781, T5Y, T5V);
          T66 = SUB(T63, T62);
          io[WS(os, 43)] = FNMS(KP923879532, T66, T65);
          io[WS(os, 19)] = FMA(KP923879532, T66, T65);
        }
        {
          E T5Z, T60, T61, T64;
          T5Z = FMA(KP707106781, T5Y, T5V);
          T60 = ADD(T5q, T5R);
          io[WS(os, 7)] = FNMS(KP923879532, T60, T5Z);
          io[WS(os, 31)] = FMA(KP923879532, T60, T5Z);
          T61 = FMA(KP707106781, T4Y, T4R);
          T64 = ADD(T62, T63);
          ro[WS(os, 7)] = FNMS(KP923879532, T64, T61);
          ro[WS(os, 31)] = FMA(KP923879532, T64, T61);
        }
        {
          E T69, T6g, T6p, T6q;
          T69 = FNMS(KP707106781, T68, T67);
          T6g = SUB(T6c, T6f);
          io[WS(os, 37)] = FNMS(KP923879532, T6g, T69);
          io[WS(os, 13)] = FMA(KP923879532, T6g, T69);
          T6p = FNMS(KP707106781, T6i, T6h);
          T6q = SUB(T6n, T6m);
          ro[WS(os, 37)] = FNMS(KP923879532, T6q, T6p);
          ro[WS(os, 13)] = FMA(KP923879532, T6q, T6p);
        }
        {
          E T6j, T6k, T6l, T6o;
          T6j = FMA(KP707106781, T6i, T6h);
          T6k = ADD(T6c, T6f);
          ro[WS(os, 25)] = FNMS(KP923879532, T6k, T6j);
          ro[WS(os, 1)] = FMA(KP923879532, T6k, T6j);
          T6l = FMA(KP707106781, T68, T67);
          T6o = ADD(T6m, T6n);
          io[WS(os, 25)] = FNMS(KP923879532, T6o, T6l);
          io[WS(os, 1)] = FMA(KP923879532, T6o, T6l);
        }
      }
    }
  }
}
