/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 28 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_r2cb_28 */

/*
 * This function contains 150 FP additions, 92 FP multiplications,
 * (or, 58 additions, 0 multiplications, 92 fused multiply/add),
 * 80 stack variables, 7 constants, and 56 memory accesses
 */
void dft_codelet_r2cb_28(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs)
{
  DK(KP1_949855824, +1.949855824363647214036263365987862434465571601);
  DK(KP801937735, +0.801937735804838252472204639014890102331838324);
  DK(KP554958132, +0.554958132087371191422194871006410481067288862);
  DK(KP1_801937735, +1.801937735804838252472204639014890102331838324);
  DK(KP692021471, +0.692021471630095869627814897002069140197260599);
  DK(KP356895867, +0.356895867892209443894399510021300583399127187);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, R0 = R0 + ovs, R1 = R1 + ovs, Cr = Cr + ivs, Ci = Ci + ivs, MAKE_VOLATILE_STRIDE(112, rs), MAKE_VOLATILE_STRIDE(112, csr), MAKE_VOLATILE_STRIDE(112, csi)) {
      E T5, TQ, Ts, Tz, T12, T1s, T1S, T2a, T17, T1c, T28, T29, T1t,
       T1u, T1M;
      E T1P, Tc, Tq, Tj, TV, T1k, T1f, Tt, Tv, Tu, T1p, T1C, T1x, TE,
       TO;
      E TJ, T25, T2i, T2d, TR, TT, TS, T1H, T20, T1V;
      {
        E T4, Ty, T3, Tx, T1, T2;
        T4 = Cr[WS(csr, 7)];
        Ty = Ci[WS(csi, 7)];
        T1 = Cr[0];
        T2 = Cr[WS(csr, 14)];
        T3 = ADD(T1, T2);
        Tx = SUB(T1, T2);
        T5 = FNMS(KP2_000000000, T4, T3);
        TQ = FNMS(KP2_000000000, Ty, Tx);
        Ts = FMA(KP2_000000000, T4, T3);
        Tz = FMA(KP2_000000000, Ty, Tx);
      }
      {
        E T8, TF, T15, T1O, Tb, T1N, TI, T16, T10, T1L, Tf, TK, Ti,
         T1K, TN;
        E T11, Tm, TA, T1a, T1R, TD, T1b, Tp, T1Q;
        {
          E T6, T7, TG, TH;
          T6 = Cr[WS(csr, 4)];
          T7 = Cr[WS(csr, 10)];
          T8 = ADD(T6, T7);
          TF = SUB(T6, T7);
          {
            E T13, T14, T9, Ta;
            T13 = Ci[WS(csi, 4)];
            T14 = Ci[WS(csi, 10)];
            T15 = SUB(T13, T14);
            T1O = ADD(T13, T14);
            T9 = Cr[WS(csr, 11)];
            Ta = Cr[WS(csr, 3)];
            Tb = ADD(T9, Ta);
            T1N = SUB(T9, Ta);
          }
          TG = Ci[WS(csi, 11)];
          TH = Ci[WS(csi, 3)];
          TI = ADD(TG, TH);
          T16 = SUB(TG, TH);
          {
            E TY, TZ, Td, Te;
            TY = Ci[WS(csi, 8)];
            TZ = Ci[WS(csi, 6)];
            T10 = SUB(TY, TZ);
            T1L = ADD(TY, TZ);
            Td = Cr[WS(csr, 8)];
            Te = Cr[WS(csr, 6)];
            Tf = ADD(Td, Te);
            TK = SUB(Td, Te);
          }
        }
        {
          E Tg, Th, T18, T19;
          Tg = Cr[WS(csr, 13)];
          Th = Cr[WS(csr, 1)];
          Ti = ADD(Tg, Th);
          T1K = SUB(Tg, Th);
          {
            E TL, TM, Tk, Tl;
            TL = Ci[WS(csi, 13)];
            TM = Ci[WS(csi, 1)];
            TN = ADD(TL, TM);
            T11 = SUB(TM, TL);
            Tk = Cr[WS(csr, 12)];
            Tl = Cr[WS(csr, 2)];
            Tm = ADD(Tk, Tl);
            TA = SUB(Tk, Tl);
          }
          T18 = Ci[WS(csi, 12)];
          T19 = Ci[WS(csi, 2)];
          T1a = SUB(T18, T19);
          T1R = ADD(T18, T19);
          {
            E TB, TC, Tn, To;
            TB = Ci[WS(csi, 9)];
            TC = Ci[WS(csi, 5)];
            TD = ADD(TB, TC);
            T1b = SUB(TC, TB);
            Tn = Cr[WS(csr, 9)];
            To = Cr[WS(csr, 5)];
            Tp = ADD(Tn, To);
            T1Q = SUB(Tn, To);
          }
        }
        T12 = SUB(T10, T11);
        T1s = ADD(T11, T10);
        T1S = ADD(T1Q, T1R);
        T2a = SUB(T1R, T1Q);
        T17 = SUB(T15, T16);
        T1c = SUB(T1a, T1b);
        T28 = SUB(T1L, T1K);
        T29 = SUB(T1O, T1N);
        T1t = ADD(T16, T15);
        T1u = ADD(T1b, T1a);
        T1M = ADD(T1K, T1L);
        T1P = ADD(T1N, T1O);
        Tc = SUB(T8, Tb);
        Tq = SUB(Tm, Tp);
        Tj = SUB(Tf, Ti);
        TV = FNMS(KP356895867, Tj, Tc);
        T1k = FNMS(KP356895867, Tq, Tj);
        T1f = FNMS(KP356895867, Tc, Tq);
        Tt = ADD(T8, Tb);
        Tv = ADD(Tm, Tp);
        Tu = ADD(Tf, Ti);
        T1p = FNMS(KP356895867, Tu, Tt);
        T1C = FNMS(KP356895867, Tv, Tu);
        T1x = FNMS(KP356895867, Tt, Tv);
        TE = SUB(TA, TD);
        TO = SUB(TK, TN);
        TJ = ADD(TF, TI);
        T25 = FNMS(KP356895867, TO, TJ);
        T2i = FNMS(KP356895867, TE, TO);
        T2d = FNMS(KP356895867, TJ, TE);
        TR = ADD(TA, TD);
        TT = ADD(TK, TN);
        TS = SUB(TF, TI);
        T1H = FNMS(KP356895867, TT, TS);
        T20 = FNMS(KP356895867, TR, TT);
        T1V = FNMS(KP356895867, TS, TR);
      }
      {
        E Tr, Tw, TP, TU;
        Tr = ADD(Tc, ADD(Tj, Tq));
        R0[WS(rs, 7)] = FMA(KP2_000000000, Tr, T5);
        Tw = ADD(Tt, ADD(Tu, Tv));
        R0[0] = FMA(KP2_000000000, Tw, Ts);
        TP = ADD(TE, ADD(TJ, TO));
        R1[WS(rs, 3)] = FMA(KP2_000000000, TP, Tz);
        TU = ADD(TR, ADD(TS, TT));
        R1[WS(rs, 10)] = FMA(KP2_000000000, TU, TQ);
      }
      {
        E TX, T1e, TW, T1d;
        TW = FNMS(KP692021471, TV, Tq);
        TX = FNMS(KP1_801937735, TW, T5);
        T1d = FMA(KP554958132, T1c, T17);
        T1e = FMA(KP801937735, T1d, T12);
        R0[WS(rs, 11)] = FNMS(KP1_949855824, T1e, TX);
        R0[WS(rs, 3)] = FMA(KP1_949855824, T1e, TX);
      }
      {
        E T1h, T1j, T1g, T1i;
        T1g = FNMS(KP692021471, T1f, Tj);
        T1h = FNMS(KP1_801937735, T1g, T5);
        T1i = FMA(KP554958132, T12, T1c);
        T1j = FNMS(KP801937735, T1i, T17);
        R0[WS(rs, 1)] = FNMS(KP1_949855824, T1j, T1h);
        R0[WS(rs, 13)] = FMA(KP1_949855824, T1j, T1h);
      }
      {
        E T2f, T2h, T2e, T2g;
        T2e = FNMS(KP692021471, T2d, TO);
        T2f = FNMS(KP1_801937735, T2e, Tz);
        T2g = FMA(KP554958132, T28, T2a);
        T2h = FNMS(KP801937735, T2g, T29);
        R1[WS(rs, 11)] = FNMS(KP1_949855824, T2h, T2f);
        R1[WS(rs, 9)] = FMA(KP1_949855824, T2h, T2f);
      }
      {
        E T2k, T2m, T2j, T2l;
        T2j = FNMS(KP692021471, T2i, TJ);
        T2k = FNMS(KP1_801937735, T2j, Tz);
        T2l = FNMS(KP554958132, T29, T28);
        T2m = FNMS(KP801937735, T2l, T2a);
        R1[WS(rs, 1)] = FNMS(KP1_949855824, T2m, T2k);
        R1[WS(rs, 5)] = FMA(KP1_949855824, T2m, T2k);
      }
      {
        E T1m, T1o, T1l, T1n;
        T1l = FNMS(KP692021471, T1k, Tc);
        T1m = FNMS(KP1_801937735, T1l, T5);
        T1n = FNMS(KP554958132, T17, T12);
        T1o = FNMS(KP801937735, T1n, T1c);
        R0[WS(rs, 5)] = FNMS(KP1_949855824, T1o, T1m);
        R0[WS(rs, 9)] = FMA(KP1_949855824, T1o, T1m);
      }
      {
        E T1E, T1G, T1D, T1F;
        T1D = FNMS(KP692021471, T1C, Tt);
        T1E = FNMS(KP1_801937735, T1D, Ts);
        T1F = FNMS(KP554958132, T1t, T1s);
        T1G = FNMS(KP801937735, T1F, T1u);
        R0[WS(rs, 12)] = FNMS(KP1_949855824, T1G, T1E);
        R0[WS(rs, 2)] = FMA(KP1_949855824, T1G, T1E);
      }
      {
        E T1J, T1U, T1I, T1T;
        T1I = FNMS(KP692021471, T1H, TR);
        T1J = FNMS(KP1_801937735, T1I, TQ);
        T1T = FMA(KP554958132, T1S, T1P);
        T1U = FMA(KP801937735, T1T, T1M);
        R1[0] = FNMS(KP1_949855824, T1U, T1J);
        R1[WS(rs, 6)] = FMA(KP1_949855824, T1U, T1J);
      }
      {
        E T27, T2c, T26, T2b;
        T26 = FNMS(KP692021471, T25, TE);
        T27 = FNMS(KP1_801937735, T26, Tz);
        T2b = FMA(KP554958132, T2a, T29);
        T2c = FMA(KP801937735, T2b, T28);
        R1[WS(rs, 7)] = FNMS(KP1_949855824, T2c, T27);
        R1[WS(rs, 13)] = FMA(KP1_949855824, T2c, T27);
      }
      {
        E T1r, T1w, T1q, T1v;
        T1q = FNMS(KP692021471, T1p, Tv);
        T1r = FNMS(KP1_801937735, T1q, Ts);
        T1v = FMA(KP554958132, T1u, T1t);
        T1w = FMA(KP801937735, T1v, T1s);
        R0[WS(rs, 4)] = FNMS(KP1_949855824, T1w, T1r);
        R0[WS(rs, 10)] = FMA(KP1_949855824, T1w, T1r);
      }
      {
        E T1z, T1B, T1y, T1A;
        T1y = FNMS(KP692021471, T1x, Tu);
        T1z = FNMS(KP1_801937735, T1y, Ts);
        T1A = FMA(KP554958132, T1s, T1u);
        T1B = FNMS(KP801937735, T1A, T1t);
        R0[WS(rs, 8)] = FNMS(KP1_949855824, T1B, T1z);
        R0[WS(rs, 6)] = FMA(KP1_949855824, T1B, T1z);
      }
      {
        E T1X, T1Z, T1W, T1Y;
        T1W = FNMS(KP692021471, T1V, TT);
        T1X = FNMS(KP1_801937735, T1W, TQ);
        T1Y = FMA(KP554958132, T1M, T1S);
        T1Z = FNMS(KP801937735, T1Y, T1P);
        R1[WS(rs, 4)] = FNMS(KP1_949855824, T1Z, T1X);
        R1[WS(rs, 2)] = FMA(KP1_949855824, T1Z, T1X);
      }
      {
        E T22, T24, T21, T23;
        T21 = FNMS(KP692021471, T20, TS);
        T22 = FNMS(KP1_801937735, T21, TQ);
        T23 = FNMS(KP554958132, T1P, T1M);
        T24 = FNMS(KP801937735, T23, T1S);
        R1[WS(rs, 8)] = FNMS(KP1_949855824, T24, T22);
        R1[WS(rs, 12)] = FMA(KP1_949855824, T24, T22);
      }
    }
  }
}
