/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_r2cb.native -n 128 -sign 1 -standalone -fma -generic-arith -compact -name dft_codelet_r2cb_128 */

/*
 * This function contains 956 FP additions, 540 FP multiplications,
 * (or, 416 additions, 0 multiplications, 540 fused multiply/add),
 * 195 stack variables, 36 constants, and 256 memory accesses
 */
void dft_codelet_r2cb_128(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs)
{
  DK(KP1_715457220, +1.715457220000544139804539968569540274084981599);
  DK(KP599376933, +0.599376933681923766271389869014404232837890546);
  DK(KP1_606415062, +1.606415062961289819613353025926283847759138854);
  DK(KP741650546, +0.741650546272035369581266691172079863842265220);
  DK(KP1_940062506, +1.940062506389087985207968414572200502913731924);
  DK(KP250486960, +0.250486960191305461595702160124721208578685568);
  DK(KP1_978353019, +1.978353019929561946903347476032486127967379067);
  DK(KP148335987, +0.148335987538347428753676511486911367000625355);
  DK(KP831469612, +0.831469612302545237078788377617905756738560812);
  DK(KP1_807978586, +1.807978586246886663172400594461074097420264050);
  DK(KP472964775, +0.472964775891319928124438237972992463904131113);
  DK(KP1_481902250, +1.481902250709918182351233794990325459457910619);
  DK(KP906347169, +0.906347169019147157946142717268914412664134293);
  DK(KP1_883088130, +1.883088130366041556825018805199004714371179592);
  DK(KP357805721, +0.357805721314524104672487743774474392487532769);
  DK(KP1_997590912, +1.997590912410344785429543209518201388886407229);
  DK(KP049126849, +0.049126849769467254105343321271313617079695752);
  DK(KP980785280, +0.980785280403230449126182236134239036973933731);
  DK(KP1_913880671, +1.913880671464417729871595773960539938965698411);
  DK(KP303346683, +0.303346683607342391675883946941299872384187453);
  DK(KP1_763842528, +1.763842528696710059425513727320776699016885241);
  DK(KP534511135, +0.534511135950791641089685961295362908582039528);
  DK(KP1_662939224, +1.662939224605090474157576755235811513477121624);
  DK(KP668178637, +0.668178637919298919997757686523080761552472251);
  DK(KP1_546020906, +1.546020906725473921621813219516939601942082586);
  DK(KP820678790, +0.820678790828660330972281985331011598767386482);
  DK(KP1_990369453, +1.990369453344393772489673906218959843150949737);
  DK(KP098491403, +0.098491403357164253077197521291327432293052451);
  DK(KP1_961570560, +1.961570560806460898252364472268478073947867462);
  DK(KP198912367, +0.198912367379658006911597622644676228597850501);
  DK(KP923879532, +0.923879532511286756128183189396788286822416626);
  DK(KP1_847759065, +1.847759065022573512256366378793576573644833252);
  DK(KP707106781, +0.707106781186547524400844362104849039284835938);
  DK(KP414213562, +0.414213562373095048801688724209698078569671875);
  DK(KP1_414213562, +1.414213562373095048801688724209698078569671875);
  DK(KP2_000000000, +2.000000000000000000000000000000000000000000000);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, R0 = R0 + ovs, R1 = R1 + ovs, Cr = Cr + ivs, Ci = Ci + ivs, MAKE_VOLATILE_STRIDE(512, rs), MAKE_VOLATILE_STRIDE(512, csr), MAKE_VOLATILE_STRIDE(512, csi)) {
      E T9, Tdr, Ta9, Tcl, T2d, T6b, T7j, T91, Tg, Tds, T2o, T6c, T7m,
       T92, Tae;
      E Tcm, Tw, Tdu, Tap, Tco, Tdx, TeM, T2G, T6f, T2P, T6e, T7t, T94,
       Tak, Tcp;
      E T7q, T95, T1i, TdM, TbD, TcL, Te6, Tf0, T42, T6q, T5t, T6B,
       T8j, T9r, TaY;
      E TcA, T7S, T9g, TM, TdA, TaN, Tcv, TdI, TeP, T38, T6i, T3F, T6l,
       T7J, T9b;
      E Taw, Tcs, T7y, T98, T1N, TeW, T4H, T6x, TdV, Te8, T4Q, T6w,
       T86, T9j, TcI;
      E TcO, T83, T9k, Tbl, TbI, T22, TeV, T58, T6u, Te0, Te9, T5h,
       T6t, T8d, T9m;
      E TcF, TcP, T8a, T9n, Tbw, TbJ, T1x, Te3, TbG, TcB, TdP, Tf1,
       T4p, T6C, T5w;
      E T6r, T8m, T9h, Tb9, TcM, T7Z, T9s, T11, TdF, TaQ, Tct, TdD,
       TeQ, T3v, T6m;
      E T3I, T6j, T7M, T99, TaH, Tcw, T7F, T9c;
      {
        E T4, T26, T3, T25, T8, T28, T2b, Ta8, T1, T2, T5, Ta7;
        T4 = Cr[WS(csr, 32)];
        T26 = Ci[WS(csi, 32)];
        T1 = Cr[0];
        T2 = Cr[WS(csr, 64)];
        T3 = ADD(T1, T2);
        T25 = SUB(T1, T2);
        {
          E T6, T7, T29, T2a;
          T6 = Cr[WS(csr, 16)];
          T7 = Cr[WS(csr, 48)];
          T8 = ADD(T6, T7);
          T28 = SUB(T6, T7);
          T29 = Ci[WS(csi, 16)];
          T2a = Ci[WS(csi, 48)];
          T2b = ADD(T29, T2a);
          Ta8 = SUB(T29, T2a);
        }
        T5 = FMA(KP2_000000000, T4, T3);
        T9 = FMA(KP2_000000000, T8, T5);
        Tdr = FNMS(KP2_000000000, T8, T5);
        Ta7 = FNMS(KP2_000000000, T4, T3);
        Ta9 = FNMS(KP2_000000000, Ta8, Ta7);
        Tcl = FMA(KP2_000000000, Ta8, Ta7);
        {
          E T27, T2c, T7h, T7i;
          T27 = FNMS(KP2_000000000, T26, T25);
          T2c = SUB(T28, T2b);
          T2d = FMA(KP1_414213562, T2c, T27);
          T6b = FNMS(KP1_414213562, T2c, T27);
          T7h = FMA(KP2_000000000, T26, T25);
          T7i = ADD(T28, T2b);
          T7j = FNMS(KP1_414213562, T7i, T7h);
          T91 = FMA(KP1_414213562, T7i, T7h);
        }
      }
      {
        E Tc, T2e, T2m, Tab, Tf, T2j, T2h, Tac, T2i, T2n;
        {
          E Ta, Tb, T2k, T2l;
          Ta = Cr[WS(csr, 8)];
          Tb = Cr[WS(csr, 56)];
          Tc = ADD(Ta, Tb);
          T2e = SUB(Ta, Tb);
          T2k = Ci[WS(csi, 8)];
          T2l = Ci[WS(csi, 56)];
          T2m = ADD(T2k, T2l);
          Tab = SUB(T2k, T2l);
        }
        {
          E Td, Te, T2f, T2g;
          Td = Cr[WS(csr, 40)];
          Te = Cr[WS(csr, 24)];
          Tf = ADD(Td, Te);
          T2j = SUB(Td, Te);
          T2f = Ci[WS(csi, 40)];
          T2g = Ci[WS(csi, 24)];
          T2h = ADD(T2f, T2g);
          Tac = SUB(T2f, T2g);
        }
        Tg = ADD(Tc, Tf);
        Tds = ADD(Tac, Tab);
        T2i = SUB(T2e, T2h);
        T2n = ADD(T2j, T2m);
        T2o = FNMS(KP414213562, T2n, T2i);
        T6c = FMA(KP414213562, T2i, T2n);
        {
          E T7k, T7l, Taa, Tad;
          T7k = SUB(T2m, T2j);
          T7l = ADD(T2e, T2h);
          T7m = FNMS(KP414213562, T7l, T7k);
          T92 = FMA(KP414213562, T7k, T7l);
          Taa = SUB(Tc, Tf);
          Tad = SUB(Tab, Tac);
          Tae = SUB(Taa, Tad);
          Tcm = ADD(Taa, Tad);
        }
      }
      {
        E Tk, T2q, T2K, Tam, Tn, T2H, T2t, Tan, Tu, Tah, T2E, T2N, Tr,
         Tai, T2z;
        E T2M;
        {
          E Ti, Tj, T2r, T2s;
          Ti = Cr[WS(csr, 4)];
          Tj = Cr[WS(csr, 60)];
          Tk = ADD(Ti, Tj);
          T2q = SUB(Ti, Tj);
          {
            E T2I, T2J, Tl, Tm;
            T2I = Ci[WS(csi, 4)];
            T2J = Ci[WS(csi, 60)];
            T2K = ADD(T2I, T2J);
            Tam = SUB(T2I, T2J);
            Tl = Cr[WS(csr, 36)];
            Tm = Cr[WS(csr, 28)];
            Tn = ADD(Tl, Tm);
            T2H = SUB(Tl, Tm);
          }
          T2r = Ci[WS(csi, 36)];
          T2s = Ci[WS(csi, 28)];
          T2t = ADD(T2r, T2s);
          Tan = SUB(T2r, T2s);
          {
            E Ts, Tt, T2A, T2B, T2C, T2D;
            Ts = Cr[WS(csr, 12)];
            Tt = Cr[WS(csr, 52)];
            T2A = SUB(Ts, Tt);
            T2B = Ci[WS(csi, 12)];
            T2C = Ci[WS(csi, 52)];
            T2D = ADD(T2B, T2C);
            Tu = ADD(Ts, Tt);
            Tah = SUB(T2C, T2B);
            T2E = SUB(T2A, T2D);
            T2N = ADD(T2A, T2D);
          }
          {
            E Tp, Tq, T2v, T2w, T2x, T2y;
            Tp = Cr[WS(csr, 20)];
            Tq = Cr[WS(csr, 44)];
            T2v = SUB(Tp, Tq);
            T2w = Ci[WS(csi, 20)];
            T2x = Ci[WS(csi, 44)];
            T2y = ADD(T2w, T2x);
            Tr = ADD(Tp, Tq);
            Tai = SUB(T2w, T2x);
            T2z = SUB(T2v, T2y);
            T2M = ADD(T2v, T2y);
          }
        }
        {
          E To, Tv, Tal, Tao;
          To = ADD(Tk, Tn);
          Tv = ADD(Tr, Tu);
          Tw = ADD(To, Tv);
          Tdu = SUB(To, Tv);
          Tal = SUB(Tr, Tu);
          Tao = SUB(Tam, Tan);
          Tap = ADD(Tal, Tao);
          Tco = SUB(Tao, Tal);
        }
        {
          E Tdv, Tdw, T2u, T2F;
          Tdv = ADD(Tan, Tam);
          Tdw = ADD(Tai, Tah);
          Tdx = SUB(Tdv, Tdw);
          TeM = ADD(Tdw, Tdv);
          T2u = SUB(T2q, T2t);
          T2F = ADD(T2z, T2E);
          T2G = FMA(KP707106781, T2F, T2u);
          T6f = FNMS(KP707106781, T2F, T2u);
        }
        {
          E T2L, T2O, T7r, T7s;
          T2L = ADD(T2H, T2K);
          T2O = SUB(T2M, T2N);
          T2P = FMA(KP707106781, T2O, T2L);
          T6e = FNMS(KP707106781, T2O, T2L);
          T7r = SUB(T2K, T2H);
          T7s = SUB(T2E, T2z);
          T7t = FNMS(KP707106781, T7s, T7r);
          T94 = FMA(KP707106781, T7s, T7r);
        }
        {
          E Tag, Taj, T7o, T7p;
          Tag = SUB(Tk, Tn);
          Taj = SUB(Tah, Tai);
          Tak = ADD(Tag, Taj);
          Tcp = SUB(Tag, Taj);
          T7o = ADD(T2q, T2t);
          T7p = ADD(T2M, T2N);
          T7q = FNMS(KP707106781, T7p, T7o);
          T95 = FMA(KP707106781, T7p, T7o);
        }
      }
      {
        E T16, T3M, T5o, TbA, T19, T5l, T3P, TbB, T1g, TaV, T40, T5r,
         T1d, TaW, T3V;
        E T5q;
        {
          E T14, T15, T3N, T3O;
          T14 = Cr[WS(csr, 1)];
          T15 = Cr[WS(csr, 63)];
          T16 = ADD(T14, T15);
          T3M = SUB(T14, T15);
          {
            E T5m, T5n, T17, T18;
            T5m = Ci[WS(csi, 1)];
            T5n = Ci[WS(csi, 63)];
            T5o = ADD(T5m, T5n);
            TbA = SUB(T5m, T5n);
            T17 = Cr[WS(csr, 33)];
            T18 = Cr[WS(csr, 31)];
            T19 = ADD(T17, T18);
            T5l = SUB(T17, T18);
          }
          T3N = Ci[WS(csi, 33)];
          T3O = Ci[WS(csi, 31)];
          T3P = ADD(T3N, T3O);
          TbB = SUB(T3N, T3O);
          {
            E T1e, T1f, T3W, T3X, T3Y, T3Z;
            T1e = Cr[WS(csr, 15)];
            T1f = Cr[WS(csr, 49)];
            T3W = SUB(T1e, T1f);
            T3X = Ci[WS(csi, 15)];
            T3Y = Ci[WS(csi, 49)];
            T3Z = ADD(T3X, T3Y);
            T1g = ADD(T1e, T1f);
            TaV = SUB(T3Y, T3X);
            T40 = SUB(T3W, T3Z);
            T5r = ADD(T3W, T3Z);
          }
          {
            E T1b, T1c, T3R, T3S, T3T, T3U;
            T1b = Cr[WS(csr, 17)];
            T1c = Cr[WS(csr, 47)];
            T3R = SUB(T1b, T1c);
            T3S = Ci[WS(csi, 17)];
            T3T = Ci[WS(csi, 47)];
            T3U = ADD(T3S, T3T);
            T1d = ADD(T1b, T1c);
            TaW = SUB(T3S, T3T);
            T3V = SUB(T3R, T3U);
            T5q = ADD(T3R, T3U);
          }
        }
        {
          E T1a, T1h, Tbz, TbC;
          T1a = ADD(T16, T19);
          T1h = ADD(T1d, T1g);
          T1i = ADD(T1a, T1h);
          TdM = SUB(T1a, T1h);
          Tbz = SUB(T1d, T1g);
          TbC = SUB(TbA, TbB);
          TbD = ADD(Tbz, TbC);
          TcL = SUB(TbC, Tbz);
        }
        {
          E Te4, Te5, T3Q, T41;
          Te4 = ADD(TbB, TbA);
          Te5 = ADD(TaW, TaV);
          Te6 = SUB(Te4, Te5);
          Tf0 = ADD(Te5, Te4);
          T3Q = SUB(T3M, T3P);
          T41 = ADD(T3V, T40);
          T42 = FMA(KP707106781, T41, T3Q);
          T6q = FNMS(KP707106781, T41, T3Q);
        }
        {
          E T5p, T5s, T8h, T8i;
          T5p = ADD(T5l, T5o);
          T5s = SUB(T5q, T5r);
          T5t = FMA(KP707106781, T5s, T5p);
          T6B = FNMS(KP707106781, T5s, T5p);
          T8h = SUB(T5o, T5l);
          T8i = SUB(T40, T3V);
          T8j = FNMS(KP707106781, T8i, T8h);
          T9r = FMA(KP707106781, T8i, T8h);
        }
        {
          E TaU, TaX, T7Q, T7R;
          TaU = SUB(T16, T19);
          TaX = SUB(TaV, TaW);
          TaY = ADD(TaU, TaX);
          TcA = SUB(TaU, TaX);
          T7Q = ADD(T3M, T3P);
          T7R = ADD(T5q, T5r);
          T7S = FNMS(KP707106781, T7R, T7Q);
          T9g = FMA(KP707106781, T7R, T7Q);
        }
      }
      {
        E TA, T2S, T3A, TaK, TD, T3x, T2V, TaL, TK, Tat, T36, T3D, TH,
         Tau, T31;
        E T3C;
        {
          E Ty, Tz, T2T, T2U;
          Ty = Cr[WS(csr, 2)];
          Tz = Cr[WS(csr, 62)];
          TA = ADD(Ty, Tz);
          T2S = SUB(Ty, Tz);
          {
            E T3y, T3z, TB, TC;
            T3y = Ci[WS(csi, 2)];
            T3z = Ci[WS(csi, 62)];
            T3A = ADD(T3y, T3z);
            TaK = SUB(T3y, T3z);
            TB = Cr[WS(csr, 34)];
            TC = Cr[WS(csr, 30)];
            TD = ADD(TB, TC);
            T3x = SUB(TB, TC);
          }
          T2T = Ci[WS(csi, 34)];
          T2U = Ci[WS(csi, 30)];
          T2V = ADD(T2T, T2U);
          TaL = SUB(T2T, T2U);
          {
            E TI, TJ, T32, T33, T34, T35;
            TI = Cr[WS(csr, 14)];
            TJ = Cr[WS(csr, 50)];
            T32 = SUB(TI, TJ);
            T33 = Ci[WS(csi, 14)];
            T34 = Ci[WS(csi, 50)];
            T35 = ADD(T33, T34);
            TK = ADD(TI, TJ);
            Tat = SUB(T34, T33);
            T36 = SUB(T32, T35);
            T3D = ADD(T32, T35);
          }
          {
            E TF, TG, T2X, T2Y, T2Z, T30;
            TF = Cr[WS(csr, 18)];
            TG = Cr[WS(csr, 46)];
            T2X = SUB(TF, TG);
            T2Y = Ci[WS(csi, 18)];
            T2Z = Ci[WS(csi, 46)];
            T30 = ADD(T2Y, T2Z);
            TH = ADD(TF, TG);
            Tau = SUB(T2Y, T2Z);
            T31 = SUB(T2X, T30);
            T3C = ADD(T2X, T30);
          }
        }
        {
          E TE, TL, TaJ, TaM;
          TE = ADD(TA, TD);
          TL = ADD(TH, TK);
          TM = ADD(TE, TL);
          TdA = SUB(TE, TL);
          TaJ = SUB(TH, TK);
          TaM = SUB(TaK, TaL);
          TaN = ADD(TaJ, TaM);
          Tcv = SUB(TaM, TaJ);
        }
        {
          E TdG, TdH, T2W, T37;
          TdG = ADD(TaL, TaK);
          TdH = ADD(Tau, Tat);
          TdI = SUB(TdG, TdH);
          TeP = ADD(TdH, TdG);
          T2W = SUB(T2S, T2V);
          T37 = ADD(T31, T36);
          T38 = FMA(KP707106781, T37, T2W);
          T6i = FNMS(KP707106781, T37, T2W);
        }
        {
          E T3B, T3E, T7H, T7I;
          T3B = ADD(T3x, T3A);
          T3E = SUB(T3C, T3D);
          T3F = FMA(KP707106781, T3E, T3B);
          T6l = FNMS(KP707106781, T3E, T3B);
          T7H = SUB(T3A, T3x);
          T7I = SUB(T36, T31);
          T7J = FNMS(KP707106781, T7I, T7H);
          T9b = FMA(KP707106781, T7I, T7H);
        }
        {
          E Tas, Tav, T7w, T7x;
          Tas = SUB(TA, TD);
          Tav = SUB(Tat, Tau);
          Taw = ADD(Tas, Tav);
          Tcs = SUB(Tas, Tav);
          T7w = ADD(T2S, T2V);
          T7x = ADD(T3C, T3D);
          T7y = FNMS(KP707106781, T7x, T7w);
          T98 = FMA(KP707106781, T7x, T7w);
        }
      }
      {
        E T1F, Tbb, T4r, T4I, T4u, TdS, T4L, Tbj, T1M, Tbg, TdT, T4A,
         T4F, T4O, Tbe;
        E T4N, TcG, TcH;
        {
          E T1z, T1A, T1B, T1C, T1D, T1E;
          T1z = Cr[WS(csr, 5)];
          T1A = Cr[WS(csr, 59)];
          T1B = ADD(T1z, T1A);
          T1C = Cr[WS(csr, 37)];
          T1D = Cr[WS(csr, 27)];
          T1E = ADD(T1C, T1D);
          T1F = ADD(T1B, T1E);
          Tbb = SUB(T1B, T1E);
          T4r = SUB(T1z, T1A);
          T4I = SUB(T1C, T1D);
        }
        {
          E T4s, T4t, Tbi, T4J, T4K, Tbh;
          T4s = Ci[WS(csi, 37)];
          T4t = Ci[WS(csi, 27)];
          Tbi = SUB(T4s, T4t);
          T4J = Ci[WS(csi, 5)];
          T4K = Ci[WS(csi, 59)];
          Tbh = SUB(T4J, T4K);
          T4u = ADD(T4s, T4t);
          TdS = ADD(Tbi, Tbh);
          T4L = ADD(T4J, T4K);
          Tbj = SUB(Tbh, Tbi);
        }
        {
          E T1I, T4w, T4z, Tbd, T1L, T4B, T4E, Tbc;
          {
            E T1G, T1H, T4x, T4y;
            T1G = Cr[WS(csr, 21)];
            T1H = Cr[WS(csr, 43)];
            T1I = ADD(T1G, T1H);
            T4w = SUB(T1G, T1H);
            T4x = Ci[WS(csi, 21)];
            T4y = Ci[WS(csi, 43)];
            T4z = ADD(T4x, T4y);
            Tbd = SUB(T4x, T4y);
          }
          {
            E T1J, T1K, T4C, T4D;
            T1J = Cr[WS(csr, 11)];
            T1K = Cr[WS(csr, 53)];
            T1L = ADD(T1J, T1K);
            T4B = SUB(T1J, T1K);
            T4C = Ci[WS(csi, 11)];
            T4D = Ci[WS(csi, 53)];
            T4E = ADD(T4C, T4D);
            Tbc = SUB(T4D, T4C);
          }
          T1M = ADD(T1I, T1L);
          Tbg = SUB(T1I, T1L);
          TdT = ADD(Tbd, Tbc);
          T4A = SUB(T4w, T4z);
          T4F = SUB(T4B, T4E);
          T4O = ADD(T4B, T4E);
          Tbe = SUB(Tbc, Tbd);
          T4N = ADD(T4w, T4z);
        }
        T1N = ADD(T1F, T1M);
        TeW = ADD(TdT, TdS);
        {
          E T4v, T4G, TdR, TdU;
          T4v = SUB(T4r, T4u);
          T4G = ADD(T4A, T4F);
          T4H = FMA(KP707106781, T4G, T4v);
          T6x = FNMS(KP707106781, T4G, T4v);
          TdR = SUB(T1F, T1M);
          TdU = SUB(TdS, TdT);
          TdV = SUB(TdR, TdU);
          Te8 = ADD(TdR, TdU);
        }
        {
          E T4M, T4P, T84, T85;
          T4M = ADD(T4I, T4L);
          T4P = SUB(T4N, T4O);
          T4Q = FMA(KP707106781, T4P, T4M);
          T6w = FNMS(KP707106781, T4P, T4M);
          T84 = SUB(T4L, T4I);
          T85 = SUB(T4F, T4A);
          T86 = FNMS(KP707106781, T85, T84);
          T9j = FMA(KP707106781, T85, T84);
        }
        TcG = SUB(Tbj, Tbg);
        TcH = SUB(Tbb, Tbe);
        TcI = FNMS(KP414213562, TcH, TcG);
        TcO = FMA(KP414213562, TcG, TcH);
        {
          E T81, T82, Tbf, Tbk;
          T81 = ADD(T4r, T4u);
          T82 = ADD(T4N, T4O);
          T83 = FNMS(KP707106781, T82, T81);
          T9k = FMA(KP707106781, T82, T81);
          Tbf = ADD(Tbb, Tbe);
          Tbk = ADD(Tbg, Tbj);
          Tbl = FNMS(KP414213562, Tbk, Tbf);
          TbI = FMA(KP414213562, Tbf, Tbk);
        }
      }
      {
        E T1U, Tbm, T4S, T59, T4V, TdX, T5c, Tbu, T21, Tbr, TdY, T51,
         T56, T5f, Tbp;
        E T5e, TcD, TcE;
        {
          E T1O, T1P, T1Q, T1R, T1S, T1T;
          T1O = Cr[WS(csr, 3)];
          T1P = Cr[WS(csr, 61)];
          T1Q = ADD(T1O, T1P);
          T1R = Cr[WS(csr, 29)];
          T1S = Cr[WS(csr, 35)];
          T1T = ADD(T1R, T1S);
          T1U = ADD(T1Q, T1T);
          Tbm = SUB(T1Q, T1T);
          T4S = SUB(T1O, T1P);
          T59 = SUB(T1R, T1S);
        }
        {
          E T4T, T4U, Tbt, T5a, T5b, Tbs;
          T4T = Ci[WS(csi, 29)];
          T4U = Ci[WS(csi, 35)];
          Tbt = SUB(T4T, T4U);
          T5a = Ci[WS(csi, 3)];
          T5b = Ci[WS(csi, 61)];
          Tbs = SUB(T5b, T5a);
          T4V = ADD(T4T, T4U);
          TdX = ADD(Tbt, Tbs);
          T5c = ADD(T5a, T5b);
          Tbu = SUB(Tbs, Tbt);
        }
        {
          E T1X, T4X, T50, Tbo, T20, T52, T55, Tbn;
          {
            E T1V, T1W, T4Y, T4Z;
            T1V = Cr[WS(csr, 13)];
            T1W = Cr[WS(csr, 51)];
            T1X = ADD(T1V, T1W);
            T4X = SUB(T1V, T1W);
            T4Y = Ci[WS(csi, 13)];
            T4Z = Ci[WS(csi, 51)];
            T50 = ADD(T4Y, T4Z);
            Tbo = SUB(T4Y, T4Z);
          }
          {
            E T1Y, T1Z, T53, T54;
            T1Y = Cr[WS(csr, 19)];
            T1Z = Cr[WS(csr, 45)];
            T20 = ADD(T1Y, T1Z);
            T52 = SUB(T1Y, T1Z);
            T53 = Ci[WS(csi, 19)];
            T54 = Ci[WS(csi, 45)];
            T55 = ADD(T53, T54);
            Tbn = SUB(T54, T53);
          }
          T21 = ADD(T1X, T20);
          Tbr = SUB(T1X, T20);
          TdY = ADD(Tbo, Tbn);
          T51 = SUB(T4X, T50);
          T56 = SUB(T52, T55);
          T5f = ADD(T52, T55);
          Tbp = SUB(Tbn, Tbo);
          T5e = ADD(T4X, T50);
        }
        T22 = ADD(T1U, T21);
        TeV = ADD(TdY, TdX);
        {
          E T4W, T57, TdW, TdZ;
          T4W = SUB(T4S, T4V);
          T57 = ADD(T51, T56);
          T58 = FMA(KP707106781, T57, T4W);
          T6u = FNMS(KP707106781, T57, T4W);
          TdW = SUB(T1U, T21);
          TdZ = SUB(TdX, TdY);
          Te0 = ADD(TdW, TdZ);
          Te9 = SUB(TdZ, TdW);
        }
        {
          E T5d, T5g, T8b, T8c;
          T5d = SUB(T59, T5c);
          T5g = SUB(T5e, T5f);
          T5h = FMA(KP707106781, T5g, T5d);
          T6t = FNMS(KP707106781, T5g, T5d);
          T8b = ADD(T59, T5c);
          T8c = SUB(T56, T51);
          T8d = FMA(KP707106781, T8c, T8b);
          T9m = FNMS(KP707106781, T8c, T8b);
        }
        TcD = SUB(Tbu, Tbr);
        TcE = SUB(Tbm, Tbp);
        TcF = FMA(KP414213562, TcE, TcD);
        TcP = FNMS(KP414213562, TcD, TcE);
        {
          E T88, T89, Tbq, Tbv;
          T88 = ADD(T4S, T4V);
          T89 = ADD(T5e, T5f);
          T8a = FNMS(KP707106781, T89, T88);
          T9n = FMA(KP707106781, T89, T88);
          Tbq = ADD(Tbm, Tbp);
          Tbv = ADD(Tbr, Tbu);
          Tbw = FMA(KP414213562, Tbv, Tbq);
          TbJ = FNMS(KP414213562, Tbq, Tbv);
        }
      }
      {
        E T1l, Tb0, T1o, Tb1, T47, T4c, Tb2, TaZ, T7U, T7T, T1s, Tb5,
         T1v, Tb6, T4i;
        E T4n, Tb7, Tb4, T7X, T7W;
        {
          E T43, T4b, T48, T46;
          {
            E T1j, T1k, T49, T4a;
            T1j = Cr[WS(csr, 9)];
            T1k = Cr[WS(csr, 55)];
            T1l = ADD(T1j, T1k);
            T43 = SUB(T1j, T1k);
            T49 = Ci[WS(csi, 9)];
            T4a = Ci[WS(csi, 55)];
            T4b = ADD(T49, T4a);
            Tb0 = SUB(T49, T4a);
          }
          {
            E T1m, T1n, T44, T45;
            T1m = Cr[WS(csr, 41)];
            T1n = Cr[WS(csr, 23)];
            T1o = ADD(T1m, T1n);
            T48 = SUB(T1m, T1n);
            T44 = Ci[WS(csi, 41)];
            T45 = Ci[WS(csi, 23)];
            T46 = ADD(T44, T45);
            Tb1 = SUB(T44, T45);
          }
          T47 = SUB(T43, T46);
          T4c = ADD(T48, T4b);
          Tb2 = SUB(Tb0, Tb1);
          TaZ = SUB(T1l, T1o);
          T7U = ADD(T43, T46);
          T7T = SUB(T4b, T48);
        }
        {
          E T4e, T4m, T4j, T4h;
          {
            E T1q, T1r, T4k, T4l;
            T1q = Cr[WS(csr, 7)];
            T1r = Cr[WS(csr, 57)];
            T1s = ADD(T1q, T1r);
            T4e = SUB(T1q, T1r);
            T4k = Ci[WS(csi, 7)];
            T4l = Ci[WS(csi, 57)];
            T4m = ADD(T4k, T4l);
            Tb5 = SUB(T4l, T4k);
          }
          {
            E T1t, T1u, T4f, T4g;
            T1t = Cr[WS(csr, 25)];
            T1u = Cr[WS(csr, 39)];
            T1v = ADD(T1t, T1u);
            T4j = SUB(T1t, T1u);
            T4f = Ci[WS(csi, 25)];
            T4g = Ci[WS(csi, 39)];
            T4h = ADD(T4f, T4g);
            Tb6 = SUB(T4f, T4g);
          }
          T4i = SUB(T4e, T4h);
          T4n = SUB(T4j, T4m);
          Tb7 = SUB(Tb5, Tb6);
          Tb4 = SUB(T1s, T1v);
          T7X = ADD(T4e, T4h);
          T7W = ADD(T4j, T4m);
        }
        {
          E T1p, T1w, TbE, TbF;
          T1p = ADD(T1l, T1o);
          T1w = ADD(T1s, T1v);
          T1x = ADD(T1p, T1w);
          Te3 = SUB(T1p, T1w);
          TbE = ADD(TaZ, Tb2);
          TbF = SUB(Tb7, Tb4);
          TbG = ADD(TbE, TbF);
          TcB = SUB(TbE, TbF);
        }
        {
          E TdN, TdO, T4d, T4o;
          TdN = ADD(Tb6, Tb5);
          TdO = ADD(Tb1, Tb0);
          TdP = SUB(TdN, TdO);
          Tf1 = ADD(TdO, TdN);
          T4d = FNMS(KP414213562, T4c, T47);
          T4o = FMA(KP414213562, T4n, T4i);
          T4p = ADD(T4d, T4o);
          T6C = SUB(T4o, T4d);
        }
        {
          E T5u, T5v, T8k, T8l;
          T5u = FMA(KP414213562, T47, T4c);
          T5v = FNMS(KP414213562, T4i, T4n);
          T5w = ADD(T5u, T5v);
          T6r = SUB(T5u, T5v);
          T8k = FMA(KP414213562, T7T, T7U);
          T8l = FMA(KP414213562, T7W, T7X);
          T8m = SUB(T8k, T8l);
          T9h = ADD(T8k, T8l);
        }
        {
          E Tb3, Tb8, T7V, T7Y;
          Tb3 = SUB(TaZ, Tb2);
          Tb8 = ADD(Tb4, Tb7);
          Tb9 = ADD(Tb3, Tb8);
          TcM = SUB(Tb8, Tb3);
          T7V = FNMS(KP414213562, T7U, T7T);
          T7Y = FNMS(KP414213562, T7X, T7W);
          T7Z = ADD(T7V, T7Y);
          T9s = SUB(T7V, T7Y);
        }
      }
      {
        E TP, Tay, TS, Taz, T3d, T3i, TaA, Tax, T7A, T7z, TW, TaD, TZ,
         TaE, T3o;
        E T3t, TaF, TaC, T7D, T7C;
        {
          E T39, T3h, T3e, T3c;
          {
            E TN, TO, T3f, T3g;
            TN = Cr[WS(csr, 10)];
            TO = Cr[WS(csr, 54)];
            TP = ADD(TN, TO);
            T39 = SUB(TN, TO);
            T3f = Ci[WS(csi, 10)];
            T3g = Ci[WS(csi, 54)];
            T3h = ADD(T3f, T3g);
            Tay = SUB(T3f, T3g);
          }
          {
            E TQ, TR, T3a, T3b;
            TQ = Cr[WS(csr, 42)];
            TR = Cr[WS(csr, 22)];
            TS = ADD(TQ, TR);
            T3e = SUB(TQ, TR);
            T3a = Ci[WS(csi, 42)];
            T3b = Ci[WS(csi, 22)];
            T3c = ADD(T3a, T3b);
            Taz = SUB(T3a, T3b);
          }
          T3d = SUB(T39, T3c);
          T3i = ADD(T3e, T3h);
          TaA = SUB(Tay, Taz);
          Tax = SUB(TP, TS);
          T7A = ADD(T39, T3c);
          T7z = SUB(T3h, T3e);
        }
        {
          E T3k, T3s, T3p, T3n;
          {
            E TU, TV, T3q, T3r;
            TU = Cr[WS(csr, 6)];
            TV = Cr[WS(csr, 58)];
            TW = ADD(TU, TV);
            T3k = SUB(TU, TV);
            T3q = Ci[WS(csi, 6)];
            T3r = Ci[WS(csi, 58)];
            T3s = ADD(T3q, T3r);
            TaD = SUB(T3r, T3q);
          }
          {
            E TX, TY, T3l, T3m;
            TX = Cr[WS(csr, 26)];
            TY = Cr[WS(csr, 38)];
            TZ = ADD(TX, TY);
            T3p = SUB(TX, TY);
            T3l = Ci[WS(csi, 26)];
            T3m = Ci[WS(csi, 38)];
            T3n = ADD(T3l, T3m);
            TaE = SUB(T3l, T3m);
          }
          T3o = SUB(T3k, T3n);
          T3t = SUB(T3p, T3s);
          TaF = SUB(TaD, TaE);
          TaC = SUB(TW, TZ);
          T7D = ADD(T3k, T3n);
          T7C = ADD(T3p, T3s);
        }
        {
          E TT, T10, TaO, TaP;
          TT = ADD(TP, TS);
          T10 = ADD(TW, TZ);
          T11 = ADD(TT, T10);
          TdF = SUB(TT, T10);
          TaO = ADD(Tax, TaA);
          TaP = SUB(TaF, TaC);
          TaQ = ADD(TaO, TaP);
          Tct = SUB(TaO, TaP);
        }
        {
          E TdB, TdC, T3j, T3u;
          TdB = ADD(TaE, TaD);
          TdC = ADD(Taz, Tay);
          TdD = SUB(TdB, TdC);
          TeQ = ADD(TdC, TdB);
          T3j = FNMS(KP414213562, T3i, T3d);
          T3u = FMA(KP414213562, T3t, T3o);
          T3v = ADD(T3j, T3u);
          T6m = SUB(T3u, T3j);
        }
        {
          E T3G, T3H, T7K, T7L;
          T3G = FMA(KP414213562, T3d, T3i);
          T3H = FNMS(KP414213562, T3o, T3t);
          T3I = ADD(T3G, T3H);
          T6j = SUB(T3G, T3H);
          T7K = FMA(KP414213562, T7z, T7A);
          T7L = FMA(KP414213562, T7C, T7D);
          T7M = SUB(T7K, T7L);
          T99 = ADD(T7K, T7L);
        }
        {
          E TaB, TaG, T7B, T7E;
          TaB = SUB(Tax, TaA);
          TaG = ADD(TaC, TaF);
          TaH = ADD(TaB, TaG);
          Tcw = SUB(TaG, TaB);
          T7B = FNMS(KP414213562, T7A, T7z);
          T7E = FNMS(KP414213562, T7D, T7C);
          T7F = ADD(T7B, T7E);
          T9c = SUB(T7B, T7E);
        }
      }
      {
        E T12, Tfg, Tx, Tff, T24, Tfi, Tfl, Tfq, Th, T13, Tfp;
        T12 = ADD(TM, T11);
        Tfg = ADD(TeQ, TeP);
        Th = FMA(KP2_000000000, Tg, T9);
        Tx = FMA(KP2_000000000, Tw, Th);
        Tff = FNMS(KP2_000000000, Tw, Th);
        {
          E T1y, T23, Tfj, Tfk;
          T1y = ADD(T1i, T1x);
          T23 = ADD(T1N, T22);
          T24 = ADD(T1y, T23);
          Tfi = SUB(T1y, T23);
          Tfj = ADD(Tf1, Tf0);
          Tfk = ADD(TeW, TeV);
          Tfl = SUB(Tfj, Tfk);
          Tfq = ADD(Tfk, Tfj);
        }
        T13 = FMA(KP2_000000000, T12, Tx);
        R0[WS(rs, 32)] = FNMS(KP2_000000000, T24, T13);
        R0[0] = FMA(KP2_000000000, T24, T13);
        Tfp = FNMS(KP2_000000000, T12, Tx);
        R0[WS(rs, 16)] = FNMS(KP2_000000000, Tfq, Tfp);
        R0[WS(rs, 48)] = FMA(KP2_000000000, Tfq, Tfp);
        {
          E Tfh, Tfm, Tfn, Tfo;
          Tfh = FNMS(KP2_000000000, Tfg, Tff);
          Tfm = SUB(Tfi, Tfl);
          R0[WS(rs, 40)] = FNMS(KP1_414213562, Tfm, Tfh);
          R0[WS(rs, 8)] = FMA(KP1_414213562, Tfm, Tfh);
          Tfn = FMA(KP2_000000000, Tfg, Tff);
          Tfo = ADD(Tfi, Tfl);
          R0[WS(rs, 24)] = FNMS(KP1_414213562, Tfo, Tfn);
          R0[WS(rs, 56)] = FMA(KP1_414213562, Tfo, Tfn);
        }
      }
      {
        E TeN, Tf7, Tf3, Tfa, TeS, Tf8, TeY, Tfb, TeL, TeZ, Tf2;
        TeL = FNMS(KP2_000000000, Tg, T9);
        TeN = FNMS(KP2_000000000, TeM, TeL);
        Tf7 = FMA(KP2_000000000, TeM, TeL);
        TeZ = SUB(T1N, T22);
        Tf2 = SUB(Tf0, Tf1);
        Tf3 = ADD(TeZ, Tf2);
        Tfa = SUB(Tf2, TeZ);
        {
          E TeO, TeR, TeU, TeX;
          TeO = SUB(TM, T11);
          TeR = SUB(TeP, TeQ);
          TeS = SUB(TeO, TeR);
          Tf8 = ADD(TeO, TeR);
          TeU = SUB(T1i, T1x);
          TeX = SUB(TeV, TeW);
          TeY = ADD(TeU, TeX);
          Tfb = SUB(TeU, TeX);
        }
        {
          E TeT, Tf4, Tfd, Tfe;
          TeT = FMA(KP1_414213562, TeS, TeN);
          Tf4 = FNMS(KP414213562, Tf3, TeY);
          R0[WS(rs, 36)] = FNMS(KP1_847759065, Tf4, TeT);
          R0[WS(rs, 4)] = FMA(KP1_847759065, Tf4, TeT);
          Tfd = FMA(KP1_414213562, Tf8, Tf7);
          Tfe = FMA(KP414213562, Tfa, Tfb);
          R0[WS(rs, 28)] = FNMS(KP1_847759065, Tfe, Tfd);
          R0[WS(rs, 60)] = FMA(KP1_847759065, Tfe, Tfd);
        }
        {
          E Tf5, Tf6, Tf9, Tfc;
          Tf5 = FNMS(KP1_414213562, TeS, TeN);
          Tf6 = FMA(KP414213562, TeY, Tf3);
          R0[WS(rs, 20)] = FNMS(KP1_847759065, Tf6, Tf5);
          R0[WS(rs, 52)] = FMA(KP1_847759065, Tf6, Tf5);
          Tf9 = FNMS(KP1_414213562, Tf8, Tf7);
          Tfc = FNMS(KP414213562, Tfb, Tfa);
          R0[WS(rs, 12)] = FNMS(KP1_847759065, Tfc, Tf9);
          R0[WS(rs, 44)] = FMA(KP1_847759065, Tfc, Tf9);
        }
      }
      {
        E Tar, TbP, TbL, TbS, TaS, TbQ, Tby, TbT;
        {
          E Taf, Taq, TbH, TbK;
          Taf = FMA(KP1_414213562, Tae, Ta9);
          Taq = FNMS(KP414213562, Tap, Tak);
          Tar = FMA(KP1_847759065, Taq, Taf);
          TbP = FNMS(KP1_847759065, Taq, Taf);
          TbH = FMA(KP707106781, TbG, TbD);
          TbK = ADD(TbI, TbJ);
          TbL = FMA(KP923879532, TbK, TbH);
          TbS = FNMS(KP923879532, TbK, TbH);
        }
        {
          E TaI, TaR, Tba, Tbx;
          TaI = FMA(KP707106781, TaH, Taw);
          TaR = FMA(KP707106781, TaQ, TaN);
          TaS = FNMS(KP198912367, TaR, TaI);
          TbQ = FMA(KP198912367, TaI, TaR);
          Tba = FMA(KP707106781, Tb9, TaY);
          Tbx = ADD(Tbl, Tbw);
          Tby = FMA(KP923879532, Tbx, Tba);
          TbT = FNMS(KP923879532, Tbx, Tba);
        }
        {
          E TaT, TbM, TbV, TbW;
          TaT = FMA(KP1_961570560, TaS, Tar);
          TbM = FNMS(KP098491403, TbL, Tby);
          R0[WS(rs, 33)] = FNMS(KP1_990369453, TbM, TaT);
          R0[WS(rs, 1)] = FMA(KP1_990369453, TbM, TaT);
          TbV = FMA(KP1_961570560, TbQ, TbP);
          TbW = FMA(KP820678790, TbS, TbT);
          R0[WS(rs, 25)] = FNMS(KP1_546020906, TbW, TbV);
          R0[WS(rs, 57)] = FMA(KP1_546020906, TbW, TbV);
        }
        {
          E TbN, TbO, TbR, TbU;
          TbN = FNMS(KP1_961570560, TaS, Tar);
          TbO = FMA(KP098491403, Tby, TbL);
          R0[WS(rs, 17)] = FNMS(KP1_990369453, TbO, TbN);
          R0[WS(rs, 49)] = FMA(KP1_990369453, TbO, TbN);
          TbR = FNMS(KP1_961570560, TbQ, TbP);
          TbU = FNMS(KP820678790, TbT, TbS);
          R0[WS(rs, 9)] = FNMS(KP1_546020906, TbU, TbR);
          R0[WS(rs, 41)] = FMA(KP1_546020906, TbU, TbR);
        }
      }
      {
        E Tdz, Tef, Teb, Tei, TdK, Teg, Te2, Tej;
        {
          E Tdt, Tdy, Te7, Tea;
          Tdt = FNMS(KP2_000000000, Tds, Tdr);
          Tdy = SUB(Tdu, Tdx);
          Tdz = FMA(KP1_414213562, Tdy, Tdt);
          Tef = FNMS(KP1_414213562, Tdy, Tdt);
          Te7 = ADD(Te3, Te6);
          Tea = ADD(Te8, Te9);
          Teb = FMA(KP707106781, Tea, Te7);
          Tei = FNMS(KP707106781, Tea, Te7);
        }
        {
          E TdE, TdJ, TdQ, Te1;
          TdE = ADD(TdA, TdD);
          TdJ = ADD(TdF, TdI);
          TdK = FNMS(KP414213562, TdJ, TdE);
          Teg = FMA(KP414213562, TdE, TdJ);
          TdQ = ADD(TdM, TdP);
          Te1 = ADD(TdV, Te0);
          Te2 = FMA(KP707106781, Te1, TdQ);
          Tej = FNMS(KP707106781, Te1, TdQ);
        }
        {
          E TdL, Tec, Tel, Tem;
          TdL = FMA(KP1_847759065, TdK, Tdz);
          Tec = FNMS(KP198912367, Teb, Te2);
          R0[WS(rs, 34)] = FNMS(KP1_961570560, Tec, TdL);
          R0[WS(rs, 2)] = FMA(KP1_961570560, Tec, TdL);
          Tel = FMA(KP1_847759065, Teg, Tef);
          Tem = FMA(KP668178637, Tei, Tej);
          R0[WS(rs, 26)] = FNMS(KP1_662939224, Tem, Tel);
          R0[WS(rs, 58)] = FMA(KP1_662939224, Tem, Tel);
        }
        {
          E Ted, Tee, Teh, Tek;
          Ted = FNMS(KP1_847759065, TdK, Tdz);
          Tee = FMA(KP198912367, Te2, Teb);
          R0[WS(rs, 18)] = FNMS(KP1_961570560, Tee, Ted);
          R0[WS(rs, 50)] = FMA(KP1_961570560, Tee, Ted);
          Teh = FNMS(KP1_847759065, Teg, Tef);
          Tek = FNMS(KP668178637, Tej, Tei);
          R0[WS(rs, 10)] = FNMS(KP1_662939224, Tek, Teh);
          R0[WS(rs, 42)] = FMA(KP1_662939224, Tek, Teh);
        }
      }
      {
        E TbZ, Tcd, Tc9, Tcg, Tc2, Tce, Tc6, Tch;
        {
          E TbX, TbY, Tc7, Tc8;
          TbX = FNMS(KP1_414213562, Tae, Ta9);
          TbY = FMA(KP414213562, Tak, Tap);
          TbZ = FNMS(KP1_847759065, TbY, TbX);
          Tcd = FMA(KP1_847759065, TbY, TbX);
          Tc7 = FNMS(KP707106781, TbG, TbD);
          Tc8 = SUB(Tbw, Tbl);
          Tc9 = FNMS(KP923879532, Tc8, Tc7);
          Tcg = FMA(KP923879532, Tc8, Tc7);
        }
        {
          E Tc0, Tc1, Tc4, Tc5;
          Tc0 = FNMS(KP707106781, TaQ, TaN);
          Tc1 = FNMS(KP707106781, TaH, Taw);
          Tc2 = FNMS(KP668178637, Tc1, Tc0);
          Tce = FMA(KP668178637, Tc0, Tc1);
          Tc4 = FNMS(KP707106781, Tb9, TaY);
          Tc5 = SUB(TbI, TbJ);
          Tc6 = FNMS(KP923879532, Tc5, Tc4);
          Tch = FMA(KP923879532, Tc5, Tc4);
        }
        {
          E Tc3, Tca, Tcj, Tck;
          Tc3 = FNMS(KP1_662939224, Tc2, TbZ);
          Tca = FNMS(KP534511135, Tc9, Tc6);
          R0[WS(rs, 37)] = FNMS(KP1_763842528, Tca, Tc3);
          R0[WS(rs, 5)] = FMA(KP1_763842528, Tca, Tc3);
          Tcj = FMA(KP1_662939224, Tce, Tcd);
          Tck = FMA(KP303346683, Tcg, Tch);
          R0[WS(rs, 29)] = FNMS(KP1_913880671, Tck, Tcj);
          R0[WS(rs, 61)] = FMA(KP1_913880671, Tck, Tcj);
        }
        {
          E Tcb, Tcc, Tcf, Tci;
          Tcb = FMA(KP1_662939224, Tc2, TbZ);
          Tcc = FMA(KP534511135, Tc6, Tc9);
          R0[WS(rs, 21)] = FNMS(KP1_763842528, Tcc, Tcb);
          R0[WS(rs, 53)] = FMA(KP1_763842528, Tcc, Tcb);
          Tcf = FNMS(KP1_662939224, Tce, Tcd);
          Tci = FNMS(KP303346683, Tch, Tcg);
          R0[WS(rs, 13)] = FNMS(KP1_913880671, Tci, Tcf);
          R0[WS(rs, 45)] = FMA(KP1_913880671, Tci, Tcf);
        }
      }
      {
        E Tep, TeD, Tez, TeG, Tes, TeE, Tew, TeH;
        {
          E Ten, Teo, Tex, Tey;
          Ten = FMA(KP2_000000000, Tds, Tdr);
          Teo = ADD(Tdu, Tdx);
          Tep = FNMS(KP1_414213562, Teo, Ten);
          TeD = FMA(KP1_414213562, Teo, Ten);
          Tex = SUB(Te6, Te3);
          Tey = SUB(Te0, TdV);
          Tez = FNMS(KP707106781, Tey, Tex);
          TeG = FMA(KP707106781, Tey, Tex);
        }
        {
          E Teq, Ter, Teu, Tev;
          Teq = SUB(TdI, TdF);
          Ter = SUB(TdA, TdD);
          Tes = FNMS(KP414213562, Ter, Teq);
          TeE = FMA(KP414213562, Teq, Ter);
          Teu = SUB(TdM, TdP);
          Tev = SUB(Te8, Te9);
          Tew = FNMS(KP707106781, Tev, Teu);
          TeH = FMA(KP707106781, Tev, Teu);
        }
        {
          E Tet, TeA, TeJ, TeK;
          Tet = FNMS(KP1_847759065, Tes, Tep);
          TeA = FNMS(KP668178637, Tez, Tew);
          R0[WS(rs, 38)] = FNMS(KP1_662939224, TeA, Tet);
          R0[WS(rs, 6)] = FMA(KP1_662939224, TeA, Tet);
          TeJ = FMA(KP1_847759065, TeE, TeD);
          TeK = FMA(KP198912367, TeG, TeH);
          R0[WS(rs, 30)] = FNMS(KP1_961570560, TeK, TeJ);
          R0[WS(rs, 62)] = FMA(KP1_961570560, TeK, TeJ);
        }
        {
          E TeB, TeC, TeF, TeI;
          TeB = FMA(KP1_847759065, Tes, Tep);
          TeC = FMA(KP668178637, Tew, Tez);
          R0[WS(rs, 22)] = FNMS(KP1_662939224, TeC, TeB);
          R0[WS(rs, 54)] = FMA(KP1_662939224, TeC, TeB);
          TeF = FNMS(KP1_847759065, TeE, TeD);
          TeI = FNMS(KP198912367, TeH, TeG);
          R0[WS(rs, 14)] = FNMS(KP1_961570560, TeI, TeF);
          R0[WS(rs, 46)] = FMA(KP1_961570560, TeI, TeF);
        }
      }
      {
        E Tcr, TcV, TcR, TcY, Tcy, TcW, TcK, TcZ;
        {
          E Tcn, Tcq, TcN, TcQ;
          Tcn = FNMS(KP1_414213562, Tcm, Tcl);
          Tcq = FNMS(KP414213562, Tcp, Tco);
          Tcr = FNMS(KP1_847759065, Tcq, Tcn);
          TcV = FMA(KP1_847759065, Tcq, Tcn);
          TcN = FNMS(KP707106781, TcM, TcL);
          TcQ = SUB(TcO, TcP);
          TcR = FMA(KP923879532, TcQ, TcN);
          TcY = FNMS(KP923879532, TcQ, TcN);
        }
        {
          E Tcu, Tcx, TcC, TcJ;
          Tcu = FNMS(KP707106781, Tct, Tcs);
          Tcx = FNMS(KP707106781, Tcw, Tcv);
          Tcy = FNMS(KP668178637, Tcx, Tcu);
          TcW = FMA(KP668178637, Tcu, Tcx);
          TcC = FNMS(KP707106781, TcB, TcA);
          TcJ = SUB(TcF, TcI);
          TcK = FMA(KP923879532, TcJ, TcC);
          TcZ = FNMS(KP923879532, TcJ, TcC);
        }
        {
          E Tcz, TcS, Td1, Td2;
          Tcz = FMA(KP1_662939224, Tcy, Tcr);
          TcS = FNMS(KP303346683, TcR, TcK);
          R0[WS(rs, 35)] = FNMS(KP1_913880671, TcS, Tcz);
          R0[WS(rs, 3)] = FMA(KP1_913880671, TcS, Tcz);
          Td1 = FMA(KP1_662939224, TcW, TcV);
          Td2 = FMA(KP534511135, TcY, TcZ);
          R0[WS(rs, 27)] = FNMS(KP1_763842528, Td2, Td1);
          R0[WS(rs, 59)] = FMA(KP1_763842528, Td2, Td1);
        }
        {
          E TcT, TcU, TcX, Td0;
          TcT = FNMS(KP1_662939224, Tcy, Tcr);
          TcU = FMA(KP303346683, TcK, TcR);
          R0[WS(rs, 19)] = FNMS(KP1_913880671, TcU, TcT);
          R0[WS(rs, 51)] = FMA(KP1_913880671, TcU, TcT);
          TcX = FNMS(KP1_662939224, TcW, TcV);
          Td0 = FNMS(KP534511135, TcZ, TcY);
          R0[WS(rs, 11)] = FNMS(KP1_763842528, Td0, TcX);
          R0[WS(rs, 43)] = FMA(KP1_763842528, Td0, TcX);
        }
      }
      {
        E Td5, Tdj, Tdf, Tdm, Td8, Tdk, Tdc, Tdn;
        {
          E Td3, Td4, Tdd, Tde;
          Td3 = FMA(KP1_414213562, Tcm, Tcl);
          Td4 = FMA(KP414213562, Tco, Tcp);
          Td5 = FNMS(KP1_847759065, Td4, Td3);
          Tdj = FMA(KP1_847759065, Td4, Td3);
          Tdd = FMA(KP707106781, TcM, TcL);
          Tde = ADD(TcI, TcF);
          Tdf = FNMS(KP923879532, Tde, Tdd);
          Tdm = FMA(KP923879532, Tde, Tdd);
        }
        {
          E Td6, Td7, Tda, Tdb;
          Td6 = FMA(KP707106781, Tcw, Tcv);
          Td7 = FMA(KP707106781, Tct, Tcs);
          Td8 = FNMS(KP198912367, Td7, Td6);
          Tdk = FMA(KP198912367, Td6, Td7);
          Tda = FMA(KP707106781, TcB, TcA);
          Tdb = ADD(TcO, TcP);
          Tdc = FNMS(KP923879532, Tdb, Tda);
          Tdn = FMA(KP923879532, Tdb, Tda);
        }
        {
          E Td9, Tdg, Tdp, Tdq;
          Td9 = FNMS(KP1_961570560, Td8, Td5);
          Tdg = FNMS(KP820678790, Tdf, Tdc);
          R0[WS(rs, 39)] = FNMS(KP1_546020906, Tdg, Td9);
          R0[WS(rs, 7)] = FMA(KP1_546020906, Tdg, Td9);
          Tdp = FMA(KP1_961570560, Tdk, Tdj);
          Tdq = FMA(KP098491403, Tdm, Tdn);
          R0[WS(rs, 31)] = FNMS(KP1_990369453, Tdq, Tdp);
          R0[WS(rs, 63)] = FMA(KP1_990369453, Tdq, Tdp);
        }
        {
          E Tdh, Tdi, Tdl, Tdo;
          Tdh = FMA(KP1_961570560, Td8, Td5);
          Tdi = FMA(KP820678790, Tdc, Tdf);
          R0[WS(rs, 23)] = FNMS(KP1_546020906, Tdi, Tdh);
          R0[WS(rs, 55)] = FMA(KP1_546020906, Tdi, Tdh);
          Tdl = FNMS(KP1_961570560, Tdk, Tdj);
          Tdo = FNMS(KP098491403, Tdn, Tdm);
          R0[WS(rs, 15)] = FNMS(KP1_990369453, Tdo, Tdl);
          R0[WS(rs, 47)] = FMA(KP1_990369453, Tdo, Tdl);
        }
      }
      {
        E T2R, T5F, T3K, T5G, T5S, T64, T5P, T63, T5B, T67, T5I, T5W,
         T5k, T66, T5J;
        E T5Z;
        {
          E T2p, T2Q, T5N, T5O;
          T2p = FMA(KP1_847759065, T2o, T2d);
          T2Q = FNMS(KP198912367, T2P, T2G);
          T2R = FMA(KP1_961570560, T2Q, T2p);
          T5F = FNMS(KP1_961570560, T2Q, T2p);
          {
            E T3w, T3J, T5Q, T5R;
            T3w = FMA(KP923879532, T3v, T38);
            T3J = FMA(KP923879532, T3I, T3F);
            T3K = FNMS(KP098491403, T3J, T3w);
            T5G = FMA(KP098491403, T3w, T3J);
            T5Q = FNMS(KP923879532, T3I, T3F);
            T5R = FNMS(KP923879532, T3v, T38);
            T5S = FNMS(KP820678790, T5R, T5Q);
            T64 = FMA(KP820678790, T5Q, T5R);
          }
          T5N = FNMS(KP1_847759065, T2o, T2d);
          T5O = FMA(KP198912367, T2G, T2P);
          T5P = FNMS(KP1_961570560, T5O, T5N);
          T63 = FMA(KP1_961570560, T5O, T5N);
          {
            E T5x, T5U, T5A, T5V, T5y, T5z;
            T5x = FMA(KP923879532, T5w, T5t);
            T5U = FNMS(KP923879532, T4p, T42);
            T5y = FMA(KP198912367, T4H, T4Q);
            T5z = FNMS(KP198912367, T58, T5h);
            T5A = ADD(T5y, T5z);
            T5V = SUB(T5y, T5z);
            T5B = FMA(KP980785280, T5A, T5x);
            T67 = FMA(KP980785280, T5V, T5U);
            T5I = FNMS(KP980785280, T5A, T5x);
            T5W = FNMS(KP980785280, T5V, T5U);
          }
          {
            E T4q, T5X, T5j, T5Y, T4R, T5i;
            T4q = FMA(KP923879532, T4p, T42);
            T5X = FNMS(KP923879532, T5w, T5t);
            T4R = FNMS(KP198912367, T4Q, T4H);
            T5i = FMA(KP198912367, T5h, T58);
            T5j = ADD(T4R, T5i);
            T5Y = SUB(T5i, T4R);
            T5k = FMA(KP980785280, T5j, T4q);
            T66 = FMA(KP980785280, T5Y, T5X);
            T5J = FNMS(KP980785280, T5j, T4q);
            T5Z = FNMS(KP980785280, T5Y, T5X);
          }
        }
        {
          E T3L, T5C, T65, T68;
          T3L = FMA(KP1_990369453, T3K, T2R);
          T5C = FNMS(KP049126849, T5B, T5k);
          R1[WS(rs, 32)] = FNMS(KP1_997590912, T5C, T3L);
          R1[0] = FMA(KP1_997590912, T5C, T3L);
          T65 = FNMS(KP1_546020906, T64, T63);
          T68 = FNMS(KP357805721, T67, T66);
          R1[WS(rs, 12)] = FNMS(KP1_883088130, T68, T65);
          R1[WS(rs, 44)] = FMA(KP1_883088130, T68, T65);
        }
        {
          E T69, T6a, T5D, T5E;
          T69 = FMA(KP1_546020906, T64, T63);
          T6a = FMA(KP357805721, T66, T67);
          R1[WS(rs, 28)] = FNMS(KP1_883088130, T6a, T69);
          R1[WS(rs, 60)] = FMA(KP1_883088130, T6a, T69);
          T5D = FNMS(KP1_990369453, T3K, T2R);
          T5E = FMA(KP049126849, T5k, T5B);
          R1[WS(rs, 16)] = FNMS(KP1_997590912, T5E, T5D);
          R1[WS(rs, 48)] = FMA(KP1_997590912, T5E, T5D);
        }
        {
          E T5H, T5K, T5T, T60;
          T5H = FNMS(KP1_990369453, T5G, T5F);
          T5K = FNMS(KP906347169, T5J, T5I);
          R1[WS(rs, 8)] = FNMS(KP1_481902250, T5K, T5H);
          R1[WS(rs, 40)] = FMA(KP1_481902250, T5K, T5H);
          T5T = FNMS(KP1_546020906, T5S, T5P);
          T60 = FNMS(KP472964775, T5Z, T5W);
          R1[WS(rs, 36)] = FNMS(KP1_807978586, T60, T5T);
          R1[WS(rs, 4)] = FMA(KP1_807978586, T60, T5T);
        }
        {
          E T61, T62, T5L, T5M;
          T61 = FMA(KP1_546020906, T5S, T5P);
          T62 = FMA(KP472964775, T5W, T5Z);
          R1[WS(rs, 20)] = FNMS(KP1_807978586, T62, T61);
          R1[WS(rs, 52)] = FMA(KP1_807978586, T62, T61);
          T5L = FMA(KP1_990369453, T5G, T5F);
          T5M = FMA(KP906347169, T5I, T5J);
          R1[WS(rs, 24)] = FNMS(KP1_481902250, T5M, T5L);
          R1[WS(rs, 56)] = FMA(KP1_481902250, T5M, T5L);
        }
      }
      {
        E T7v, T8v, T7O, T8w, T8I, T8U, T8F, T8T, T8r, T8X, T8y, T8M,
         T8g, T8W, T8z;
        E T8P;
        {
          E T7n, T7u, T8D, T8E;
          T7n = FNMS(KP1_847759065, T7m, T7j);
          T7u = FNMS(KP668178637, T7t, T7q);
          T7v = FMA(KP1_662939224, T7u, T7n);
          T8v = FNMS(KP1_662939224, T7u, T7n);
          {
            E T7G, T7N, T8G, T8H;
            T7G = FNMS(KP923879532, T7F, T7y);
            T7N = FMA(KP923879532, T7M, T7J);
            T7O = FNMS(KP303346683, T7N, T7G);
            T8w = FMA(KP303346683, T7G, T7N);
            T8G = FNMS(KP923879532, T7M, T7J);
            T8H = FMA(KP923879532, T7F, T7y);
            T8I = FNMS(KP534511135, T8H, T8G);
            T8U = FMA(KP534511135, T8G, T8H);
          }
          T8D = FMA(KP1_847759065, T7m, T7j);
          T8E = FMA(KP668178637, T7q, T7t);
          T8F = FNMS(KP1_662939224, T8E, T8D);
          T8T = FMA(KP1_662939224, T8E, T8D);
          {
            E T8n, T8K, T8q, T8L, T8o, T8p;
            T8n = FMA(KP923879532, T8m, T8j);
            T8K = FMA(KP923879532, T7Z, T7S);
            T8o = FMA(KP668178637, T83, T86);
            T8p = FMA(KP668178637, T8a, T8d);
            T8q = SUB(T8o, T8p);
            T8L = ADD(T8o, T8p);
            T8r = FMA(KP831469612, T8q, T8n);
            T8X = FMA(KP831469612, T8L, T8K);
            T8y = FNMS(KP831469612, T8q, T8n);
            T8M = FNMS(KP831469612, T8L, T8K);
          }
          {
            E T80, T8N, T8f, T8O, T87, T8e;
            T80 = FNMS(KP923879532, T7Z, T7S);
            T8N = FNMS(KP923879532, T8m, T8j);
            T87 = FNMS(KP668178637, T86, T83);
            T8e = FNMS(KP668178637, T8d, T8a);
            T8f = ADD(T87, T8e);
            T8O = SUB(T8e, T87);
            T8g = FMA(KP831469612, T8f, T80);
            T8W = FMA(KP831469612, T8O, T8N);
            T8z = FNMS(KP831469612, T8f, T80);
            T8P = FNMS(KP831469612, T8O, T8N);
          }
        }
        {
          E T7P, T8s, T8V, T8Y;
          T7P = FMA(KP1_913880671, T7O, T7v);
          T8s = FNMS(KP148335987, T8r, T8g);
          R1[WS(rs, 33)] = FNMS(KP1_978353019, T8s, T7P);
          R1[WS(rs, 1)] = FMA(KP1_978353019, T8s, T7P);
          T8V = FNMS(KP1_763842528, T8U, T8T);
          T8Y = FNMS(KP250486960, T8X, T8W);
          R1[WS(rs, 13)] = FNMS(KP1_940062506, T8Y, T8V);
          R1[WS(rs, 45)] = FMA(KP1_940062506, T8Y, T8V);
        }
        {
          E T8Z, T90, T8t, T8u;
          T8Z = FMA(KP1_763842528, T8U, T8T);
          T90 = FMA(KP250486960, T8W, T8X);
          R1[WS(rs, 29)] = FNMS(KP1_940062506, T90, T8Z);
          R1[WS(rs, 61)] = FMA(KP1_940062506, T90, T8Z);
          T8t = FNMS(KP1_913880671, T7O, T7v);
          T8u = FMA(KP148335987, T8g, T8r);
          R1[WS(rs, 17)] = FNMS(KP1_978353019, T8u, T8t);
          R1[WS(rs, 49)] = FMA(KP1_978353019, T8u, T8t);
        }
        {
          E T8x, T8A, T8J, T8Q;
          T8x = FNMS(KP1_913880671, T8w, T8v);
          T8A = FNMS(KP741650546, T8z, T8y);
          R1[WS(rs, 9)] = FNMS(KP1_606415062, T8A, T8x);
          R1[WS(rs, 41)] = FMA(KP1_606415062, T8A, T8x);
          T8J = FNMS(KP1_763842528, T8I, T8F);
          T8Q = FNMS(KP599376933, T8P, T8M);
          R1[WS(rs, 37)] = FNMS(KP1_715457220, T8Q, T8J);
          R1[WS(rs, 5)] = FMA(KP1_715457220, T8Q, T8J);
        }
        {
          E T8R, T8S, T8B, T8C;
          T8R = FMA(KP1_763842528, T8I, T8F);
          T8S = FMA(KP599376933, T8M, T8P);
          R1[WS(rs, 21)] = FNMS(KP1_715457220, T8S, T8R);
          R1[WS(rs, 53)] = FMA(KP1_715457220, T8S, T8R);
          T8B = FMA(KP1_913880671, T8w, T8v);
          T8C = FMA(KP741650546, T8y, T8z);
          R1[WS(rs, 25)] = FNMS(KP1_606415062, T8C, T8B);
          R1[WS(rs, 57)] = FMA(KP1_606415062, T8C, T8B);
        }
      }
      {
        E T6h, T6L, T6o, T6M, T6Y, T7a, T6V, T79, T6H, T7d, T6O, T72,
         T6A, T7c, T6P;
        E T75;
        {
          E T6d, T6g, T6T, T6U;
          T6d = FNMS(KP1_847759065, T6c, T6b);
          T6g = FNMS(KP668178637, T6f, T6e);
          T6h = FNMS(KP1_662939224, T6g, T6d);
          T6L = FMA(KP1_662939224, T6g, T6d);
          {
            E T6k, T6n, T6W, T6X;
            T6k = FNMS(KP923879532, T6j, T6i);
            T6n = FNMS(KP923879532, T6m, T6l);
            T6o = FNMS(KP534511135, T6n, T6k);
            T6M = FMA(KP534511135, T6k, T6n);
            T6W = FMA(KP923879532, T6m, T6l);
            T6X = FMA(KP923879532, T6j, T6i);
            T6Y = FNMS(KP303346683, T6X, T6W);
            T7a = FMA(KP303346683, T6W, T6X);
          }
          T6T = FMA(KP1_847759065, T6c, T6b);
          T6U = FMA(KP668178637, T6e, T6f);
          T6V = FNMS(KP1_662939224, T6U, T6T);
          T79 = FMA(KP1_662939224, T6U, T6T);
          {
            E T6D, T70, T6G, T71, T6E, T6F;
            T6D = FNMS(KP923879532, T6C, T6B);
            T70 = FMA(KP923879532, T6r, T6q);
            T6E = FMA(KP668178637, T6w, T6x);
            T6F = FNMS(KP668178637, T6t, T6u);
            T6G = SUB(T6E, T6F);
            T71 = ADD(T6E, T6F);
            T6H = FMA(KP831469612, T6G, T6D);
            T7d = FMA(KP831469612, T71, T70);
            T6O = FNMS(KP831469612, T6G, T6D);
            T72 = FNMS(KP831469612, T71, T70);
          }
          {
            E T6s, T73, T6z, T74, T6v, T6y;
            T6s = FNMS(KP923879532, T6r, T6q);
            T73 = FMA(KP923879532, T6C, T6B);
            T6v = FMA(KP668178637, T6u, T6t);
            T6y = FNMS(KP668178637, T6x, T6w);
            T6z = SUB(T6v, T6y);
            T74 = ADD(T6y, T6v);
            T6A = FMA(KP831469612, T6z, T6s);
            T7c = FMA(KP831469612, T74, T73);
            T6P = FNMS(KP831469612, T6z, T6s);
            T75 = FNMS(KP831469612, T74, T73);
          }
        }
        {
          E T6p, T6I, T7b, T7e;
          T6p = FMA(KP1_763842528, T6o, T6h);
          T6I = FNMS(KP250486960, T6H, T6A);
          R1[WS(rs, 34)] = FNMS(KP1_940062506, T6I, T6p);
          R1[WS(rs, 2)] = FMA(KP1_940062506, T6I, T6p);
          T7b = FNMS(KP1_913880671, T7a, T79);
          T7e = FNMS(KP148335987, T7d, T7c);
          R1[WS(rs, 14)] = FNMS(KP1_978353019, T7e, T7b);
          R1[WS(rs, 46)] = FMA(KP1_978353019, T7e, T7b);
        }
        {
          E T7f, T7g, T6J, T6K;
          T7f = FMA(KP1_913880671, T7a, T79);
          T7g = FMA(KP148335987, T7c, T7d);
          R1[WS(rs, 30)] = FNMS(KP1_978353019, T7g, T7f);
          R1[WS(rs, 62)] = FMA(KP1_978353019, T7g, T7f);
          T6J = FNMS(KP1_763842528, T6o, T6h);
          T6K = FMA(KP250486960, T6A, T6H);
          R1[WS(rs, 18)] = FNMS(KP1_940062506, T6K, T6J);
          R1[WS(rs, 50)] = FMA(KP1_940062506, T6K, T6J);
        }
        {
          E T6N, T6Q, T6Z, T76;
          T6N = FNMS(KP1_763842528, T6M, T6L);
          T6Q = FNMS(KP599376933, T6P, T6O);
          R1[WS(rs, 10)] = FNMS(KP1_715457220, T6Q, T6N);
          R1[WS(rs, 42)] = FMA(KP1_715457220, T6Q, T6N);
          T6Z = FNMS(KP1_913880671, T6Y, T6V);
          T76 = FNMS(KP741650546, T75, T72);
          R1[WS(rs, 38)] = FNMS(KP1_606415062, T76, T6Z);
          R1[WS(rs, 6)] = FMA(KP1_606415062, T76, T6Z);
        }
        {
          E T77, T78, T6R, T6S;
          T77 = FMA(KP1_913880671, T6Y, T6V);
          T78 = FMA(KP741650546, T72, T75);
          R1[WS(rs, 22)] = FNMS(KP1_606415062, T78, T77);
          R1[WS(rs, 54)] = FMA(KP1_606415062, T78, T77);
          T6R = FMA(KP1_763842528, T6M, T6L);
          T6S = FMA(KP599376933, T6O, T6P);
          R1[WS(rs, 26)] = FNMS(KP1_715457220, T6S, T6R);
          R1[WS(rs, 58)] = FMA(KP1_715457220, T6S, T6R);
        }
      }
      {
        E T97, T9B, T9e, T9C, T9O, Ta0, T9L, T9Z, T9x, Ta3, T9E, T9S,
         T9q, Ta2, T9F;
        E T9V;
        {
          E T93, T96, T9J, T9K;
          T93 = FNMS(KP1_847759065, T92, T91);
          T96 = FNMS(KP198912367, T95, T94);
          T97 = FNMS(KP1_961570560, T96, T93);
          T9B = FMA(KP1_961570560, T96, T93);
          {
            E T9a, T9d, T9M, T9N;
            T9a = FNMS(KP923879532, T99, T98);
            T9d = FNMS(KP923879532, T9c, T9b);
            T9e = FNMS(KP820678790, T9d, T9a);
            T9C = FMA(KP820678790, T9a, T9d);
            T9M = FMA(KP923879532, T9c, T9b);
            T9N = FMA(KP923879532, T99, T98);
            T9O = FNMS(KP098491403, T9N, T9M);
            Ta0 = FMA(KP098491403, T9M, T9N);
          }
          T9J = FMA(KP1_847759065, T92, T91);
          T9K = FMA(KP198912367, T94, T95);
          T9L = FNMS(KP1_961570560, T9K, T9J);
          T9Z = FMA(KP1_961570560, T9K, T9J);
          {
            E T9t, T9Q, T9w, T9R, T9u, T9v;
            T9t = FNMS(KP923879532, T9s, T9r);
            T9Q = FMA(KP923879532, T9h, T9g);
            T9u = FMA(KP198912367, T9j, T9k);
            T9v = FMA(KP198912367, T9m, T9n);
            T9w = SUB(T9u, T9v);
            T9R = ADD(T9u, T9v);
            T9x = FMA(KP980785280, T9w, T9t);
            Ta3 = FMA(KP980785280, T9R, T9Q);
            T9E = FNMS(KP980785280, T9w, T9t);
            T9S = FNMS(KP980785280, T9R, T9Q);
          }
          {
            E T9i, T9T, T9p, T9U, T9l, T9o;
            T9i = FNMS(KP923879532, T9h, T9g);
            T9T = FMA(KP923879532, T9s, T9r);
            T9l = FNMS(KP198912367, T9k, T9j);
            T9o = FNMS(KP198912367, T9n, T9m);
            T9p = ADD(T9l, T9o);
            T9U = SUB(T9l, T9o);
            T9q = FNMS(KP980785280, T9p, T9i);
            Ta2 = FMA(KP980785280, T9U, T9T);
            T9F = FMA(KP980785280, T9p, T9i);
            T9V = FNMS(KP980785280, T9U, T9T);
          }
        }
        {
          E T9f, T9y, Ta1, Ta4;
          T9f = FMA(KP1_546020906, T9e, T97);
          T9y = FNMS(KP357805721, T9x, T9q);
          R1[WS(rs, 35)] = FNMS(KP1_883088130, T9y, T9f);
          R1[WS(rs, 3)] = FMA(KP1_883088130, T9y, T9f);
          Ta1 = FNMS(KP1_990369453, Ta0, T9Z);
          Ta4 = FNMS(KP049126849, Ta3, Ta2);
          R1[WS(rs, 15)] = FNMS(KP1_997590912, Ta4, Ta1);
          R1[WS(rs, 47)] = FMA(KP1_997590912, Ta4, Ta1);
        }
        {
          E Ta5, Ta6, T9z, T9A;
          Ta5 = FMA(KP1_990369453, Ta0, T9Z);
          Ta6 = FMA(KP049126849, Ta2, Ta3);
          R1[WS(rs, 31)] = FNMS(KP1_997590912, Ta6, Ta5);
          R1[WS(rs, 63)] = FMA(KP1_997590912, Ta6, Ta5);
          T9z = FNMS(KP1_546020906, T9e, T97);
          T9A = FMA(KP357805721, T9q, T9x);
          R1[WS(rs, 19)] = FNMS(KP1_883088130, T9A, T9z);
          R1[WS(rs, 51)] = FMA(KP1_883088130, T9A, T9z);
        }
        {
          E T9D, T9G, T9P, T9W;
          T9D = FNMS(KP1_546020906, T9C, T9B);
          T9G = FNMS(KP472964775, T9F, T9E);
          R1[WS(rs, 11)] = FNMS(KP1_807978586, T9G, T9D);
          R1[WS(rs, 43)] = FMA(KP1_807978586, T9G, T9D);
          T9P = FNMS(KP1_990369453, T9O, T9L);
          T9W = FNMS(KP906347169, T9V, T9S);
          R1[WS(rs, 39)] = FNMS(KP1_481902250, T9W, T9P);
          R1[WS(rs, 7)] = FMA(KP1_481902250, T9W, T9P);
        }
        {
          E T9X, T9Y, T9H, T9I;
          T9X = FMA(KP1_990369453, T9O, T9L);
          T9Y = FMA(KP906347169, T9S, T9V);
          R1[WS(rs, 23)] = FNMS(KP1_481902250, T9Y, T9X);
          R1[WS(rs, 55)] = FMA(KP1_481902250, T9Y, T9X);
          T9H = FMA(KP1_546020906, T9C, T9B);
          T9I = FMA(KP472964775, T9E, T9F);
          R1[WS(rs, 27)] = FNMS(KP1_807978586, T9I, T9H);
          R1[WS(rs, 59)] = FMA(KP1_807978586, T9I, T9H);
        }
      }
    }
  }
}
