/* Generated by: /Users/sfegan/GitHub/fftw3/genfft/gen_notw.native -n 20 -standalone -fma -generic-arith -compact -name dft_codelet_c2c_20 */

/*
 * This function contains 208 FP additions, 72 FP multiplications,
 * (or, 136 additions, 0 multiplications, 72 fused multiply/add),
 * 81 stack variables, 4 constants, and 80 memory accesses
 */
void dft_codelet_c2c_20(const R * ri, const R * ii, R * ro, R * io, stride is, stride os, INT v, INT ivs, INT ovs)
{
  DK(KP951056516, +0.951056516295153572116439333379382143405698634);
  DK(KP559016994, +0.559016994374947424102293417182819058860154590);
  DK(KP618033988, +0.618033988749894848204586834365638117720309180);
  DK(KP250000000, +0.250000000000000000000000000000000000000000000);
  {
    INT i;
    for (i = v; i > 0; i = i - 1, ri = ri + ivs, ii = ii + ivs, ro = ro + ovs, io = io + ovs, MAKE_VOLATILE_STRIDE(80, is), MAKE_VOLATILE_STRIDE(80, os)) {
      E T7, T2N, T3b, TD, TP, T1R, T2f, T1d, Tt, TA, TB, T2w, T2z, T2P,
       T35;
      E T36, T3d, TH, TI, TJ, T15, T1a, T1b, T1s, T1x, T1T, T29, T2a,
       T2h, T1h;
      E T1i, T1j, Te, Tl, Tm, T2D, T2G, T2O, T32, T33, T3c, TE, TF,
       TG, TU;
      E TZ, T10, T1D, T1I, T1S, T26, T27, T2g, T1e, T1f, T1g;
      {
        E T3, T1N, TN, T2L, T6, TO, T1Q, T2M;
        {
          E T1, T2, TL, TM;
          T1 = ri[0];
          T2 = ri[WS(is, 10)];
          T3 = ADD(T1, T2);
          T1N = SUB(T1, T2);
          TL = ii[0];
          TM = ii[WS(is, 10)];
          TN = SUB(TL, TM);
          T2L = ADD(TL, TM);
        }
        {
          E T4, T5, T1O, T1P;
          T4 = ri[WS(is, 5)];
          T5 = ri[WS(is, 15)];
          T6 = ADD(T4, T5);
          TO = SUB(T4, T5);
          T1O = ii[WS(is, 5)];
          T1P = ii[WS(is, 15)];
          T1Q = SUB(T1O, T1P);
          T2M = ADD(T1O, T1P);
        }
        T7 = SUB(T3, T6);
        T2N = SUB(T2L, T2M);
        T3b = ADD(T2L, T2M);
        TD = ADD(T3, T6);
        TP = SUB(TN, TO);
        T1R = SUB(T1N, T1Q);
        T2f = ADD(T1N, T1Q);
        T1d = ADD(TO, TN);
      }
      {
        E Tp, T1o, T13, T2u, Ts, T14, T1r, T2v, Tw, T1t, T18, T2x, Tz,
         T19, T1w;
        E T2y;
        {
          E Tn, To, T11, T12;
          Tn = ri[WS(is, 8)];
          To = ri[WS(is, 18)];
          Tp = ADD(Tn, To);
          T1o = SUB(Tn, To);
          T11 = ii[WS(is, 8)];
          T12 = ii[WS(is, 18)];
          T13 = SUB(T11, T12);
          T2u = ADD(T11, T12);
        }
        {
          E Tq, Tr, T1p, T1q;
          Tq = ri[WS(is, 13)];
          Tr = ri[WS(is, 3)];
          Ts = ADD(Tq, Tr);
          T14 = SUB(Tq, Tr);
          T1p = ii[WS(is, 13)];
          T1q = ii[WS(is, 3)];
          T1r = SUB(T1p, T1q);
          T2v = ADD(T1p, T1q);
        }
        {
          E Tu, Tv, T16, T17;
          Tu = ri[WS(is, 12)];
          Tv = ri[WS(is, 2)];
          Tw = ADD(Tu, Tv);
          T1t = SUB(Tu, Tv);
          T16 = ii[WS(is, 12)];
          T17 = ii[WS(is, 2)];
          T18 = SUB(T16, T17);
          T2x = ADD(T16, T17);
        }
        {
          E Tx, Ty, T1u, T1v;
          Tx = ri[WS(is, 17)];
          Ty = ri[WS(is, 7)];
          Tz = ADD(Tx, Ty);
          T19 = SUB(Tx, Ty);
          T1u = ii[WS(is, 17)];
          T1v = ii[WS(is, 7)];
          T1w = SUB(T1u, T1v);
          T2y = ADD(T1u, T1v);
        }
        Tt = SUB(Tp, Ts);
        TA = SUB(Tw, Tz);
        TB = ADD(Tt, TA);
        T2w = SUB(T2u, T2v);
        T2z = SUB(T2x, T2y);
        T2P = ADD(T2w, T2z);
        T35 = ADD(T2u, T2v);
        T36 = ADD(T2x, T2y);
        T3d = ADD(T35, T36);
        TH = ADD(Tp, Ts);
        TI = ADD(Tw, Tz);
        TJ = ADD(TH, TI);
        T15 = SUB(T13, T14);
        T1a = SUB(T18, T19);
        T1b = ADD(T15, T1a);
        T1s = SUB(T1o, T1r);
        T1x = SUB(T1t, T1w);
        T1T = ADD(T1s, T1x);
        T29 = ADD(T1o, T1r);
        T2a = ADD(T1t, T1w);
        T2h = ADD(T29, T2a);
        T1h = ADD(T14, T13);
        T1i = ADD(T19, T18);
        T1j = ADD(T1h, T1i);
      }
      {
        E Ta, T1z, TS, T2B, Td, TT, T1C, T2C, Th, T1E, TX, T2E, Tk,
         TY, T1H;
        E T2F;
        {
          E T8, T9, TQ, TR;
          T8 = ri[WS(is, 4)];
          T9 = ri[WS(is, 14)];
          Ta = ADD(T8, T9);
          T1z = SUB(T8, T9);
          TQ = ii[WS(is, 4)];
          TR = ii[WS(is, 14)];
          TS = SUB(TQ, TR);
          T2B = ADD(TQ, TR);
        }
        {
          E Tb, Tc, T1A, T1B;
          Tb = ri[WS(is, 9)];
          Tc = ri[WS(is, 19)];
          Td = ADD(Tb, Tc);
          TT = SUB(Tb, Tc);
          T1A = ii[WS(is, 9)];
          T1B = ii[WS(is, 19)];
          T1C = SUB(T1A, T1B);
          T2C = ADD(T1A, T1B);
        }
        {
          E Tf, Tg, TV, TW;
          Tf = ri[WS(is, 16)];
          Tg = ri[WS(is, 6)];
          Th = ADD(Tf, Tg);
          T1E = SUB(Tf, Tg);
          TV = ii[WS(is, 16)];
          TW = ii[WS(is, 6)];
          TX = SUB(TV, TW);
          T2E = ADD(TV, TW);
        }
        {
          E Ti, Tj, T1F, T1G;
          Ti = ri[WS(is, 1)];
          Tj = ri[WS(is, 11)];
          Tk = ADD(Ti, Tj);
          TY = SUB(Ti, Tj);
          T1F = ii[WS(is, 1)];
          T1G = ii[WS(is, 11)];
          T1H = SUB(T1F, T1G);
          T2F = ADD(T1F, T1G);
        }
        Te = SUB(Ta, Td);
        Tl = SUB(Th, Tk);
        Tm = ADD(Te, Tl);
        T2D = SUB(T2B, T2C);
        T2G = SUB(T2E, T2F);
        T2O = ADD(T2D, T2G);
        T32 = ADD(T2B, T2C);
        T33 = ADD(T2E, T2F);
        T3c = ADD(T32, T33);
        TE = ADD(Ta, Td);
        TF = ADD(Th, Tk);
        TG = ADD(TE, TF);
        TU = SUB(TS, TT);
        TZ = SUB(TX, TY);
        T10 = ADD(TU, TZ);
        T1D = SUB(T1z, T1C);
        T1I = SUB(T1E, T1H);
        T1S = ADD(T1D, T1I);
        T26 = ADD(T1z, T1C);
        T27 = ADD(T1E, T1H);
        T2g = ADD(T26, T27);
        T1e = ADD(TT, TS);
        T1f = ADD(TY, TX);
        T1g = ADD(T1e, T1f);
      }
      {
        E T2s, TC, T2r, T2I, T2K, T2A, T2H, T2J, T2t;
        T2s = SUB(Tm, TB);
        TC = ADD(Tm, TB);
        T2r = FNMS(KP250000000, TC, T7);
        T2A = SUB(T2w, T2z);
        T2H = SUB(T2D, T2G);
        T2I = FNMS(KP618033988, T2H, T2A);
        T2K = FMA(KP618033988, T2A, T2H);
        ro[WS(os, 10)] = ADD(T7, TC);
        T2J = FMA(KP559016994, T2s, T2r);
        ro[WS(os, 14)] = FNMS(KP951056516, T2K, T2J);
        ro[WS(os, 6)] = FMA(KP951056516, T2K, T2J);
        T2t = FNMS(KP559016994, T2s, T2r);
        ro[WS(os, 2)] = FNMS(KP951056516, T2I, T2t);
        ro[WS(os, 18)] = FMA(KP951056516, T2I, T2t);
      }
      {
        E T2S, T2Q, T2R, T2W, T2Y, T2U, T2V, T2X, T2T;
        T2S = SUB(T2O, T2P);
        T2Q = ADD(T2O, T2P);
        T2R = FNMS(KP250000000, T2Q, T2N);
        T2U = SUB(Tt, TA);
        T2V = SUB(Te, Tl);
        T2W = FNMS(KP618033988, T2V, T2U);
        T2Y = FMA(KP618033988, T2U, T2V);
        io[WS(os, 10)] = ADD(T2N, T2Q);
        T2X = FMA(KP559016994, T2S, T2R);
        io[WS(os, 6)] = FNMS(KP951056516, T2Y, T2X);
        io[WS(os, 14)] = FMA(KP951056516, T2Y, T2X);
        T2T = FNMS(KP559016994, T2S, T2R);
        io[WS(os, 2)] = FMA(KP951056516, T2W, T2T);
        io[WS(os, 18)] = FNMS(KP951056516, T2W, T2T);
      }
      {
        E T30, TK, T2Z, T38, T3a, T34, T37, T39, T31;
        T30 = SUB(TG, TJ);
        TK = ADD(TG, TJ);
        T2Z = FNMS(KP250000000, TK, TD);
        T34 = SUB(T32, T33);
        T37 = SUB(T35, T36);
        T38 = FMA(KP618033988, T37, T34);
        T3a = FNMS(KP618033988, T34, T37);
        ro[0] = ADD(TD, TK);
        T39 = FNMS(KP559016994, T30, T2Z);
        ro[WS(os, 12)] = FNMS(KP951056516, T3a, T39);
        ro[WS(os, 8)] = FMA(KP951056516, T3a, T39);
        T31 = FMA(KP559016994, T30, T2Z);
        ro[WS(os, 4)] = FNMS(KP951056516, T38, T31);
        ro[WS(os, 16)] = FMA(KP951056516, T38, T31);
      }
      {
        E T3g, T3e, T3f, T3k, T3m, T3i, T3j, T3l, T3h;
        T3g = SUB(T3c, T3d);
        T3e = ADD(T3c, T3d);
        T3f = FNMS(KP250000000, T3e, T3b);
        T3i = SUB(TE, TF);
        T3j = SUB(TH, TI);
        T3k = FMA(KP618033988, T3j, T3i);
        T3m = FNMS(KP618033988, T3i, T3j);
        io[0] = ADD(T3b, T3e);
        T3l = FNMS(KP559016994, T3g, T3f);
        io[WS(os, 8)] = FNMS(KP951056516, T3m, T3l);
        io[WS(os, 12)] = FMA(KP951056516, T3m, T3l);
        T3h = FMA(KP559016994, T3g, T3f);
        io[WS(os, 4)] = FMA(KP951056516, T3k, T3h);
        io[WS(os, 16)] = FNMS(KP951056516, T3k, T3h);
      }
      {
        E T24, T1c, T23, T2c, T2e, T28, T2b, T2d, T25;
        T24 = SUB(T10, T1b);
        T1c = ADD(T10, T1b);
        T23 = FNMS(KP250000000, T1c, TP);
        T28 = SUB(T26, T27);
        T2b = SUB(T29, T2a);
        T2c = FMA(KP618033988, T2b, T28);
        T2e = FNMS(KP618033988, T28, T2b);
        io[WS(os, 5)] = ADD(TP, T1c);
        T2d = FNMS(KP559016994, T24, T23);
        io[WS(os, 13)] = FNMS(KP951056516, T2e, T2d);
        io[WS(os, 17)] = FMA(KP951056516, T2e, T2d);
        T25 = FMA(KP559016994, T24, T23);
        io[WS(os, 1)] = FNMS(KP951056516, T2c, T25);
        io[WS(os, 9)] = FMA(KP951056516, T2c, T25);
      }
      {
        E T2k, T2i, T2j, T2o, T2q, T2m, T2n, T2p, T2l;
        T2k = SUB(T2g, T2h);
        T2i = ADD(T2g, T2h);
        T2j = FNMS(KP250000000, T2i, T2f);
        T2m = SUB(TU, TZ);
        T2n = SUB(T15, T1a);
        T2o = FMA(KP618033988, T2n, T2m);
        T2q = FNMS(KP618033988, T2m, T2n);
        ro[WS(os, 5)] = ADD(T2f, T2i);
        T2p = FNMS(KP559016994, T2k, T2j);
        ro[WS(os, 13)] = FMA(KP951056516, T2q, T2p);
        ro[WS(os, 17)] = FNMS(KP951056516, T2q, T2p);
        T2l = FMA(KP559016994, T2k, T2j);
        ro[WS(os, 1)] = FMA(KP951056516, T2o, T2l);
        ro[WS(os, 9)] = FNMS(KP951056516, T2o, T2l);
      }
      {
        E T1m, T1k, T1l, T1K, T1M, T1y, T1J, T1L, T1n;
        T1m = SUB(T1g, T1j);
        T1k = ADD(T1g, T1j);
        T1l = FNMS(KP250000000, T1k, T1d);
        T1y = SUB(T1s, T1x);
        T1J = SUB(T1D, T1I);
        T1K = FNMS(KP618033988, T1J, T1y);
        T1M = FMA(KP618033988, T1y, T1J);
        io[WS(os, 15)] = ADD(T1d, T1k);
        T1L = FMA(KP559016994, T1m, T1l);
        io[WS(os, 11)] = FNMS(KP951056516, T1M, T1L);
        io[WS(os, 19)] = FMA(KP951056516, T1M, T1L);
        T1n = FNMS(KP559016994, T1m, T1l);
        io[WS(os, 3)] = FNMS(KP951056516, T1K, T1n);
        io[WS(os, 7)] = FMA(KP951056516, T1K, T1n);
      }
      {
        E T1W, T1U, T1V, T20, T22, T1Y, T1Z, T21, T1X;
        T1W = SUB(T1S, T1T);
        T1U = ADD(T1S, T1T);
        T1V = FNMS(KP250000000, T1U, T1R);
        T1Y = SUB(T1h, T1i);
        T1Z = SUB(T1e, T1f);
        T20 = FNMS(KP618033988, T1Z, T1Y);
        T22 = FMA(KP618033988, T1Y, T1Z);
        ro[WS(os, 15)] = ADD(T1R, T1U);
        T21 = FMA(KP559016994, T1W, T1V);
        ro[WS(os, 11)] = FMA(KP951056516, T22, T21);
        ro[WS(os, 19)] = FNMS(KP951056516, T22, T21);
        T1X = FNMS(KP559016994, T1W, T1V);
        ro[WS(os, 3)] = FMA(KP951056516, T20, T1X);
        ro[WS(os, 7)] = FNMS(KP951056516, T20, T1X);
      }
    }
  }
}
