name: CI build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        compiler: [ [gcc-11, g++-11, 'gcc-11 g++-11'],
                    [gcc-10, g++-10, 'gcc-10 g++-10'],
                    [gcc-9, g++-9, 'gcc-9 g++-9'],
                    [gcc-8, g++-8, 'gcc-8 g++-8'],
                    [gcc-7, g++-7, 'gcc-7 g++-7'],
                    [clang-12, clang++-12, 'clang-12'],
                    [clang-11, clang++-11, 'clang-11'],
                    [clang-10, clang++-10, 'clang-10'] ]

    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.compiler[0] }}
      CXX: ${{ matrix.compiler[1] }}

    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gsl-bin libgsl0-dev libfftw3-dev python-numpy  \
          libzmq3-dev python3 python3-dev python3-numpy libxerces-c-dev        \
          libpcap-dev libz-dev libprotobuf-c-dev protobuf-c-compiler           \
          libprotobuf-dev protobuf-compiler libprotoc-dev libzstd-dev          \
          ${{ matrix.compiler[2] }}
        wget https://github.com/llr-cta/CamerasToACTLRelease/releases/download/latest/CamerasToACTL-1.16.1-unknown.x86_64.rpm
        sudo rpm -i CamerasToACTL-1.16.1-unknown.x86_64.rpm
    - name: Print version information
      shell: bash
      run: |
        swig -version
        cmake -version
        $CC -v
        python -V
        python3 -V
    - name: Configure build
      shell: bash
      run: |
        mkdir mybuild
        cd mybuild
        cmake -DCALIN_BUILD_ARCH=broadwell                                \
              -DCMAKE_BUILD_TYPE=Release                                  \
              -DCMAKE_INSTALL_PREFIX=/usr                                 \
              -DCALIN_PYTHON_SUB_DIR=lib/python3.8                        \
              -DNO_GEANT4:BOOLEAN=TRUE                                    \
              ..
    - name: Build
      shell: bash
      run: |
        cd mybuild
        make -j3
    - name: Test
      shell: bash
      run: |
        cd mybuild
        ctest --output-on-failure
